// Engelska i högskoleprovets stil (ELF): egna övningsmeningar och ordförråd, inte provfrågor.
// ENG_GAP: [mening med ___, alternativ (rätt svar först, ett ord per lucka), svårighet 1–3]
// ENG_VOCAB: [ord, närmaste betydelse] – felsvaren tas från andra ords betydelser.
(function (root) {
  const ENG_GAP = [
    ["Despite the heavy rain, the match was not ___.", [["cancelled"], ["played"], ["won"], ["watched"]], 1],
    ["She was so ___ that she fell asleep in the middle of the film.", [["tired"], ["excited"], ["hungry"], ["angry"]], 1],
    ["The museum is ___ to the public every day except Monday.", [["open"], ["close"], ["opened"], ["opening"]], 1],
    ["He apologized for ___ late to the meeting.", [["being"], ["be"], ["been"], ["to be"]], 1],
    ["If I ___ more time, I would learn to play the piano.", [["had"], ["have"], ["will have"], ["am having"]], 1],
    ["The price of the tickets has ___ significantly this year.", [["risen"], ["raised"], ["rose"], ["rising"]], 1],
    ["Could you please ___ me how to get to the station?", [["tell"], ["say"], ["speak"], ["talk"]], 1],
    ["The book was so ___ that I read it in one night.", [["gripping"], ["boring"], ["dull"], ["tedious"]], 1],
    ["They decided to ___ the trip until the weather improved.", [["postpone"], ["prolong"], ["pursue"], ["provide"]], 1],
    ["The new law will come into ___ next year.", [["effect"], ["affect"], ["effort"], ["efficiency"]], 1],
    ["It is important to ___ between facts and opinions.", [["distinguish"], ["discuss"], ["dispute"], ["display"]], 1],
    ["The company had to ___ several employees because of the crisis.", [["lay off"], ["lay down"], ["lay out"], ["lay by"]], 1],
    ["Her explanation was clear and easy to ___.", [["follow"], ["lead"], ["obey"], ["chase"]], 1],
    ["We ran ___ of milk, so I went to the shop.", [["out"], ["off"], ["over"], ["away"]], 1],
    ["The results of the vote were ___: every single member agreed.", [["unanimous"], ["ambiguous"], ["doubtful"], ["scarce"]], 1],
    ["The government has been criticised for its ___ response to the crisis, which many felt came far too late.", [["sluggish"], ["swift"], ["prompt"], ["decisive"]], 2],
    ["Although the evidence was largely ___, the jury still found him guilty.", [["circumstantial"], ["conclusive"], ["overwhelming"], ["irrefutable"]], 2],
    ["The author's latest novel has been ___ by critics as her finest work yet.", [["hailed"], ["dismissed"], ["ignored"], ["banned"]], 2],
    ["Scientists remain ___ about the long-term effects of the new drug.", [["cautious"], ["certain"], ["careless"], ["confident"]], 2],
    ["The two countries signed a treaty to ___ their trade relations.", [["strengthen"], ["weaken"], ["abandon"], ["sever"]], 2],
    ["His ___ remarks offended many people in the audience.", [["insensitive"], ["considerate"], ["tactful"], ["thoughtful"]], 2],
    ["The factory was forced to close after ___ heavy losses for several years.", [["incurring"], ["earning"], ["gaining"], ["avoiding"]], 2],
    ["The instructions were so ___ that nobody understood what to do.", [["vague"], ["precise"], ["explicit"], ["detailed"]], 2],
    ["She has a real ___ for languages and speaks five of them fluently.", [["flair"], ["dislike"], ["fear"], ["lack"]], 2],
    ["The film's success was largely ___ to its brilliant soundtrack.", [["attributed"], ["contributed"], ["distributed"], ["related"]], 2],
    ["Rather than ___ the problem, the manager decided to deal with it directly.", [["ignore"], ["tackle"], ["solve"], ["confront"]], 2],
    ["The expedition had to turn back due to ___ weather conditions.", [["adverse"], ["favourable"], ["mild"], ["pleasant"]], 2],
    ["The report ___ the urgent need for more investment in education.", [["highlights"], ["hides"], ["denies"], ["questions"]], 2],
    ["Local residents were strongly ___ to the plans for a new motorway.", [["opposed"], ["inclined"], ["devoted"], ["accustomed"]], 2],
    ["Many species are now on the ___ of extinction.", [["verge"], ["border"], ["margin"], ["rim"]], 2],
    ["The negotiations reached a ___ when neither side was willing to compromise.", [["deadlock"], ["breakthrough"], ["conclusion"], ["settlement"]], 2],
    ["The theory was initially ___ by the scientific community, but later research ___ its central claims, and it is now widely accepted.", [["dismissed", "confirmed"], ["embraced", "confirmed"], ["ignored", "refuted"], ["accepted", "disproved"]], 3],
    ["Her argument, though ___, failed to ___ the committee.", [["compelling", "convince"], ["weak", "impress"], ["flawed", "confuse"], ["brief", "bore"]], 3],
    ["The ___ of the new policy were not immediately ___, and it took years before its full impact was understood.", [["consequences", "apparent"], ["benefits", "hidden"], ["causes", "obvious"], ["origins", "relevant"]], 3],
    ["Critics ___ the decision as short-sighted, arguing that it would ___ long-term growth.", [["condemned", "undermine"], ["praised", "boost"], ["welcomed", "hinder"], ["described", "encourage"]], 3],
    ["The company's ___ growth has made it one of the most ___ firms in the industry.", [["rapid", "influential"], ["sluggish", "powerful"], ["steady", "obscure"], ["declining", "dominant"]], 3],
    ["Although the task seemed ___ at first, it turned out to be surprisingly ___.", [["daunting", "manageable"], ["simple", "easy"], ["impossible", "difficult"], ["trivial", "straightforward"]], 3],
    ["The witness gave a ___ account of the events, which the police found highly ___.", [["detailed", "credible"], ["vague", "reliable"], ["confused", "convincing"], ["brief", "exhaustive"]], 3],
    ["In ___ of the recent findings, the researchers were forced to ___ their original hypothesis.", [["light", "revise"], ["spite", "confirm"], ["case", "abandon"], ["view", "maintain"]], 3],
    ["The negotiations were ___ by mutual suspicion, making any ___ extremely difficult.", [["hampered", "agreement"], ["helped", "conflict"], ["marked", "dispute"], ["eased", "compromise"]], 3],
    ["His ___ attitude towards safety regulations eventually led to a ___ accident.", [["cavalier", "serious"], ["careful", "fatal"], ["strict", "minor"], ["cautious", "tragic"]], 3],
    ["The novel ___ the lives of three generations, offering a ___ portrait of a changing society.", [["spans", "vivid"], ["ignores", "faithful"], ["shortens", "blurred"], ["limits", "broad"]], 3],
    ["Public ___ for the project waned as the costs began to ___.", [["support", "soar"], ["opposition", "rise"], ["interest", "fall"], ["enthusiasm", "drop"]], 3],
  ];

  const ENG_VOCAB = [
    ["abandon", "give up"], ["abundant", "plentiful"], ["accurate", "exact"], ["acquire", "obtain"],
    ["adequate", "sufficient"], ["adverse", "harmful"], ["advocate", "support"], ["allocate", "distribute"],
    ["ambiguous", "unclear"], ["amend", "change slightly"], ["anticipate", "expect"], ["apparent", "obvious"],
    ["arbitrary", "random"], ["assess", "evaluate"], ["assume", "suppose"], ["attain", "achieve"],
    ["authentic", "genuine"], ["benevolent", "kind"], ["bewildered", "confused"], ["brief", "short"],
    ["candid", "frank"], ["cautious", "careful"], ["cease", "stop"], ["coherent", "logical"],
    ["commence", "begin"], ["compel", "force"], ["comprehensive", "thorough"], ["conceal", "hide"],
    ["concise", "short and clear"], ["confine", "restrict"], ["consequence", "result"], ["considerable", "substantial"],
    ["contemplate", "consider"], ["contradict", "deny"], ["convey", "communicate"], ["crucial", "vital"],
    ["curb", "limit"], ["deceive", "mislead"], ["decline", "decrease"], ["deliberate", "intentional"],
    ["deprive", "take away from"], ["derive", "come from"], ["detrimental", "damaging"], ["deter", "discourage"],
    ["devastate", "destroy"], ["diligent", "hard-working"], ["diminish", "reduce"], ["discard", "throw away"],
    ["disclose", "reveal"], ["discreet", "tactful"], ["dismiss", "reject"], ["disperse", "scatter"],
    ["distinct", "clearly different"], ["diverse", "varied"], ["dubious", "doubtful"], ["durable", "long-lasting"],
    ["elaborate", "detailed"], ["eligible", "qualified"], ["elusive", "hard to find"], ["emerge", "appear"],
    ["emphasize", "stress"], ["endeavour", "attempt"], ["enhance", "improve"], ["enormous", "huge"],
    ["entire", "whole"], ["erratic", "unpredictable"], ["essential", "necessary"], ["evident", "clear"],
    ["exaggerate", "overstate"], ["exceed", "go beyond"], ["exhausted", "very tired"], ["explicit", "clearly stated"],
    ["exploit", "take advantage of"], ["feasible", "possible"], ["feeble", "weak"], ["fierce", "violent"],
    ["flaw", "defect"], ["fluctuate", "vary"], ["forbid", "prohibit"], ["fragile", "easily broken"],
    ["frugal", "thrifty"], ["futile", "pointless"], ["grim", "gloomy"], ["hazard", "danger"],
    ["hesitant", "unsure"], ["hostile", "unfriendly"], ["imminent", "about to happen"], ["impartial", "neutral"],
    ["impede", "hinder"], ["implement", "carry out"], ["implicit", "implied"], ["inevitable", "unavoidable"],
    ["inferior", "lower in quality"], ["inhabit", "live in"], ["inherent", "built-in"], ["initiate", "set in motion"],
    ["innate", "inborn"], ["intricate", "complex"], ["intrinsic", "fundamental"], ["invaluable", "extremely useful"],
    ["lethal", "deadly"], ["lucid", "easy to understand"], ["lucrative", "profitable"], ["meagre", "scanty"],
    ["meticulous", "extremely careful"], ["mitigate", "ease"], ["modest", "humble"], ["mundane", "ordinary"],
    ["negligible", "insignificant"], ["notorious", "infamous"], ["novel", "new and original"], ["obsolete", "outdated"],
    ["obstacle", "barrier"], ["omit", "leave out"], ["ongoing", "continuing"], ["optimal", "best"],
    ["ordeal", "painful experience"], ["overwhelm", "overpower"], ["paramount", "supreme"], ["persevere", "persist"],
    ["persuade", "convince"], ["pertinent", "relevant"], ["plausible", "believable"], ["ponder", "think over"],
    ["predominant", "main"], ["prevalent", "widespread"], ["profound", "deep"], ["prominent", "well-known"],
    ["prompt", "quick"], ["prosper", "flourish"], ["prudent", "wise"], ["pursue", "chase"],
    ["reckless", "careless"], ["reinforce", "strengthen"], ["reluctant", "unwilling"], ["remedy", "cure"],
    ["resilient", "quick to recover"], ["restrain", "hold back"], ["retain", "keep"], ["rigid", "stiff"],
    ["robust", "strong"], ["scarce", "rare"], ["scrutinize", "examine closely"], ["shrewd", "clever"],
    ["significant", "important"], ["simultaneous", "at the same time"], ["sole", "only"], ["sparse", "thinly scattered"],
    ["spontaneous", "unplanned"], ["stagnant", "not moving"], ["subsequent", "following"], ["subtle", "delicate"],
    ["superficial", "shallow"], ["supplement", "add to"], ["suppress", "put down"], ["surplus", "excess"],
    ["susceptible", "vulnerable"], ["tedious", "boring"], ["tentative", "provisional"], ["thrive", "grow well"],
    ["tranquil", "calm"], ["transparent", "see-through"], ["trivial", "unimportant"], ["ubiquitous", "found everywhere"],
    ["undermine", "weaken"], ["unprecedented", "never done before"], ["utilize", "use"], ["vague", "not clearly expressed"],
    ["valid", "sound"], ["vast", "immense"], ["verify", "confirm"], ["viable", "workable"],
    ["vigorous", "energetic"], ["vivid", "bright"], ["wary", "watchful"], ["yield", "produce"], ["zealous", "passionate"],
  ];

  const api = { ENG_GAP, ENG_VOCAB };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else Object.assign(root, { HP_ENG_GAP: ENG_GAP, HP_ENG_VOCAB: ENG_VOCAB });
})(this);
