// Engelska i högskoleprovets stil (ELF): egna övningsmeningar och ordförråd, inte provfrågor.
// ENG_GAP: [mening med ___, alternativ (rätt svar först, ett ord per lucka), svårighet 1–3]
// ENG_VOCAB: [ord, närmaste betydelse] – felsvaren tas från andra ords betydelser.
(function (root) {
  const ENG_GAP = [
    ["Despite the heavy rain, the match was not ___.", [["cancelled"], ["played"], ["won"], ["watched"]], 1],
    ["She was so ___ that she fell asleep in the middle of the film.", [["tired"], ["excited"], ["hungry"], ["angry"]], 1],
    ["The museum is ___ to the public every day except Monday.", [["open"], ["close"], ["opened"], ["opening"]], 1],
    ["He apologized for ___ late to the meeting.", [["being"], ["be"], ["been"], ["to be"]], 1],
    ["If I ___ more time, I would learn to play the piano.", [["had"], ["have"], ["will have"], ["am having"]], 1],
    ["The price of the tickets has ___ significantly this year.", [["risen"], ["raised"], ["rose"], ["rising"]], 1],
    ["Could you please ___ me how to get to the station?", [["tell"], ["say"], ["speak"], ["talk"]], 1],
    ["The book was so ___ that I read it in one night.", [["gripping"], ["boring"], ["dull"], ["tedious"]], 1],
    ["They decided to ___ the trip until the weather improved.", [["postpone"], ["prolong"], ["pursue"], ["provide"]], 1],
    ["The new law will come into ___ next year.", [["effect"], ["affect"], ["effort"], ["efficiency"]], 1],
    ["It is important to ___ between facts and opinions.", [["distinguish"], ["discuss"], ["dispute"], ["display"]], 1],
    ["The company had to ___ several employees because of the crisis.", [["lay off"], ["lay down"], ["lay out"], ["lay by"]], 1],
    ["Her explanation was clear and easy to ___.", [["follow"], ["lead"], ["obey"], ["chase"]], 1],
    ["We ran ___ of milk, so I went to the shop.", [["out"], ["off"], ["over"], ["away"]], 1],
    ["The results of the vote were ___: every single member agreed.", [["unanimous"], ["ambiguous"], ["doubtful"], ["scarce"]], 1],
    ["The government has been criticised for its ___ response to the crisis, which many felt came far too late.", [["sluggish"], ["swift"], ["prompt"], ["decisive"]], 2],
    ["Although the evidence was largely ___, the jury still found him guilty.", [["circumstantial"], ["conclusive"], ["overwhelming"], ["irrefutable"]], 2],
    ["The author's latest novel has been ___ by critics as her finest work yet.", [["hailed"], ["dismissed"], ["ignored"], ["banned"]], 2],
    ["Scientists remain ___ about the long-term effects of the new drug.", [["cautious"], ["certain"], ["careless"], ["confident"]], 2],
    ["The two countries signed a treaty to ___ their trade relations.", [["strengthen"], ["weaken"], ["abandon"], ["sever"]], 2],
    ["His ___ remarks offended many people in the audience.", [["insensitive"], ["considerate"], ["tactful"], ["thoughtful"]], 2],
    ["The factory was forced to close after ___ heavy losses for several years.", [["incurring"], ["earning"], ["gaining"], ["avoiding"]], 2],
    ["The instructions were so ___ that nobody understood what to do.", [["vague"], ["precise"], ["explicit"], ["detailed"]], 2],
    ["She has a real ___ for languages and speaks five of them fluently.", [["flair"], ["dislike"], ["fear"], ["lack"]], 2],
    ["The film's success was largely ___ to its brilliant soundtrack.", [["attributed"], ["contributed"], ["distributed"], ["related"]], 2],
    ["Rather than ___ the problem, the manager decided to deal with it directly.", [["ignore"], ["tackle"], ["solve"], ["confront"]], 2],
    ["The expedition had to turn back due to ___ weather conditions.", [["adverse"], ["favourable"], ["mild"], ["pleasant"]], 2],
    ["The report ___ the urgent need for more investment in education.", [["highlights"], ["hides"], ["denies"], ["questions"]], 2],
    ["Local residents were strongly ___ to the plans for a new motorway.", [["opposed"], ["inclined"], ["devoted"], ["accustomed"]], 2],
    ["Many species are now on the ___ of extinction.", [["verge"], ["border"], ["margin"], ["rim"]], 2],
    ["The negotiations reached a ___ when neither side was willing to compromise.", [["deadlock"], ["breakthrough"], ["conclusion"], ["settlement"]], 2],
    ["The theory was initially ___ by the scientific community, but later research ___ its central claims, and it is now widely accepted.", [["dismissed", "confirmed"], ["embraced", "confirmed"], ["ignored", "refuted"], ["accepted", "disproved"]], 3],
    ["Her argument, though ___, failed to ___ the committee.", [["compelling", "convince"], ["weak", "impress"], ["flawed", "confuse"], ["brief", "bore"]], 3],
    ["The ___ of the new policy were not immediately ___, and it took years before its full impact was understood.", [["consequences", "apparent"], ["benefits", "hidden"], ["causes", "obvious"], ["origins", "relevant"]], 3],
    ["Critics ___ the decision as short-sighted, arguing that it would ___ long-term growth.", [["condemned", "undermine"], ["praised", "boost"], ["welcomed", "hinder"], ["described", "encourage"]], 3],
    ["The company's ___ growth has made it one of the most ___ firms in the industry.", [["rapid", "influential"], ["sluggish", "powerful"], ["steady", "obscure"], ["declining", "dominant"]], 3],
    ["Although the task seemed ___ at first, it turned out to be surprisingly ___.", [["daunting", "manageable"], ["simple", "easy"], ["impossible", "difficult"], ["trivial", "straightforward"]], 3],
    ["The witness gave a ___ account of the events, which the police found highly ___.", [["detailed", "credible"], ["vague", "reliable"], ["confused", "convincing"], ["brief", "exhaustive"]], 3],
    ["In ___ of the recent findings, the researchers were forced to ___ their original hypothesis.", [["light", "revise"], ["spite", "confirm"], ["case", "abandon"], ["view", "maintain"]], 3],
    ["The negotiations were ___ by mutual suspicion, making any ___ extremely difficult.", [["hampered", "agreement"], ["helped", "conflict"], ["marked", "dispute"], ["eased", "compromise"]], 3],
    ["His ___ attitude towards safety regulations eventually led to a ___ accident.", [["cavalier", "serious"], ["careful", "fatal"], ["strict", "minor"], ["cautious", "tragic"]], 3],
    ["The novel ___ the lives of three generations, offering a ___ portrait of a changing society.", [["spans", "vivid"], ["ignores", "faithful"], ["shortens", "blurred"], ["limits", "broad"]], 3],
    ["Public ___ for the project waned as the costs began to ___.", [["support", "soar"], ["opposition", "rise"], ["interest", "fall"], ["enthusiasm", "drop"]], 3],
    // ---- Fler övningar ----
    ["I have lived in this town ___ I was a child.",[["since"], ["for"], ["from"], ["during"]],1],
    ["There aren't ___ eggs left, so we need to buy some more.",[["any"], ["some"], ["much"], ["no"]],1],
    ["She is the ___ student in the whole class.",[["best"], ["better"], ["good"], ["well"]],1],
    ["We were looking forward ___ the summer holidays.",[["to"], ["for"], ["at"], ["on"]],1],
    ["He has been working here ___ ten years.",[["for"], ["since"], ["during"], ["ago"]],1],
    ["The film was so ___ that many people left before the end.",[["boring"], ["bored"], ["bore"], ["bores"]],1],
    ["I don't know ___ she will come to the party or not.",[["whether"], ["unless"], ["weather"], ["either"]],1],
    ["Neither my brother ___ my sister likes coffee.",[["nor"], ["or"], ["and"], ["but"]],1],
    ["You ___ smoke in here – it is strictly forbidden.",[["mustn't"], ["don't have to"], ["needn't"], ["wouldn't"]],1],
    ["The children were told to ___ quiet during the ceremony.",[["keep"], ["hold"], ["stand"], ["save"]],1],
    ["Everybody ___ to be happy.",[["wants"], ["want"], ["wanting"], ["are wanting"]],1],
    ["Could you ___ me a favour and close the window?",[["do"], ["make"], ["give"], ["take"]],1],
    ["She has ___ money than her brother.",[["less"], ["fewer"], ["little"], ["least"]],1],
    ["The train was delayed ___ the snow.",[["because of"], ["because"], ["although"], ["despite of"]],1],
    ["I'm not used to ___ up so early in the morning.",[["getting"], ["get"], ["got"], ["have got"]],1],
    ["He asked me where ___.",[["I lived"], ["did I live"], ["do I live"], ["I do live"]],1],
    ["By the time we arrived, the concert ___ already started.",[["had"], ["has"], ["have"], ["was"]],1],
    ["If it rains tomorrow, we ___ stay at home.",[["will"], ["would"], ["had"], ["did"]],1],
    ["This is the house ___ my grandparents used to live.",[["where"], ["which"], ["who"], ["what"]],1],
    ["They made him ___ the whole room again.",[["clean"], ["to clean"], ["cleaning"], ["cleaned"]],1],
    ["The information you gave me ___ very useful.",[["was"], ["were"], ["are"], ["have been"]],1],
    ["I'd rather ___ at home tonight.",[["stay"], ["to stay"], ["staying"], ["stayed"]],1],
    ["He is ___ honest man that everyone trusts him.",[["such an"], ["so an"], ["such"], ["so"]],1],
    ["The meeting has been ___ until next week.",[["postponed"], ["prevented"], ["preferred"], ["provided"]],1],
    ["She couldn't ___ the noise any longer and moved out.",[["stand"], ["bear with"], ["accept to"], ["suffer"]],1],
    ["It's no use ___ about it now – it's too late.",[["worrying"], ["to worry"], ["worry"], ["worried"]],1],
    ["The doctor ___ me to take a few days off work.",[["advised"], ["suggested"], ["proposed"], ["insisted"]],1],
    ["Hardly anyone ___ up for the early lecture.",[["turned"], ["took"], ["gave"], ["put"]],1],
    ["The committee's decision was ___, with all twelve members voting in favour.",[["unanimous"], ["anonymous"], ["ambiguous"], ["arbitrary"]],2],
    ["The drug is effective, but its side effects can be ___.",[["severe"], ["cordial"], ["meagre"], ["frugal"]],2],
    ["After years of ___, the two countries finally signed a peace treaty.",[["hostility"], ["hospitality"], ["humility"], ["hilarity"]],2],
    ["The new manager quickly ___ a reputation for being fair but demanding.",[["acquired"], ["required"], ["inquired"], ["retired"]],2],
    ["Most scientists ___ that the climate is changing faster than expected.",[["agree"], ["argue with"], ["accord"], ["assent"]],2],
    ["The evidence was ___, so the case was dismissed.",[["insufficient"], ["inefficient"], ["indifferent"], ["insistent"]],2],
    ["Her explanation was so ___ that even the children understood it.",[["lucid"], ["obscure"], ["verbose"], ["opaque"]],2],
    ["The company was forced to ___ hundreds of workers during the recession.",[["lay off"], ["lay down"], ["lay out"], ["lay by"]],2],
    ["Tourism has had a ___ effect on the local economy, creating thousands of jobs.",[["beneficial"], ["detrimental"], ["negligible"], ["hostile"]],2],
    ["He was ___ of stealing the money, but there was no proof.",[["suspected"], ["suspicious"], ["suspect"], ["suspecting"]],2],
    ["The ___ of the new vaccine took less than a year.",[["development"], ["developer"], ["developing"], ["developed"]],2],
    ["It was an ___ decision; nobody could see any reason behind it.",[["arbitrary"], ["obvious"], ["informed"], ["deliberate"]],2],
    ["The book gives a ___ overview of the history of the region, covering two thousand years.",[["comprehensive"], ["comprehensible"], ["compulsory"], ["competitive"]],2],
    ["Children are often more ___ to infections than adults.",[["susceptible"], ["sensible"], ["resistant"], ["reluctant"]],2],
    ["The politician refused to ___ on the rumours about his resignation.",[["comment"], ["remark"], ["mention"], ["notice"]],2],
    ["The success of the project ___ on everyone doing their part.",[["depends"], ["consists"], ["counts"], ["bases"]],2],
    ["Her ___ to detail made her an excellent editor.",[["attention"], ["tension"], ["intention"], ["retention"]],2],
    ["The storm caused ___ damage to the coastal towns.",[["extensive"], ["expensive"], ["expansive"], ["excessive"]],2],
    ["Rather than ___ the problem, the government chose to ignore it.",[["address"], ["dress"], ["redress"], ["stress"]],2],
    ["The results of the survey should be interpreted with ___, as the sample was small.",[["caution"], ["courage"], ["confidence"], ["certainty"]],2],
    ["The old factory has been ___ into luxury apartments.",[["converted"], ["conveyed"], ["convinced"], ["concerned"]],2],
    ["She was ___ to admit that she had made a mistake.",[["reluctant"], ["relevant"], ["resilient"], ["redundant"]],2],
    ["The negotiations ___ down when neither side was willing to compromise.",[["broke"], ["turned"], ["cut"], ["fell"]],2],
    ["The regulations are ___ enforced, so few companies bother to follow them.",[["rarely"], ["strictly"], ["heavily"], ["closely"]],2],
    ["Researchers ___ the data carefully before publishing their findings.",[["scrutinized"], ["scattered"], ["summoned"], ["suppressed"]],2],
    ["The island's ___ wildlife attracts biologists from all over the world.",[["unique"], ["uniform"], ["united"], ["universal"]],2],
    ["He tried to ___ his disappointment, but everyone could see how upset he was.",[["conceal"], ["reveal"], ["display"], ["confess"]],2],
    ["In ___ to popular belief, bats are not blind.",[["contrast"], ["contrary"], ["opposite"], ["comparison"]],2],
    ["The new law will come into ___ on the first of January.",[["force"], ["power"], ["motion"], ["action"]],2],
    ["Although the theory is ___ elegant, it has so far been ___ by very little experimental evidence.",[["mathematically", "supported"], ["practically", "refuted"], ["hardly", "confirmed"], ["rarely", "undermined"]],3],
    ["Far from being ___, the new rules have made the process even more ___.",[["simplified", "complicated"], ["complicated", "simple"], ["abolished", "rigid"], ["welcomed", "popular"]],3],
    ["The author's ___ style, full of long digressions, makes the book ___ to read.",[["verbose", "tedious"], ["succinct", "tiresome"], ["lucid", "difficult"], ["concise", "boring"]],3],
    ["What was once considered a ___ luxury has now become an everyday ___.",[["rare", "necessity"], ["common", "extravagance"], ["cheap", "burden"], ["modest", "rarity"]],3],
    ["The minister's ___ reply only ___ suspicions that something was being hidden.",[["evasive", "fuelled"], ["candid", "confirmed"], ["frank", "dispelled"], ["prompt", "eased"]],3],
    ["Critics ___ the film for its stunning photography but found the plot ___.",[["praised", "predictable"], ["blamed", "original"], ["attacked", "gripping"], ["ignored", "brilliant"]],3],
    ["Unlike her ___ predecessor, the new director is willing to ___ risks.",[["cautious", "take"], ["reckless", "avoid"], ["bold", "make"], ["timid", "do"]],3],
    ["The species was thought to be ___, until a small population was ___ in a remote valley.",[["extinct", "discovered"], ["abundant", "found"], ["dormant", "destroyed"], ["endangered", "lost"]],3],
    ["The report ___ that the problem is not a lack of money but a ___ of coordination.",[["concludes", "lack"], ["denies", "surplus"], ["assumes", "wealth"], ["questions", "result"]],3],
    ["His ___ optimism seemed ___ given the gravity of the situation.",[["unwavering", "misplaced"], ["cautious", "justified"], ["reluctant", "appropriate"], ["feeble", "warranted"]],3],
    ["The ___ of the evidence was so great that even the most ___ members of the jury were convinced.",[["weight", "sceptical"], ["lack", "gullible"], ["absence", "doubtful"], ["size", "certain"]],3],
    ["Rather than ___ the crisis, the measures seem to have ___ it.",[["alleviated", "aggravated"], ["worsened", "solved"], ["caused", "prevented"], ["ignored", "noticed"]],3],
    ["The language is ___ with borrowed words, most of which were ___ during the Middle Ages.",[["replete", "adopted"], ["devoid", "invented"], ["scarce", "abandoned"], ["empty", "rejected"]],3],
    ["The treaty was meant to be ___, but it was ___ within ten years.",[["permanent", "broken"], ["temporary", "honoured"], ["brief", "extended"], ["fragile", "respected"]],3],
    ["She spoke so ___ that the audience hung on her every word; few speakers have been so ___.",[["eloquently", "captivating"], ["hesitantly", "convincing"], ["quietly", "tedious"], ["vaguely", "persuasive"]],3],
    ["Economic growth alone is ___ to reduce poverty; the benefits must also be ___ distributed.",[["insufficient", "fairly"], ["enough", "unequally"], ["adequate", "narrowly"], ["essential", "rarely"]],3],
    ["The professor, ___ known for her strict grading, surprised everyone by being unusually ___.",[["notoriously", "lenient"], ["rarely", "harsh"], ["hardly", "severe"], ["famously", "strict"]],3],
    ["The discovery was ___ rather than planned; the researchers ___ upon it while looking for something else.",[["accidental", "stumbled"], ["deliberate", "came"], ["intended", "relied"], ["predictable", "insisted"]],3],
  ];

  const ENG_VOCAB = [
    ["abandon", "give up"], ["abolish", "do away with"], ["abrupt", "sudden and unexpected"], ["absurd", "ridiculous"], ["abundant", "plentiful"],
    ["accelerate", "speed up"], ["accommodate", "provide room for"], ["accumulate", "gather over time"], ["accurate", "exact"], ["acknowledge", "admit"],
    ["acquire", "obtain"], ["acute", "severe"], ["adapt", "adjust"], ["adequate", "sufficient"], ["adjacent", "next to"],
    ["adverse", "harmful"], ["advocate", "support"], ["affluent", "wealthy"], ["aggravate", "make worse"], ["agile", "quick and nimble"],
    ["alleviate", "relieve"], ["allocate", "distribute"], ["alter", "change"], ["ambiguous", "unclear"], ["amend", "change slightly"],
    ["ample", "more than enough"], ["anonymous", "without a known name"], ["anticipate", "expect"], ["apparent", "obvious"], ["apprehensive", "uneasy"],
    ["arbitrary", "random"], ["arduous", "very difficult and tiring"], ["articulate", "express clearly"], ["ascend", "go up"], ["aspire", "aim for"],
    ["assess", "evaluate"], ["assume", "suppose"], ["astonish", "amaze"], ["attain", "achieve"], ["audacious", "daring"],
    ["augment", "enlarge"], ["authentic", "genuine"], ["avert", "prevent"], ["benevolent", "kind"], ["bewildered", "confused"],
    ["bias", "prejudice"], ["bleak", "hopeless"], ["blunt", "very direct"], ["bolster", "prop up"], ["brief", "short"],
    ["brittle", "hard but easily snapped"], ["candid", "frank"], ["cater", "provide for"], ["cautious", "careful"], ["cease", "stop"],
    ["chronic", "persisting for a long time"], ["clarify", "make clear"], ["coherent", "logical"], ["coincide", "happen at the same time"], ["collapse", "fall down"],
    ["commence", "begin"], ["commonplace", "everyday"], ["compassion", "sympathy"], ["compatible", "able to work together"], ["compel", "force"],
    ["compensate", "make up for"], ["compile", "put together"], ["complacent", "too satisfied with oneself"], ["comply", "obey"], ["comprehensive", "thorough"],
    ["conceal", "hide"], ["concede", "admit defeat"], ["concise", "short and clear"], ["concur", "agree"], ["condemn", "strongly criticize"],
    ["confine", "restrict"], ["confront", "face"], ["consent", "permission"], ["consequence", "result"], ["considerable", "substantial"],
    ["conspicuous", "easy to notice"], ["constrain", "hold within limits"], ["contaminate", "pollute"], ["contemplate", "consider"], ["contempt", "scorn"],
    ["contradict", "deny"], ["convene", "come together"], ["convey", "communicate"], ["cordial", "warm and friendly"], ["corrode", "wear away"],
    ["credible", "trustworthy"], ["crucial", "vital"], ["cumbersome", "awkward to carry"], ["cunning", "sly"], ["curb", "limit"],
    ["customary", "usual"], ["dearth", "lack"], ["debris", "scattered remains"], ["deceive", "mislead"], ["decisive", "resolute"],
    ["decline", "decrease"], ["defer", "postpone"], ["deficient", "lacking"], ["defy", "resist openly"], ["degrade", "reduce in quality"],
    ["deliberate", "intentional"], ["dense", "thick"], ["depict", "portray"], ["deplete", "use up"], ["deprive", "take away from"],
    ["derive", "come from"], ["desolate", "empty and bleak"], ["deter", "discourage"], ["detrimental", "damaging"], ["devastate", "destroy"],
    ["deviate", "depart from the norm"], ["devise", "invent"], ["devoid", "completely without"], ["dilemma", "difficult choice"], ["diligent", "hard-working"],
    ["diminish", "reduce"], ["discard", "throw away"], ["discern", "perceive"], ["disclose", "reveal"], ["discreet", "tactful"],
    ["disdain", "feeling of superiority"], ["dismal", "depressing"], ["dismiss", "reject"], ["disparity", "inequality"], ["disperse", "scatter"],
    ["dispute", "disagreement"], ["disrupt", "interrupt"], ["dissent", "disagreement with authority"], ["distinct", "clearly different"], ["distort", "twist"],
    ["diverse", "varied"], ["docile", "easily controlled"], ["dormant", "inactive"], ["drastic", "extreme"], ["dubious", "doubtful"],
    ["durable", "long-lasting"], ["dwindle", "shrink gradually"], ["eager", "keen"], ["eccentric", "odd"], ["elaborate", "detailed"],
    ["elicit", "draw out"], ["eligible", "qualified"], ["eloquent", "well-spoken"], ["elusive", "hard to find"], ["embark", "set out"],
    ["embrace", "accept willingly"], ["emerge", "appear"], ["eminent", "distinguished"], ["empathy", "understanding of others' feelings"], ["emphasize", "stress"],
    ["encompass", "include"], ["endeavour", "attempt"], ["endorse", "support publicly"], ["endure", "put up with"], ["enhance", "improve"],
    ["enigma", "mystery"], ["enormous", "huge"], ["entire", "whole"], ["ephemeral", "short-lived"], ["equitable", "fair"],
    ["eradicate", "wipe out"], ["erode", "wear down"], ["erratic", "unpredictable"], ["essential", "necessary"], ["evade", "escape from"],
    ["evident", "clear"], ["evoke", "call to mind"], ["exaggerate", "overstate"], ["exceed", "go beyond"], ["exemplary", "serving as a model"],
    ["exempt", "free from an obligation"], ["exhausted", "very tired"], ["explicit", "clearly stated"], ["exploit", "take advantage of"], ["exquisite", "extremely beautiful"],
    ["extinct", "no longer existing"], ["fabricate", "make up"], ["facilitate", "make easier"], ["fallacy", "mistaken belief"], ["feasible", "possible"],
    ["feeble", "weak"], ["fervent", "intense"], ["fickle", "changeable"], ["fierce", "violent"], ["flaw", "defect"],
    ["flourish", "blossom"], ["fluctuate", "vary"], ["forbid", "prohibit"], ["foresee", "predict"], ["formidable", "impressive and frightening"],
    ["fortify", "reinforce"], ["fragile", "easily broken"], ["frail", "physically delicate"], ["frantic", "desperate"], ["fraudulent", "dishonest"],
    ["frugal", "thrifty"], ["futile", "pointless"], ["gauge", "measure"], ["genuine", "real"], ["gratify", "please"],
    ["grim", "gloomy"], ["gullible", "easily fooled"], ["harsh", "cruel"], ["haughty", "arrogant"], ["hazard", "danger"],
    ["heed", "pay attention to"], ["hesitant", "unsure"], ["hinder", "obstruct"], ["hostile", "unfriendly"], ["hypothetical", "imagined"],
    ["illuminate", "light up"], ["illusion", "false impression"], ["immense", "vast in size"], ["imminent", "about to happen"], ["impair", "damage"],
    ["impartial", "neutral"], ["impartiality", "lack of bias"], ["impede", "hinder"], ["impetus", "driving force"], ["implement", "carry out"],
    ["implicate", "involve in a crime"], ["implicit", "implied"], ["impose", "force upon"], ["inadvertent", "unintentional"], ["incentive", "motivation"],
    ["incessant", "never-ending"], ["incidental", "of minor importance"], ["incite", "provoke"], ["inclined", "likely"], ["incompatible", "unable to coexist"],
    ["indifferent", "uninterested"], ["indigenous", "native"], ["indulge", "give in to a desire"], ["inevitable", "unavoidable"], ["infer", "conclude"],
    ["inferior", "lower in quality"], ["infringe", "violate"], ["ingenious", "inventive"], ["inhabit", "live in"], ["inherent", "built-in"],
    ["inhibit", "prevent from acting freely"], ["initial", "first"], ["initiate", "set in motion"], ["innate", "inborn"], ["innocuous", "harmless"],
    ["insight", "deep understanding"], ["integrity", "honesty"], ["intervene", "step in"], ["intimidate", "frighten"], ["intrepid", "fearless"],
    ["intricate", "complex"], ["intrinsic", "fundamental"], ["intrude", "enter without permission"], ["invaluable", "extremely useful"], ["invoke", "appeal to"],
    ["jeopardize", "put at risk"], ["justify", "defend"], ["keen", "enthusiastic"], ["lament", "mourn"], ["lavish", "extravagant"],
    ["legitimate", "lawful"], ["lenient", "not strict"], ["lethal", "deadly"], ["linger", "stay longer"], ["lucid", "easy to understand"],
    ["lucrative", "profitable"], ["lure", "tempt"], ["malicious", "spiteful"], ["mandatory", "compulsory"], ["manifest", "show clearly"],
    ["meagre", "scanty"], ["mediocre", "average"], ["menace", "threat"], ["mend", "repair"], ["meticulous", "extremely careful"],
    ["mimic", "imitate"], ["misconception", "false idea"], ["mitigate", "ease"], ["mobilize", "organize for action"], ["modest", "humble"],
    ["monotonous", "dull and repetitive"], ["mundane", "ordinary"], ["mutual", "shared"], ["naive", "innocent"], ["negligent", "failing to take proper care"],
    ["negligible", "insignificant"], ["nostalgia", "longing for the past"], ["notorious", "infamous"], ["nourish", "feed"], ["novel", "new and original"],
    ["nuisance", "annoyance"], ["oblivious", "unaware"], ["obscure", "little known"], ["obsolete", "outdated"], ["obstacle", "barrier"],
    ["obstinate", "stubborn"], ["offset", "counterbalance"], ["ominous", "threatening"], ["omit", "leave out"], ["ongoing", "continuing"],
    ["opaque", "not transparent"], ["oppress", "treat harshly"], ["optimal", "best"], ["ordeal", "painful experience"], ["outrage", "anger"],
    ["outweigh", "be greater than"], ["overt", "open"], ["overwhelm", "overpower"], ["paradox", "seeming contradiction"], ["paramount", "supreme"],
    ["peculiar", "strange"], ["perceive", "notice"], ["perpetual", "continual"], ["persevere", "persist"], ["persistent", "unrelenting"],
    ["persuade", "convince"], ["pertinent", "relevant"], ["pessimistic", "expecting the worst"], ["petty", "small-minded"], ["pioneer", "trailblazer"],
    ["placid", "not easily upset"], ["plausible", "believable"], ["plight", "difficult situation"], ["ponder", "think over"], ["potent", "powerful"],
    ["pragmatic", "practical"], ["precarious", "unstable"], ["precede", "come before"], ["precise", "sharply defined"], ["predicament", "awkward situation"],
    ["predominant", "main"], ["preliminary", "introductory"], ["presume", "take for granted"], ["prevail", "win"], ["prevalent", "widespread"],
    ["proficient", "skilled"], ["profound", "deep"], ["prohibit", "ban"], ["proliferate", "increase rapidly"], ["prolong", "extend"],
    ["prominent", "well-known"], ["prompt", "quick"], ["propel", "drive forward"], ["prospect", "possibility"], ["prosper", "flourish"],
    ["provoke", "stir up"], ["proximity", "nearness"], ["prudent", "wise"], ["pursue", "chase"], ["quarrel", "argument"],
    ["radiant", "shining"], ["random", "by chance"], ["rational", "based on reason"], ["rebuke", "scold"], ["recede", "move back"],
    ["reckless", "careless"], ["reconcile", "restore friendship"], ["redundant", "unnecessary"], ["refrain", "hold back from"], ["refute", "prove wrong"],
    ["reinforce", "strengthen"], ["reiterate", "repeat"], ["relentless", "unceasing"], ["relevant", "related to the matter"], ["relinquish", "let go of"],
    ["reluctant", "unwilling"], ["remedy", "cure"], ["remote", "far away"], ["renounce", "formally give up"], ["replenish", "refill"],
    ["reprimand", "formal criticism"], ["resent", "feel bitter about"], ["resilient", "quick to recover"], ["resolve", "determination"], ["restrain", "hold back"],
    ["retain", "keep"], ["retaliate", "strike back"], ["retrieve", "get back"], ["revoke", "cancel"], ["rigid", "stiff"],
    ["robust", "strong"], ["rudimentary", "basic"], ["rural", "of the countryside"], ["sanction", "official approval"], ["scant", "barely sufficient"],
    ["scarce", "rare"], ["scatter", "spread out"], ["scrutinize", "examine closely"], ["serene", "peaceful"], ["severe", "very serious"],
    ["shrewd", "clever"], ["shun", "avoid deliberately"], ["significant", "important"], ["simultaneous", "at the same time"], ["skeptical", "questioning"],
    ["sole", "only"], ["solitary", "alone"], ["sophisticated", "advanced"], ["sparse", "thinly scattered"], ["spontaneous", "unplanned"],
    ["sporadic", "occasional"], ["stagnant", "not moving"], ["steadfast", "loyal"], ["stern", "strict"], ["stimulate", "encourage"],
    ["strenuous", "requiring great effort"], ["stringent", "strict and precise"], ["subdue", "bring under control"], ["subsequent", "following"], ["substantial", "large in amount"],
    ["subtle", "delicate"], ["succinct", "brief and clear"], ["suffice", "be enough"], ["superficial", "shallow"], ["supplement", "add to"],
    ["suppress", "put down"], ["surmount", "overcome"], ["surpass", "outdo"], ["surplus", "excess"], ["susceptible", "vulnerable"],
    ["sustain", "maintain"], ["swift", "fast"], ["tangible", "touchable"], ["tedious", "boring"], ["tenacious", "determined"],
    ["tentative", "provisional"], ["tenuous", "weak or slight"], ["terminate", "end"], ["thrifty", "economical"], ["thrive", "grow well"],
    ["thwart", "foil"], ["tolerate", "allow"], ["toxic", "poisonous"], ["trait", "characteristic"], ["tranquil", "calm"],
    ["transient", "temporary"], ["transparent", "see-through"], ["trigger", "set off"], ["trivial", "unimportant"], ["turbulent", "unsettled"],
    ["ubiquitous", "found everywhere"], ["unanimous", "in complete agreement"], ["uncanny", "strangely familiar"], ["undergo", "experience"], ["undermine", "weaken"],
    ["unprecedented", "never done before"], ["uphold", "maintain a principle"], ["urban", "of the city"], ["urgent", "pressing"], ["utilize", "use"],
    ["vacant", "empty"], ["vague", "not clearly expressed"], ["valid", "sound"], ["vanish", "disappear"], ["vast", "immense"],
    ["vehement", "forceful"], ["venture", "risky undertaking"], ["verbose", "wordy"], ["verify", "confirm"], ["versatile", "adaptable"],
    ["vex", "annoy"], ["viable", "workable"], ["vigorous", "energetic"], ["vindicate", "clear of blame"], ["vivid", "bright"],
    ["volatile", "liable to change rapidly"], ["vulnerable", "exposed to harm"], ["wane", "grow weaker"], ["wary", "watchful"], ["weary", "tired"],
    ["whim", "sudden impulse"], ["wholesome", "healthy"], ["wither", "dry up"], ["withstand", "resist"], ["yield", "produce"],
    ["zealous", "passionate"],
  ];

  const api = { ENG_GAP, ENG_VOCAB };
  if (typeof module !== "undefined" && module.exports) module.exports = api;
  else Object.assign(root, { HP_ENG_GAP: ENG_GAP, HP_ENG_VOCAB: ENG_VOCAB });
})(this);
