// Meningskomplettering (MEK) i högskoleprovets stil. Egna övningsmeningar, inte provfrågor.
// Varje fråga: [text med ___ för varje lucka, alternativ (rätt svar först), svårighet 1–3].
// Ett alternativ är en lista med ett ord per lucka. Ordningen blandas när frågan visas.
(function (root) {
  const MEK = [
    // ---- Nivå 1: en lucka, tydliga ledtrådar i meningen ----
    ["Efter flera veckors förhandlingar kunde parterna till slut enas om en ___ som alla kunde acceptera.", [["kompromiss"], ["konflikt"], ["provokation"], ["fördom"]], 1],
    ["Hon var känd för att vara mycket ___ och kom aldrig för sent till ett möte.", [["punktlig"], ["slarvig"], ["frånvarande"], ["vankelmodig"]], 1],
    ["Forskarna menade att resultaten var för ___ för att man skulle kunna dra några säkra slutsatser.", [["tvetydiga"], ["entydiga"], ["övertygande"], ["fullständiga"]], 1],
    ["Trots det ___ vädret genomfördes utomhuskonserten som planerat.", [["dåliga"], ["strålande"], ["ljuvliga"], ["stabila"]], 1],
    ["Den nya lagen fick ___ konsekvenser för småföretagen, som plötsligt fick betydligt högre kostnader.", [["kännbara"], ["obetydliga"], ["positiva"], ["marginella"]], 1],
    ["Politikern försökte ___ frågan genom att i stället tala om ett helt annat ämne.", [["undvika"], ["besvara"], ["förtydliga"], ["fördjupa"]], 1],
    ["Eftersom boken var skriven på ett ___ språk kunde även unga läsare ta till sig den.", [["lättillgängligt"], ["snårigt"], ["ålderdomligt"], ["invecklat"]], 1],
    ["Utställningen blev en stor ___ och lockade dubbelt så många besökare som väntat.", [["framgång"], ["besvikelse"], ["förlust"], ["motgång"]], 1],
    ["Han var så ___ att han aldrig kunde bestämma sig för vad han skulle beställa.", [["obeslutsam"], ["bestämd"], ["resolut"], ["målmedveten"]], 1],
    ["Läkaren betonade att behandlingen var ___ och att patienten därför inte behövde oroa sig.", [["ofarlig"], ["riskabel"], ["plågsam"], ["experimentell"]], 1],
    ["Kommunen beslutade att ___ den gamla skolan i stället för att riva den.", [["renovera"], ["stänga"], ["sälja"], ["överge"]], 1],
    ["Hennes skarpa ___ för detaljer gjorde henne till en utmärkt korrekturläsare.", [["öga"], ["ovilja"], ["likgiltighet"], ["avsmak"]], 1],
    ["Tidningen tvingades publicera en ___ efter att ha spridit felaktiga uppgifter.", [["rättelse"], ["recension"], ["annons"], ["krönika"]], 1],
    ["Det var ___ att se hur snabbt barnen lärde sig det nya språket, och lärarna var mycket stolta.", [["imponerande"], ["sorgligt"], ["oroande"], ["pinsamt"]], 1],
    ["Företaget gick med stor vinst, så styrelsen valde att ___ verksamheten till fler länder.", [["utvidga"], ["avveckla"], ["begränsa"], ["koncentrera"]], 1],
    ["Den gamla bron ansågs vara ___ och stängdes därför av för trafik.", [["instabil"], ["nybyggd"], ["robust"], ["vacker"]], 1],
    ["Hans ___ kommentarer gjorde att många på mötet kände sig kränkta.", [["nedsättande"], ["uppmuntrande"], ["sakliga"], ["vänliga"]], 1],
    ["Vittnenas berättelser var så ___ att polisen inte visste vem de skulle tro.", [["motstridiga"], ["samstämmiga"], ["detaljerade"], ["tydliga"]], 1],
    ["För att få pengarna att räcka levde studenten mycket ___ under hela terminen.", [["sparsamt"], ["slösaktigt"], ["lyxigt"], ["bekymmerslöst"]], 1],
    ["Hon fick stort ___ för sitt arbete och tilldelades årets pris.", [["erkännande"], ["missnöje"], ["straff"], ["avståndstagande"]], 1],
    ["Klimatförändringarna är ett ___ problem som kräver samarbete mellan alla länder.", [["globalt"], ["lokalt"], ["obetydligt"], ["tillfälligt"]], 1],
    ["Efter den långa vandringen var de så ___ att de somnade direkt.", [["utmattade"], ["pigga"], ["uttråkade"], ["nervösa"]], 1],
    ["Museet har en ___ samling av medeltida konst, en av de största i landet.", [["omfattande"], ["blygsam"], ["bristfällig"], ["ofullständig"]], 1],
    ["Grannarnas ständiga ___ om parkeringsplatserna gjorde stämningen i huset dålig.", [["gräl"], ["samförstånd"], ["fester"], ["skämt"]], 1],
    ["Uppsatsen var välskriven men saknade en tydlig ___, vilket gjorde den svår att följa.", [["struktur"], ["längd"], ["stavning"], ["tidsgräns"]], 1],
    ["Utan regn på flera månader blev marken helt ___.", [["förtorkad"], ["blöt"], ["bördig"], ["översvämmad"]], 1],
    ["Direktören fattade ett ___ beslut utan att först rådfråga sina medarbetare.", [["egenmäktigt"], ["gemensamt"], ["demokratiskt"], ["förankrat"]], 1],
    ["De båda syskonen var så ___ att många trodde att de var tvillingar.", [["lika"], ["olika"], ["osams"], ["främmande"]], 1],
    ["Eftersom kursen var ___ var alla studenter tvungna att delta.", [["obligatorisk"], ["frivillig"], ["valbar"], ["inställd"]], 1],
    ["Författaren använder ofta ___ för att beskriva naturen, till exempel när hon kallar skogen för en katedral.", [["metaforer"], ["siffror"], ["citat"], ["fotnoter"]], 1],
    ["Efter att ha fått sparken var han mycket ___ och ville inte prata med någon.", [["nedslagen"], ["uppspelt"], ["belåten"], ["sorglös"]], 1],
    ["Den erfarna guiden kunde ___ alla fåglar i skogen enbart på deras läten.", [["identifiera"], ["skrämma"], ["mata"], ["ignorera"]], 1],
    ["Eftersom bilen var så ___ i drift valde familjen att behålla den i många år.", [["billig"], ["dyr"], ["krånglig"], ["osäker"]], 1],
    ["Tävlingen var ___ in i det sista, och vinnaren avgjordes först på sista sekunden.", [["jämn"], ["avgjord"], ["ojämn"], ["förutsägbar"]], 1],

    // ---- Nivå 2: svårare ord eller två luckor ----
    ["Ministerns uttalande var så ___ att både anhängare och kritiker tolkade det som stöd för sin egen linje.", [["tvetydigt"], ["entydigt"], ["kategoriskt"], ["explicit"]], 2],
    ["Trots sin ___ framtoning var han i själva verket mycket osäker.", [["självsäkra"], ["blyga"], ["ängsliga"], ["försynta"]], 2],
    ["Utredningen visade att olyckan inte hade en enda ___ utan berodde på en rad samverkande faktorer.", [["orsak"], ["följd"], ["lösning"], ["vittne"]], 2],
    ["Den ___ debattören lyckades alltid få publiken på sin sida, oavsett ämne.", [["vältalige"], ["fåordige"], ["blyge"], ["osäkre"]], 2],
    ["Kritikerna menade att filmens handling var ___ och att man redan efter tio minuter kunde gissa slutet.", [["förutsägbar"], ["oväntad"], ["invecklad"], ["originell"]], 2],
    ["Hans ___ inställning till regler gjorde honom populär bland eleverna men mindre omtyckt av rektorn.", [["nonchalanta"], ["strikta"], ["noggranna"], ["pedantiska"]], 2],
    ["Forskaren var ___ till de nya rönen och krävde fler studier innan hon ville uttala sig.", [["skeptisk"], ["entusiastisk"], ["positiv"], ["likgiltig"]], 2],
    ["Det är ___ att tro att problemet löser sig av sig självt; det krävs aktiva åtgärder.", [["naivt"], ["klokt"], ["realistiskt"], ["nödvändigt"]], 2],
    ["Förhandlingarna ___ och parterna lämnade mötet utan att ha nått någon överenskommelse.", [["strandade"], ["lyckades"], ["fullbordades"], ["förlängdes"]], 2],
    ["Romanen skildrar med stor ___ hur det var att växa upp i en fattig arbetarfamilj på 1930-talet.", [["inlevelse"], ["likgiltighet"], ["ironi"], ["hast"]], 2],
    ["Beslutet att lägga ner vårdcentralen möttes av ___ protester från ortens invånare.", [["högljudda"], ["försiktiga"], ["obefintliga"], ["uppskattande"]], 2],
    ["Han hade ett ___ minne och kunde återge långa samtal ord för ord.", [["fenomenalt"], ["bristfälligt"], ["selektivt"], ["diffust"]], 2],
    ["Diskussionen blev alltmer ___ och till slut var det ingen som lyssnade på någon annan.", [["upphetsad"], ["saklig"], ["stillsam"], ["konstruktiv"]], 2],
    ["Enligt kritikern var pjäsen ett ___ försök att kopiera en klassiker, helt utan egna idéer.", [["fantasilöst"], ["nyskapande"], ["djärvt"], ["lyckat"]], 2],
    ["Den tidigare så ___ stadsdelen har på senare år blivit ett populärt område med kaféer och gallerier.", [["nedgångna"], ["eftertraktade"], ["exklusiva"], ["välskötta"]], 2],
    ["Eftersom budgeten var ___ fick projektgruppen prioritera hårt bland sina idéer.", [["snäv"], ["generös"], ["obegränsad"], ["riklig"]], 2],
    ["Efter en lång och ___ debatt valde regeringen till slut att ___ det omstridda förslaget.", [["infekterad", "dra tillbaka"], ["enig", "dra tillbaka"], ["kortfattad", "förbjuda"], ["ointressant", "hylla"]], 2],
    ["Författarens tidiga verk präglades av ___, medan de senare böckerna är betydligt mer ___ och ljusa.", [["svårmod", "hoppfulla"], ["glädje", "dystra"], ["optimism", "pessimistiska"], ["humor", "allvarsamma"]], 2],
    ["Att lära sig ett nytt språk kräver ___; det går inte att bli flytande på några veckor.", [["tålamod"], ["tur"], ["pengar"], ["intuition"]], 2],
    ["Hennes förklaring var så ___ att alla i rummet genast förstod hur maskinen fungerade.", [["pedagogisk"], ["kryptisk"], ["omständlig"], ["vag"]], 2],
    ["Trots att bevisen var ___ valde åklagaren att väcka åtal.", [["bristfälliga"], ["överväldigande"], ["tydliga"], ["fällande"]], 2],
    ["Företaget har länge haft ___ på marknaden, men nu har flera konkurrenter dykt upp.", [["monopol"], ["underskott"], ["förluster"], ["svårigheter"]], 2],
    ["Den ___ professorn var känd för att glömma både möten och paraply.", [["tankspridde"], ["punktlige"], ["noggranne"], ["vaksamme"]], 2],
    ["Arkitekten ville att byggnaden skulle ___ med den omgivande naturen i stället för att dominera den.", [["harmoniera"], ["konkurrera"], ["kontrastera"], ["kollidera"]], 2],
    ["Rapporten innehöll så många ___ att den fick skrivas om från början.", [["felaktigheter"], ["förtjänster"], ["illustrationer"], ["slutsatser"]], 2],
    ["Hans ___ försök att imponera på de andra fick motsatt effekt.", [["krystade"], ["naturliga"], ["lyckade"], ["diskreta"]], 2],
    ["Löftena om lägre skatter visade sig vara ___; efter valet höjdes skatten i stället.", [["tomma"], ["uppfyllda"], ["realistiska"], ["blygsamma"]], 2],
    ["Det gamla manuskriptet var så ___ att experterna behövde flera år för att tolka det.", [["svårtytt"], ["välbevarat"], ["kortfattat"], ["lättläst"]], 2],
    ["Hon tog ___ från kollegornas åsikter och fortsatte arbeta på sitt eget sätt.", [["avstånd"], ["intryck"], ["del"], ["ansvar"]], 2],
    ["Ekonomin befann sig i en djup ___ med hög arbetslöshet och sjunkande löner.", [["lågkonjunktur"], ["högkonjunktur"], ["tillväxtfas"], ["blomstring"]], 2],
    ["Med sin ___ humor lyckades han få även de mest allvarsamma mötena att bli trivsamma.", [["avväpnande"], ["sarkastiska"], ["grova"], ["obefintliga"]], 2],
    ["Resultatet av undersökningen var ___: en klar majoritet av de tillfrågade var nöjda.", [["entydigt"], ["ofullständigt"], ["motsägelsefullt"], ["svårtolkat"]], 2],
    ["Den nya chefen var ___ i sina beslut men alltid ___ mot sina medarbetare.", [["bestämd", "lyhörd"], ["ängslig", "kylig"], ["rådvill", "nonchalant"], ["nyckfull", "hånfull"]], 2],
    ["Fyndet var ___ för forskarna, eftersom det ___ flera av de rådande teorierna om stenåldern.", [["sensationellt", "kullkastade"], ["ointressant", "bekräftade"], ["väntat", "styrkte"], ["obetydligt", "ändrade"]], 2],
    ["Trots sin ___ ålder var konstnären fortfarande lika ___ som i ungdomen.", [["höga", "produktiv"], ["unga", "trött"], ["låga", "erfaren"], ["höga", "passiv"]], 2],

    // ---- Nivå 3: formellt språk, två eller tre luckor ----
    ["Forskningsfältet har länge dominerats av ___ teorier, men på senare tid har en mer ___ syn vunnit mark.", [["deterministiska", "nyanserad"], ["nyanserade", "förenklad"], ["flexibla", "dogmatisk"], ["moderna", "samtida"]], 3],
    ["Även om hans argument var ___ och logiskt uppbyggda, lyckades han inte ___ åhörarna.", [["stringenta", "övertyga"], ["slarviga", "engagera"], ["svaga", "tråka ut"], ["ologiska", "förvirra"]], 3],
    ["Det är ___ att en så liten ändring i lagtexten kan få så ___ konsekvenser.", [["anmärkningsvärt", "långtgående"], ["självklart", "obetydliga"], ["naturligt", "marginella"], ["förväntat", "begränsade"]], 3],
    ["Kritikern ___ romanen som ett mästerverk, medan andra recensenter var betydligt mer ___.", [["hyllade", "avvaktande"], ["sågade", "entusiastiska"], ["ignorerade", "positiva"], ["kritiserade", "negativa"]], 3],
    ["Förslaget var ___ i teorin men visade sig vara ___ att genomföra i praktiken.", [["tilltalande", "omöjligt"], ["orealistiskt", "enkelt"], ["bristfälligt", "lätt"], ["lysande", "självklart"]], 3],
    ["Hennes ___ för ämnet var så stor att hon ägnade hela sitt ___ åt forskning om det.", [["passion", "yrkesliv"], ["ovilja", "liv"], ["likgiltighet", "kapital"], ["okunskap", "fritid"]], 3],
    ["Den ___ tonen i debatten gjorde det svårt att föra ett ___ samtal om sakfrågorna.", [["polariserade", "konstruktivt"], ["sansade", "upphetsat"], ["vänliga", "aggressivt"], ["lugna", "meningsfullt"]], 3],
    ["Trots att hon ___ mycket över sina misstag, var hon aldrig rädd att ___ nya utmaningar.", [["grubblade", "anta"], ["skröt", "undvika"], ["skämtade", "vägra"], ["glömde", "fly"]], 3],
    ["Utan tillräckliga ___ kan forskaren inte dra några ___ slutsatser.", [["belägg", "säkra"], ["pengar", "tveksamma"], ["idéer", "felaktiga"], ["kollegor", "tråkiga"]], 3],
    ["Studien är ___ eftersom den bygger på ett alltför ___ urval av deltagare.", [["missvisande", "begränsat"], ["tillförlitlig", "litet"], ["representativ", "snävt"], ["banbrytande", "ensidigt"]], 3],
    ["Den till synes ___ uppgiften visade sig vara betydligt mer ___ än någon hade anat.", [["enkla", "komplicerad"], ["svåra", "invecklad"], ["omöjliga", "ogenomförbar"], ["tråkiga", "enformig"]], 3],
    ["Han ___ sitt ansvar genom att skylla på sina kollegor, vilket väckte stor ___ inom företaget.", [["försökte undandra sig", "harm"], ["tog", "beundran"], ["axlade", "irritation"], ["förnekade", "glädje"]], 3],
    ["Med tiden blev skillnaderna mellan de två dialekterna allt mer ___, tills de nästan var ___.", [["utsuddade", "identiska"], ["markanta", "identiska"], ["tydliga", "likadana"], ["obetydliga", "oförenliga"]], 3],
    ["Den ___ utredningen lämnade inga frågor obesvarade och fick beröm för sin ___.", [["grundliga", "noggrannhet"], ["summariska", "kortfattadhet"], ["slarviga", "ärlighet"], ["ofullständiga", "grundlighet"]], 3],
    ["Eftersom vittnets uppgifter ___ med de tekniska bevisen, valde domstolen att ___ dem.", [["stämde överens", "godta"], ["stred mot", "godta"], ["stämde överens", "avfärda"], ["sammanföll", "ifrågasätta"]], 3],
    ["Hennes tal var ___ men ___: på bara fem minuter lyckades hon säga allt väsentligt.", [["kort", "innehållsrikt"], ["långt", "tomt"], ["kort", "intetsägande"], ["utdraget", "koncist"]], 3],
    ["Den ___ fredsprocessen hotades när en av parterna plötsligt ___ avtalet.", [["sköra", "bröt"], ["stabila", "bekräftade"], ["robusta", "undertecknade"], ["nya", "förlängde"]], 3],
    ["Att kalla förslaget ___ vore en överdrift; det är snarare ett ___ steg i rätt riktning.", [["revolutionerande", "försiktigt"], ["misslyckat", "stort"], ["meningslöst", "gigantiskt"], ["radikalt", "drastiskt"]], 3],
    ["Hans ___ intresse för historia gjorde honom till en ___ källa för alla som skrev om trakten.", [["djupa", "ovärderlig"], ["ytliga", "betydelsefull"], ["flyktiga", "pålitlig"], ["obefintliga", "ovärderlig"]], 3],
    ["Trots ___ protester från allmänheten beslutade kommunen att ___ parken för att bygga bostäder.", [["omfattande", "exploatera"], ["obefintliga", "bevara"], ["svaga", "utvidga"], ["ljumma", "skydda"]], 3],
    ["Konstnärens verk är ___: de kan tolkas på många olika sätt och låter sig inte ___ till en enda sanning.", [["mångtydiga", "reduceras"], ["entydiga", "begränsas"], ["banala", "ledas"], ["tydliga", "föras"]], 3],
    ["Den tidigare så ___ ledaren blev med åren alltmer ___ och vägrade lyssna på kritik.", [["lyhörda", "egenmäktig"], ["envisa", "öppen"], ["auktoritära", "ödmjuk"], ["ödmjuka", "prestigelös"]], 3],
    ["Rapporten ___ de risker som projektet medför och ___ därför att det skjuts upp.", [["belyser", "rekommenderar"], ["bagatelliserar", "rekommenderar"], ["ignorerar", "kräver"], ["förnekar", "föreslår"]], 3],
    ["Det ___ klimatet på arbetsplatsen gjorde att många anställda kände sig ___ och sa upp sig.", [["hårda", "utbrända"], ["vänliga", "uppskattade"], ["avslappnade", "utbrända"], ["kollegiala", "sedda"]], 3],
    ["Kritiken mot boken var ___: ingen av recensenterna hade något ___ att säga om den.", [["samstämmig", "positivt"], ["splittrad", "negativt"], ["mild", "elakt"], ["blandad", "gott"]], 3],
    ["Hans ___ sätt att uttrycka sig gjorde att även ___ ämnen blev begripliga för en bred publik.", [["klara", "komplexa"], ["dunkla", "enkla"], ["kryptiska", "vardagliga"], ["omständliga", "triviala"]], 3],
    ["Reformen var tänkt att ___ byråkratin, men i praktiken ledde den till ännu fler ___.", [["minska", "blanketter"], ["öka", "förenklingar"], ["avskaffa", "lättnader"], ["bevara", "nedskärningar"]], 3],
    ["Det var ___ att se hur den en gång så ___ fabriken nu stod tom och förfallen.", [["vemodigt", "livliga"], ["glädjande", "övergivna"], ["lugnande", "tysta"], ["roande", "nedlagda"]], 3],
    ["Författaren har ett ___ öga för detaljer, vilket gör hennes miljöskildringar ovanligt ___.", [["skarpt", "levande"], ["slött", "färgstarka"], ["ointresserat", "precisa"], ["skarpt", "blodfattiga"]], 3],
    ["Den ___ tillväxten under decenniet ___ av en plötslig finanskris.", [["stadiga", "avbröts"], ["svaga", "förstärktes"], ["obefintliga", "följdes"], ["snabba", "förutsågs"]], 3],
    ["Att ___ problemen är inte detsamma som att lösa dem; de finns kvar oavsett hur mycket man ___ dem.", [["förneka", "blundar för"], ["analysera", "studerar"], ["lösa", "arbetar med"], ["erkänna", "diskuterar"]], 3],
    // ---- Fler övningar ----
    ["Efter olyckan inleddes en grundlig ___ för att ta reda på vad som hade gått fel.",[["utredning"], ["festlighet"], ["belöning"], ["avslappning"]],1],
    ["Eftersom hon var så ___ vågade hon aldrig säga något på lektionerna.",[["blyg"], ["frispråkig"], ["självsäker"], ["högljudd"]],1],
    ["Företaget gick med stor ___ förra året och tvingades därför säga upp personal.",[["förlust"], ["vinst"], ["framgång"], ["expansion"]],1],
    ["Läkaren kunde snabbt ställa rätt ___ tack vare de tydliga symtomen.",[["diagnos"], ["prognos"], ["hypotes"], ["premiss"]],1],
    ["Den gamla bron var så ___ att den fick stängas för all trafik.",[["fallfärdig"], ["nyrenoverad"], ["robust"], ["hållbar"]],1],
    ["Utställningen blev en stor ___ och drog fler besökare än någon väntat sig.",[["succé"], ["besvikelse"], ["kris"], ["flopp"]],1],
    ["Han var ___ inför resultatet och vågade knappt öppna kuvertet.",[["nervös"], ["likgiltig"], ["säker"], ["uttråkad"]],1],
    ["Myndigheten gav ___ till bygget först efter flera års prövning.",[["tillstånd"], ["avslag"], ["förbud"], ["kritik"]],1],
    ["För att spara tid valde de den ___ vägen genom skogen.",[["genaste"], ["längsta"], ["krokigaste"], ["mödosammaste"]],1],
    ["Det är viktigt att ___ källor när man skriver en vetenskaplig uppsats.",[["ange"], ["dölja"], ["förfalska"], ["glömma"]],1],
    ["Den ___ debattören lyckades övertyga även sina hårdaste kritiker.",[["vältalige"], ["osäkre"], ["tystlåtne"], ["förvirrade"]],1],
    ["Priserna har ___ kraftigt det senaste året, och många hushåll har fått det svårare.",[["stigit"], ["sjunkit"], ["stabiliserats"], ["halverats"]],1],
    ["Hon fick ett ___ för sitt arbete med att förbättra vården för äldre.",[["pris"], ["straff"], ["avslag"], ["varning"]],1],
    ["Eleverna var ___ efter den långa vandringen och somnade direkt.",[["utmattade"], ["utvilade"], ["pigga"], ["rastlösa"]],1],
    ["Tidningen tvingades ___ artikeln eftersom den innehöll flera faktafel.",[["dementera"], ["publicera"], ["prisa"], ["citera"]],1],
    ["Fabriken släppte ut stora mängder ___ i sjön, vilket skadade fisket.",[["föroreningar"], ["näringsämnen"], ["syre"], ["sötvatten"]],1],
    ["Hans ___ inställning gjorde att han alltid såg möjligheter i stället för problem.",[["positiva"], ["negativa"], ["kritiska"], ["pessimistiska"]],1],
    ["Beslutet var ___ och kunde inte överklagas.",[["slutgiltigt"], ["preliminärt"], ["tillfälligt"], ["osäkert"]],1],
    ["Under krisen blev det ___ på mat i flera delar av landet.",[["brist"], ["överflöd"], ["överskott"], ["fest"]],1],
    ["Konstnären hämtade ___ från naturen till nästan alla sina målningar.",[["inspiration"], ["pengar"], ["kritik"], ["tillstånd"]],1],
    ["Hon var mycket ___ och delade gärna med sig av det hon hade.",[["generös"], ["snål"], ["girig"], ["självisk"]],1],
    ["Rapporten var så ___ att ingen orkade läsa den till slut.",[["omfattande"], ["kortfattad"], ["koncis"], ["lättläst"]],1],
    ["Mötet blev ___ eftersom flera av deltagarna var sjuka.",[["inställt"], ["förlängt"], ["tidigarelagt"], ["överfullt"]],1],
    ["Han hade en ___ för att berätta roliga historier, och alla ville sitta bredvid honom.",[["talang"], ["motvilja"], ["rädsla"], ["ovana"]],1],
    ["Den nya medicinen ska ___ smärtan men botar inte sjukdomen.",[["lindra"], ["förvärra"], ["orsaka"], ["förlänga"]],1],
    ["Staden är känd för sin ___ arkitektur från 1600-talet.",[["välbevarade"], ["förstörda"], ["moderna"], ["obefintliga"]],1],
    ["Efter en lång ___ kom de fram till att förslaget borde godkännas.",[["överläggning"], ["paus"], ["semester"], ["tystnad"]],1],
    ["Trafiken var så ___ att de missade flyget.",[["tät"], ["gles"], ["lugn"], ["obefintlig"]],1],
    ["Hans svar var så ___ att ingen förstod vad han egentligen menade.",[["svävande"], ["tydligt"], ["rakt"], ["kortfattat"]],1],
    ["Det krävs stor ___ för att lära sig ett nytt språk som vuxen.",[["uthållighet"], ["slump"], ["tur"], ["lättja"]],1],
    ["Forskarna gjorde en viktig ___ som kan leda till nya behandlingar.",[["upptäckt"], ["förlust"], ["felräkning"], ["gissning"]],1],
    ["Barnen blev ___ när de fick höra att skolan skulle vara stängd en hel vecka, och de började genast planera allt roligt de skulle hitta på.",[["förtjusta"], ["bedrövade"], ["oroliga"], ["besvikna"]],1],
    ["Politikerna var ___ om att något måste göras, men inte om vad.",[["överens"], ["oense"], ["okunniga"], ["osäkra"]],1],
    ["Kommunen beslutade att ___ biblioteket, trots stora protester.",[["lägga ned"], ["bygga ut"], ["renovera"], ["utvidga"]],1],
    ["Hon talade ett ___ språk som gjorde föreläsningen lätt att följa.",[["klart"], ["dunkelt"], ["kryptiskt"], ["förvirrat"]],1],
    ["Den ___ kritiken mot förslaget fick regeringen att dra tillbaka det redan efter en vecka.",[["massiva"], ["försiktiga"], ["obefintliga"], ["positiva"]],2],
    ["Forskningen har länge varit ___ till storstäderna, medan landsbygden har fått betydligt mindre uppmärksamhet.",[["koncentrerad"], ["främmande"], ["likgiltig"], ["fientlig"]],2],
    ["Hans ___ beteende på mötet gjorde att ingen längre tog honom på allvar.",[["oförutsägbara"], ["konsekventa"], ["behärskade"], ["genomtänkta"]],2],
    ["Trots att experimentet upprepades flera gånger kunde resultaten inte ___.",[["reproduceras"], ["publiceras"], ["ifrågasättas"], ["förbises"]],2],
    ["Romanen skildrar ___ den fattigdom som präglade landet under 1800-talet.",[["ingående"], ["ytligt"], ["motvilligt"], ["sällan"]],2],
    ["Förslaget ___ både av oppositionen och av flera tunga namn inom regeringspartiet.",[["kritiserades"], ["hyllades"], ["ignorerades"], ["efterfrågades"]],2],
    ["I stället för att ___ problemen valde ledningen att tysta ner dem.",[["åtgärda"], ["förvärra"], ["dölja"], ["förneka"]],2],
    ["Klimatförändringarna utgör ett ___ hot mot många arter som redan är sällsynta.",[["påtagligt"], ["inbillat"], ["avlägset"], ["överdrivet"]],2],
    ["Den ___ tonen i brevet gjorde mottagaren både sårad och förvånad.",[["avmätta"], ["hjärtliga"], ["uppsluppna"], ["vänliga"]],2],
    ["Trots sin ___ ålder var hon en av de mest erfarna i laget.",[["unga"], ["höga"], ["mogna"], ["aktningsvärda"]],2],
    ["Den tidigare ___ stadsdelen har på senare år blivit ett av stadens mest eftertraktade områden.",[["försummade"], ["exklusiva"], ["populära"], ["välbärgade"]],2],
    ["Debatten blev alltmer ___, och till slut fick moderatorn avbryta den.",[["hätsk"], ["saklig"], ["stillsam"], ["konstruktiv"]],2],
    ["Den nya tekniken har ___ sättet vi kommunicerar på i grunden.",[["förändrat"], ["bevarat"], ["bekräftat"], ["försvårat"]],2],
    ["Det är ___ att dra slutsatser om hela befolkningen utifrån en så liten undersökning.",[["vanskligt"], ["självklart"], ["nödvändigt"], ["enkelt"]],2],
    ["Hon var ___ i sin kritik: ingen detalj undgick hennes granskning.",[["minutiös"], ["slarvig"], ["överseende"], ["ytlig"]],2],
    ["Hans teorier möttes först av ___, men i dag betraktas de som självklara.",[["skepsis"], ["entusiasm"], ["beundran"], ["likgiltighet"]],2],
    ["Avtalet var ___ och kunde därför tolkas på flera olika sätt.",[["tvetydigt"], ["entydigt"], ["kortfattat"], ["bindande"]],2],
    ["Den ___ utvecklingen på bostadsmarknaden har gjort det svårt för unga att hitta en egen bostad.",[["oroande"], ["gynnsamma"], ["lovande"], ["förväntade"]],2],
    ["Hans ___ att acceptera kompromisser gjorde förhandlingarna mycket utdragna.",[["ovilja"], ["förmåga"], ["iver"], ["benägenhet"]],2],
    ["Museets samlingar är ___ och spänner över flera tusen år av historia.",[["omfångsrika"], ["begränsade"], ["torftiga"], ["ensidiga"]],2],
    ["Som ___ för sina insatser fick hon en ledande roll i det nya projektet.",[["erkännande"], ["straff"], ["förebråelse"], ["tröst"]],2],
    ["Utredningen visade att olyckan berodde på ___ och inte på tekniska fel.",[["slarv"], ["noggrannhet"], ["omsorg"], ["försiktighet"]],2],
    ["Kritikerna menar att reformen är ___ och inte kommer att lösa de verkliga problemen.",[["kosmetisk"], ["genomgripande"], ["radikal"], ["djupgående"]],2],
    ["Han har en ___ förmåga att få människor att känna sig sedda.",[["enastående"], ["bristfällig"], ["obefintlig"], ["måttlig"]],2],
    ["Det ___ vädret gjorde det omöjligt att planera utflykten i förväg.",[["ombytliga"], ["stabila"], ["förutsägbara"], ["behagliga"]],2],
    ["Resultatet var ___: ingen hade räknat med att det lilla partiet skulle bli störst.",[["sensationellt"], ["väntat"], ["förutsägbart"], ["alldagligt"]],2],
    ["Rektorn ville ___ tydligt att mobbning inte under några omständigheter accepteras.",[["markera"], ["antyda"], ["förtiga"], ["ifrågasätta"]],2],
    ["Planerna var ___, men det saknades både pengar och personal för att genomföra dem.",[["ambitiösa"], ["blygsamma"], ["realistiska"], ["obetydliga"]],2],
    ["Den gamla traditionen har ___ i generationer och lever fortfarande kvar i byn.",[["bevarats"], ["glömts"], ["förbjudits"], ["försvunnit"]],2],
    ["Hennes ___ om vad som skulle hända visade sig stämma till punkt och pricka.",[["farhågor"], ["glädjeämnen"], ["minnen"], ["önskningar"]],2],
    ["Med ___ röster antogs förslaget: bara en ledamot röstade emot.",[["överväldigande"], ["knappa"], ["delade"], ["osäkra"]],2],
    ["Bristen på ___ gjorde att många kände sig överkörda av beslutet.",[["förankring"], ["motstånd"], ["pengar"], ["tid"]],2],
    ["Det ___ intresset för boken överraskade både författaren och förlaget.",[["stora"], ["ringa"], ["svala"], ["obefintliga"]],2],
    ["Hon ___ sina argument så skickligt att motståndarna inte hade något att sätta emot.",[["underbyggde"], ["försvagade"], ["övergav"], ["förvanskade"]],2],
    ["Snarare än att ___ konflikten bidrog medlarens uttalanden till att ___ den.",[["dämpa", "förvärra"], ["förvärra", "lösa"], ["starta", "avsluta"], ["ignorera", "förstå"]],3],
    ["Det som till en början betraktades som en ___ modefluga har visat sig vara en ___ förändring av konsumtionsmönstren.",[["flyktig", "bestående"], ["bestående", "tillfällig"], ["viktig", "ytlig"], ["varaktig", "kortvarig"]],3],
    ["Författaren ___ inte att beskriva krigets fasor; tvärtom skildras de med en nästan ___ detaljrikedom.",[["drar sig", "plågsam"], ["vågar", "överdriven"], ["hinner", "bristfällig"], ["orkar", "ytlig"]],3],
    ["Eftersom tidigare studier varit ___ gick det inte att dra några ___ slutsatser.",[["motsägelsefulla", "säkra"], ["samstämmiga", "tydliga"], ["omfattande", "vaga"], ["entydiga", "enkla"]],3],
    ["Hans ___ för detaljer var imponerande, men den gjorde honom också ___ när det gällde att fatta snabba beslut.",[["känsla", "handfallen"], ["ointresse", "effektiv"], ["motvilja", "snabb"], ["förakt", "beslutsam"]],3],
    ["Långt ifrån att vara ___ var hennes kritik både genomtänkt och ___.",[["godtycklig", "välgrundad"], ["välgrundad", "godtycklig"], ["saklig", "ogenomtänkt"], ["hård", "orättvis"]],3],
    ["Reformen var tänkt att ___ skillnaderna mellan regionerna, men i praktiken har den snarare ___ dem.",[["utjämna", "förstärkt"], ["förstärka", "minskat"], ["öka", "utplånat"], ["dölja", "avslöjat"]],3],
    ["Även om metoden är ___ ger den inte alltid ___ resultat.",[["beprövad", "tillförlitliga"], ["ny", "osäkra"], ["otestad", "felaktiga"], ["okänd", "dåliga"]],3],
    ["Hans ___ var så övertygande att få märkte hur ___ själva argumenten egentligen var.",[["retorik", "ihåliga"], ["tystnad", "starka"], ["tvekan", "solida"], ["ärlighet", "sanna"]],3],
    ["Det är ___ att fler inte har upptäckt bristerna, med tanke på hur ___ de är.",[["förvånande", "uppenbara"], ["självklart", "dolda"], ["naturligt", "uppenbara"], ["förvånande", "obetydliga"]],3],
    ["Den tidigare så ___ ministern blev efter skandalen alltmer ___ i sina uttalanden.",[["frispråkiga", "återhållsam"], ["tystlåtna", "tystlåten"], ["försiktiga", "försiktig"], ["reserverade", "tillbakadragen"]],3],
    ["För att ___ förtroendet måste företaget inte bara be om ursäkt utan också ___ hur det ska undvika liknande misstag.",[["återvinna", "redogöra för"], ["förlora", "dölja"], ["missbruka", "förklara"], ["skada", "förneka"]],3],
    ["Det som ___ skiljer de två teorierna åt är inte deras slutsatser utan deras ___.",[["egentligen", "utgångspunkter"], ["knappast", "resultat"], ["tydligt", "slutsatser"], ["sällan", "konsekvenser"]],3],
    ["Trots en ___ start växte företaget snabbt och blev inom några år ___ i branschen.",[["blygsam", "ledande"], ["lysande", "obetydligt"], ["kraftfull", "okänt"], ["storslagen", "bortglömt"]],3],
    ["Skribenten ___ mellan ironi och allvar på ett sätt som gör texten svår att ___ entydigt.",[["pendlar", "tolka"], ["väljer", "läsa"], ["skiljer", "förstå"], ["förväxlar", "kritisera"]],3],
    ["Beslutet framstod först som ___, men med tiden har det visat sig vara ___.",[["förhastat", "klokt"], ["klokt", "genomtänkt"], ["självklart", "rimligt"], ["genomtänkt", "förhastat"]],3],
    ["Hon var ___ mot kritik och tog den aldrig personligt, vilket gjorde henne ___ som ledare.",[["okänslig", "stabil"], ["överkänslig", "trygg"], ["allergisk", "säker"], ["likgiltig", "osäker"]],3],
    ["Eftersom materialet är så ___ måste man vara ___ när man drar generella slutsatser.",[["begränsat", "försiktig"], ["omfattande", "vårdslös"], ["stort", "slarvig"], ["tillförlitligt", "tveksam"]],3],
    ["De ___ försöken att stoppa spridningen misslyckades, delvis på grund av ___ samordning.",[["första", "bristande"], ["senare", "utmärkt"], ["lyckade", "god"], ["sista", "effektiv"]],3],
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = MEK;
  else root.HP_MEK = MEK;
})(this);
