// Meningskomplettering (MEK) i högskoleprovets stil. Egna övningsmeningar, inte provfrågor.
// Varje fråga: [text med ___ för varje lucka, alternativ (rätt svar först), svårighet 1–3].
// Ett alternativ är en lista med ett ord per lucka. Ordningen blandas när frågan visas.
(function (root) {
  const MEK = [
    // ---- Nivå 1: en lucka, tydliga ledtrådar i meningen ----
    ["Efter flera veckors förhandlingar kunde parterna till slut enas om en ___ som alla kunde acceptera.", [["kompromiss"], ["konflikt"], ["provokation"], ["fördom"]], 1],
    ["Hon var känd för att vara mycket ___ och kom aldrig för sent till ett möte.", [["punktlig"], ["slarvig"], ["frånvarande"], ["vankelmodig"]], 1],
    ["Forskarna menade att resultaten var för ___ för att man skulle kunna dra några säkra slutsatser.", [["tvetydiga"], ["entydiga"], ["övertygande"], ["fullständiga"]], 1],
    ["Trots det ___ vädret genomfördes utomhuskonserten som planerat.", [["dåliga"], ["strålande"], ["ljuvliga"], ["stabila"]], 1],
    ["Den nya lagen fick ___ konsekvenser för småföretagen, som plötsligt fick betydligt högre kostnader.", [["kännbara"], ["obetydliga"], ["positiva"], ["marginella"]], 1],
    ["Politikern försökte ___ frågan genom att i stället tala om ett helt annat ämne.", [["undvika"], ["besvara"], ["förtydliga"], ["fördjupa"]], 1],
    ["Eftersom boken var skriven på ett ___ språk kunde även unga läsare ta till sig den.", [["lättillgängligt"], ["snårigt"], ["ålderdomligt"], ["invecklat"]], 1],
    ["Utställningen blev en stor ___ och lockade dubbelt så många besökare som väntat.", [["framgång"], ["besvikelse"], ["förlust"], ["motgång"]], 1],
    ["Han var så ___ att han aldrig kunde bestämma sig för vad han skulle beställa.", [["obeslutsam"], ["bestämd"], ["resolut"], ["målmedveten"]], 1],
    ["Läkaren betonade att behandlingen var ___ och att patienten därför inte behövde oroa sig.", [["ofarlig"], ["riskabel"], ["plågsam"], ["experimentell"]], 1],
    ["Kommunen beslutade att ___ den gamla skolan i stället för att riva den.", [["renovera"], ["stänga"], ["sälja"], ["överge"]], 1],
    ["Hennes skarpa ___ för detaljer gjorde henne till en utmärkt korrekturläsare.", [["öga"], ["ovilja"], ["likgiltighet"], ["avsmak"]], 1],
    ["Tidningen tvingades publicera en ___ efter att ha spridit felaktiga uppgifter.", [["rättelse"], ["recension"], ["annons"], ["krönika"]], 1],
    ["Det var ___ att se hur snabbt barnen lärde sig det nya språket, och lärarna var mycket stolta.", [["imponerande"], ["sorgligt"], ["oroande"], ["pinsamt"]], 1],
    ["Företaget gick med stor vinst, så styrelsen valde att ___ verksamheten till fler länder.", [["utvidga"], ["avveckla"], ["begränsa"], ["koncentrera"]], 1],
    ["Den gamla bron ansågs vara ___ och stängdes därför av för trafik.", [["instabil"], ["nybyggd"], ["robust"], ["vacker"]], 1],
    ["Hans ___ kommentarer gjorde att många på mötet kände sig kränkta.", [["nedsättande"], ["uppmuntrande"], ["sakliga"], ["vänliga"]], 1],
    ["Vittnenas berättelser var så ___ att polisen inte visste vem de skulle tro.", [["motstridiga"], ["samstämmiga"], ["detaljerade"], ["tydliga"]], 1],
    ["För att få pengarna att räcka levde studenten mycket ___ under hela terminen.", [["sparsamt"], ["slösaktigt"], ["lyxigt"], ["bekymmerslöst"]], 1],
    ["Hon fick stort ___ för sitt arbete och tilldelades årets pris.", [["erkännande"], ["missnöje"], ["straff"], ["avståndstagande"]], 1],
    ["Klimatförändringarna är ett ___ problem som kräver samarbete mellan alla länder.", [["globalt"], ["lokalt"], ["obetydligt"], ["tillfälligt"]], 1],
    ["Efter den långa vandringen var de så ___ att de somnade direkt.", [["utmattade"], ["pigga"], ["uttråkade"], ["nervösa"]], 1],
    ["Museet har en ___ samling av medeltida konst, en av de största i landet.", [["omfattande"], ["blygsam"], ["bristfällig"], ["ofullständig"]], 1],
    ["Grannarnas ständiga ___ om parkeringsplatserna gjorde stämningen i huset dålig.", [["gräl"], ["samförstånd"], ["fester"], ["skämt"]], 1],
    ["Uppsatsen var välskriven men saknade en tydlig ___, vilket gjorde den svår att följa.", [["struktur"], ["längd"], ["stavning"], ["tidsgräns"]], 1],
    ["Utan regn på flera månader blev marken helt ___.", [["förtorkad"], ["blöt"], ["bördig"], ["översvämmad"]], 1],
    ["Direktören fattade ett ___ beslut utan att först rådfråga sina medarbetare.", [["egenmäktigt"], ["gemensamt"], ["demokratiskt"], ["förankrat"]], 1],
    ["De båda syskonen var så ___ att många trodde att de var tvillingar.", [["lika"], ["olika"], ["osams"], ["främmande"]], 1],
    ["Eftersom kursen var ___ var alla studenter tvungna att delta.", [["obligatorisk"], ["frivillig"], ["valbar"], ["inställd"]], 1],
    ["Författaren använder ofta ___ för att beskriva naturen, till exempel när hon kallar skogen för en katedral.", [["metaforer"], ["siffror"], ["citat"], ["fotnoter"]], 1],
    ["Efter att ha fått sparken var han mycket ___ och ville inte prata med någon.", [["nedslagen"], ["uppspelt"], ["belåten"], ["sorglös"]], 1],
    ["Den erfarna guiden kunde ___ alla fåglar i skogen enbart på deras läten.", [["identifiera"], ["skrämma"], ["mata"], ["ignorera"]], 1],
    ["Eftersom bilen var så ___ i drift valde familjen att behålla den i många år.", [["billig"], ["dyr"], ["krånglig"], ["osäker"]], 1],
    ["Tävlingen var ___ in i det sista, och vinnaren avgjordes först på sista sekunden.", [["jämn"], ["avgjord"], ["ojämn"], ["förutsägbar"]], 1],

    // ---- Nivå 2: svårare ord eller två luckor ----
    ["Ministerns uttalande var så ___ att både anhängare och kritiker tolkade det som stöd för sin egen linje.", [["tvetydigt"], ["entydigt"], ["kategoriskt"], ["explicit"]], 2],
    ["Trots sin ___ framtoning var han i själva verket mycket osäker.", [["självsäkra"], ["blyga"], ["ängsliga"], ["försynta"]], 2],
    ["Utredningen visade att olyckan inte hade en enda ___ utan berodde på en rad samverkande faktorer.", [["orsak"], ["följd"], ["lösning"], ["vittne"]], 2],
    ["Den ___ debattören lyckades alltid få publiken på sin sida, oavsett ämne.", [["vältalige"], ["fåordige"], ["blyge"], ["osäkre"]], 2],
    ["Kritikerna menade att filmens handling var ___ och att man redan efter tio minuter kunde gissa slutet.", [["förutsägbar"], ["oväntad"], ["invecklad"], ["originell"]], 2],
    ["Hans ___ inställning till regler gjorde honom populär bland eleverna men mindre omtyckt av rektorn.", [["nonchalanta"], ["strikta"], ["noggranna"], ["pedantiska"]], 2],
    ["Forskaren var ___ till de nya rönen och krävde fler studier innan hon ville uttala sig.", [["skeptisk"], ["entusiastisk"], ["positiv"], ["likgiltig"]], 2],
    ["Det är ___ att tro att problemet löser sig av sig självt; det krävs aktiva åtgärder.", [["naivt"], ["klokt"], ["realistiskt"], ["nödvändigt"]], 2],
    ["Förhandlingarna ___ och parterna lämnade mötet utan att ha nått någon överenskommelse.", [["strandade"], ["lyckades"], ["fullbordades"], ["förlängdes"]], 2],
    ["Romanen skildrar med stor ___ hur det var att växa upp i en fattig arbetarfamilj på 1930-talet.", [["inlevelse"], ["likgiltighet"], ["ironi"], ["hast"]], 2],
    ["Beslutet att lägga ner vårdcentralen möttes av ___ protester från ortens invånare.", [["högljudda"], ["försiktiga"], ["obefintliga"], ["uppskattande"]], 2],
    ["Han hade ett ___ minne och kunde återge långa samtal ord för ord.", [["fenomenalt"], ["bristfälligt"], ["selektivt"], ["diffust"]], 2],
    ["Diskussionen blev alltmer ___ och till slut var det ingen som lyssnade på någon annan.", [["upphetsad"], ["saklig"], ["stillsam"], ["konstruktiv"]], 2],
    ["Enligt kritikern var pjäsen ett ___ försök att kopiera en klassiker, helt utan egna idéer.", [["fantasilöst"], ["nyskapande"], ["djärvt"], ["lyckat"]], 2],
    ["Den tidigare så ___ stadsdelen har på senare år blivit ett populärt område med kaféer och gallerier.", [["nedgångna"], ["eftertraktade"], ["exklusiva"], ["välskötta"]], 2],
    ["Eftersom budgeten var ___ fick projektgruppen prioritera hårt bland sina idéer.", [["snäv"], ["generös"], ["obegränsad"], ["riklig"]], 2],
    ["Efter en lång och ___ debatt valde regeringen till slut att ___ det omstridda förslaget.", [["infekterad", "dra tillbaka"], ["enig", "dra tillbaka"], ["kortfattad", "förbjuda"], ["ointressant", "hylla"]], 2],
    ["Författarens tidiga verk präglades av ___, medan de senare böckerna är betydligt mer ___ och ljusa.", [["svårmod", "hoppfulla"], ["glädje", "dystra"], ["optimism", "pessimistiska"], ["humor", "allvarsamma"]], 2],
    ["Att lära sig ett nytt språk kräver ___; det går inte att bli flytande på några veckor.", [["tålamod"], ["tur"], ["pengar"], ["intuition"]], 2],
    ["Hennes förklaring var så ___ att alla i rummet genast förstod hur maskinen fungerade.", [["pedagogisk"], ["kryptisk"], ["omständlig"], ["vag"]], 2],
    ["Trots att bevisen var ___ valde åklagaren att väcka åtal.", [["bristfälliga"], ["överväldigande"], ["tydliga"], ["fällande"]], 2],
    ["Företaget har länge haft ___ på marknaden, men nu har flera konkurrenter dykt upp.", [["monopol"], ["underskott"], ["förluster"], ["svårigheter"]], 2],
    ["Den ___ professorn var känd för att glömma både möten och paraply.", [["tankspridde"], ["punktlige"], ["noggranne"], ["vaksamme"]], 2],
    ["Arkitekten ville att byggnaden skulle ___ med den omgivande naturen i stället för att dominera den.", [["harmoniera"], ["konkurrera"], ["kontrastera"], ["kollidera"]], 2],
    ["Rapporten innehöll så många ___ att den fick skrivas om från början.", [["felaktigheter"], ["förtjänster"], ["illustrationer"], ["slutsatser"]], 2],
    ["Hans ___ försök att imponera på de andra fick motsatt effekt.", [["krystade"], ["naturliga"], ["lyckade"], ["diskreta"]], 2],
    ["Löftena om lägre skatter visade sig vara ___; efter valet höjdes skatten i stället.", [["tomma"], ["uppfyllda"], ["realistiska"], ["blygsamma"]], 2],
    ["Det gamla manuskriptet var så ___ att experterna behövde flera år för att tolka det.", [["svårtytt"], ["välbevarat"], ["kortfattat"], ["lättläst"]], 2],
    ["Hon tog ___ från kollegornas åsikter och fortsatte arbeta på sitt eget sätt.", [["avstånd"], ["intryck"], ["del"], ["ansvar"]], 2],
    ["Ekonomin befann sig i en djup ___ med hög arbetslöshet och sjunkande löner.", [["lågkonjunktur"], ["högkonjunktur"], ["tillväxtfas"], ["blomstring"]], 2],
    ["Med sin ___ humor lyckades han få även de mest allvarsamma mötena att bli trivsamma.", [["avväpnande"], ["sarkastiska"], ["grova"], ["obefintliga"]], 2],
    ["Resultatet av undersökningen var ___: en klar majoritet av de tillfrågade var nöjda.", [["entydigt"], ["ofullständigt"], ["motsägelsefullt"], ["svårtolkat"]], 2],
    ["Den nya chefen var ___ i sina beslut men alltid ___ mot sina medarbetare.", [["bestämd", "lyhörd"], ["ängslig", "kylig"], ["rådvill", "nonchalant"], ["nyckfull", "hånfull"]], 2],
    ["Fyndet var ___ för forskarna, eftersom det ___ flera av de rådande teorierna om stenåldern.", [["sensationellt", "kullkastade"], ["ointressant", "bekräftade"], ["väntat", "styrkte"], ["obetydligt", "ändrade"]], 2],
    ["Trots sin ___ ålder var konstnären fortfarande lika ___ som i ungdomen.", [["höga", "produktiv"], ["unga", "trött"], ["låga", "erfaren"], ["höga", "passiv"]], 2],

    // ---- Nivå 3: formellt språk, två eller tre luckor ----
    ["Forskningsfältet har länge dominerats av ___ teorier, men på senare tid har en mer ___ syn vunnit mark.", [["deterministiska", "nyanserad"], ["nyanserade", "förenklad"], ["flexibla", "dogmatisk"], ["moderna", "samtida"]], 3],
    ["Även om hans argument var ___ och logiskt uppbyggda, lyckades han inte ___ åhörarna.", [["stringenta", "övertyga"], ["slarviga", "engagera"], ["svaga", "tråka ut"], ["ologiska", "förvirra"]], 3],
    ["Det är ___ att en så liten ändring i lagtexten kan få så ___ konsekvenser.", [["anmärkningsvärt", "långtgående"], ["självklart", "obetydliga"], ["naturligt", "marginella"], ["förväntat", "begränsade"]], 3],
    ["Kritikern ___ romanen som ett mästerverk, medan andra recensenter var betydligt mer ___.", [["hyllade", "avvaktande"], ["sågade", "entusiastiska"], ["ignorerade", "positiva"], ["kritiserade", "negativa"]], 3],
    ["Förslaget var ___ i teorin men visade sig vara ___ att genomföra i praktiken.", [["tilltalande", "omöjligt"], ["orealistiskt", "enkelt"], ["bristfälligt", "lätt"], ["lysande", "självklart"]], 3],
    ["Hennes ___ för ämnet var så stor att hon ägnade hela sitt ___ åt forskning om det.", [["passion", "yrkesliv"], ["ovilja", "liv"], ["likgiltighet", "kapital"], ["okunskap", "fritid"]], 3],
    ["Den ___ tonen i debatten gjorde det svårt att föra ett ___ samtal om sakfrågorna.", [["polariserade", "konstruktivt"], ["sansade", "upphetsat"], ["vänliga", "aggressivt"], ["lugna", "meningsfullt"]], 3],
    ["Trots att hon ___ mycket över sina misstag, var hon aldrig rädd att ___ nya utmaningar.", [["grubblade", "anta"], ["skröt", "undvika"], ["skämtade", "vägra"], ["glömde", "fly"]], 3],
    ["Utan tillräckliga ___ kan forskaren inte dra några ___ slutsatser.", [["belägg", "säkra"], ["pengar", "tveksamma"], ["idéer", "felaktiga"], ["kollegor", "tråkiga"]], 3],
    ["Studien är ___ eftersom den bygger på ett alltför ___ urval av deltagare.", [["missvisande", "begränsat"], ["tillförlitlig", "litet"], ["representativ", "snävt"], ["banbrytande", "ensidigt"]], 3],
    ["Den till synes ___ uppgiften visade sig vara betydligt mer ___ än någon hade anat.", [["enkla", "komplicerad"], ["svåra", "invecklad"], ["omöjliga", "ogenomförbar"], ["tråkiga", "enformig"]], 3],
    ["Han ___ sitt ansvar genom att skylla på sina kollegor, vilket väckte stor ___ inom företaget.", [["försökte undandra sig", "harm"], ["tog", "beundran"], ["axlade", "irritation"], ["förnekade", "glädje"]], 3],
    ["Med tiden blev skillnaderna mellan de två dialekterna allt mer ___, tills de nästan var ___.", [["utsuddade", "identiska"], ["markanta", "identiska"], ["tydliga", "likadana"], ["obetydliga", "oförenliga"]], 3],
    ["Den ___ utredningen lämnade inga frågor obesvarade och fick beröm för sin ___.", [["grundliga", "noggrannhet"], ["summariska", "kortfattadhet"], ["slarviga", "ärlighet"], ["ofullständiga", "grundlighet"]], 3],
    ["Eftersom vittnets uppgifter ___ med de tekniska bevisen, valde domstolen att ___ dem.", [["stämde överens", "godta"], ["stred mot", "godta"], ["stämde överens", "avfärda"], ["sammanföll", "ifrågasätta"]], 3],
    ["Hennes tal var ___ men ___: på bara fem minuter lyckades hon säga allt väsentligt.", [["kort", "innehållsrikt"], ["långt", "tomt"], ["kort", "intetsägande"], ["utdraget", "koncist"]], 3],
    ["Den ___ fredsprocessen hotades när en av parterna plötsligt ___ avtalet.", [["sköra", "bröt"], ["stabila", "bekräftade"], ["robusta", "undertecknade"], ["nya", "förlängde"]], 3],
    ["Att kalla förslaget ___ vore en överdrift; det är snarare ett ___ steg i rätt riktning.", [["revolutionerande", "försiktigt"], ["misslyckat", "stort"], ["meningslöst", "gigantiskt"], ["radikalt", "drastiskt"]], 3],
    ["Hans ___ intresse för historia gjorde honom till en ___ källa för alla som skrev om trakten.", [["djupa", "ovärderlig"], ["ytliga", "betydelsefull"], ["flyktiga", "pålitlig"], ["obefintliga", "ovärderlig"]], 3],
    ["Trots ___ protester från allmänheten beslutade kommunen att ___ parken för att bygga bostäder.", [["omfattande", "exploatera"], ["obefintliga", "bevara"], ["svaga", "utvidga"], ["ljumma", "skydda"]], 3],
    ["Konstnärens verk är ___: de kan tolkas på många olika sätt och låter sig inte ___ till en enda sanning.", [["mångtydiga", "reduceras"], ["entydiga", "begränsas"], ["banala", "ledas"], ["tydliga", "föras"]], 3],
    ["Den tidigare så ___ ledaren blev med åren alltmer ___ och vägrade lyssna på kritik.", [["lyhörda", "egenmäktig"], ["envisa", "öppen"], ["auktoritära", "ödmjuk"], ["ödmjuka", "prestigelös"]], 3],
    ["Rapporten ___ de risker som projektet medför och ___ därför att det skjuts upp.", [["belyser", "rekommenderar"], ["bagatelliserar", "rekommenderar"], ["ignorerar", "kräver"], ["förnekar", "föreslår"]], 3],
    ["Det ___ klimatet på arbetsplatsen gjorde att många anställda kände sig ___ och sa upp sig.", [["hårda", "utbrända"], ["vänliga", "uppskattade"], ["avslappnade", "utbrända"], ["kollegiala", "sedda"]], 3],
    ["Kritiken mot boken var ___: ingen av recensenterna hade något ___ att säga om den.", [["samstämmig", "positivt"], ["splittrad", "negativt"], ["mild", "elakt"], ["blandad", "gott"]], 3],
    ["Hans ___ sätt att uttrycka sig gjorde att även ___ ämnen blev begripliga för en bred publik.", [["klara", "komplexa"], ["dunkla", "enkla"], ["kryptiska", "vardagliga"], ["omständliga", "triviala"]], 3],
    ["Reformen var tänkt att ___ byråkratin, men i praktiken ledde den till ännu fler ___.", [["minska", "blanketter"], ["öka", "förenklingar"], ["avskaffa", "lättnader"], ["bevara", "nedskärningar"]], 3],
    ["Det var ___ att se hur den en gång så ___ fabriken nu stod tom och förfallen.", [["vemodigt", "livliga"], ["glädjande", "övergivna"], ["lugnande", "tysta"], ["roande", "nedlagda"]], 3],
    ["Författaren har ett ___ öga för detaljer, vilket gör hennes miljöskildringar ovanligt ___.", [["skarpt", "levande"], ["slött", "färgstarka"], ["ointresserat", "precisa"], ["skarpt", "blodfattiga"]], 3],
    ["Den ___ tillväxten under decenniet ___ av en plötslig finanskris.", [["stadiga", "avbröts"], ["svaga", "förstärktes"], ["obefintliga", "följdes"], ["snabba", "förutsågs"]], 3],
    ["Att ___ problemen är inte detsamma som att lösa dem; de finns kvar oavsett hur mycket man ___ dem.", [["förneka", "blundar för"], ["analysera", "studerar"], ["lösa", "arbetar med"], ["erkänna", "diskuterar"]], 3],
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = MEK;
  else root.HP_MEK = MEK;
})(this);
