// HP-ord (ORD-delen) med betydelse. Ordet i versaler, ledtråden är en synonym/förklaring.
(function (root) {
  const WORDS = [
    ["ABDIKERA", "avsäga sig tronen"],
    ["ADEKVAT", "lämplig, passande"],
    ["AFFEKTERAD", "tillgjord, onaturlig"],
    ["AGITERA", "uppvigla, driva opinion"],
    ["AMBIVALENT", "kluven, tvehågsen"],
    ["ANAKRONISM", "något som hör till en annan tid"],
    ["ANEKDOT", "kort, underhållande berättelse"],
    ["ANTAGONIST", "motståndare, motspelare"],
    ["APATISK", "likgiltig, håglös"],
    ["ARKAISK", "ålderdomlig"],
    ["ASKETISK", "försakande, avhållsam"],
    ["AUKTORITÄR", "maktfullkomlig, sträng"],
    ["AVOG", "ovänligt inställd"],
    ["BAGATELL", "struntsak, småsak"],
    ["BANAL", "alldaglig, platt"],
    ["BENÄGEN", "villig, böjd för"],
    ["BESINNA", "tänka efter, betänka"],
    ["BETUTTAD", "förälskad"],
    ["BISARR", "underlig, besynnerlig"],
    ["BRYDD", "bekymrad, förlägen"],
    ["CYNISK", "känslokall, hånfull"],
    ["DEKADENT", "förfallen"],
    ["DIGNA", "böjas under tyngd"],
    ["DISKREPANS", "oöverensstämmelse, skillnad"],
    ["DOGMATISK", "orubblig i sina åsikter"],
    ["DUBIÖS", "tvivelaktig"],
    ["DYSTER", "nedstämd, mörk"],
    ["EKVIVALENT", "likvärdig"],
    ["ELOKVENT", "vältalig"],
    ["EMFAS", "eftertryck"],
    ["EMPIRISK", "grundad på erfarenhet"],
    ["EPITET", "tillnamn, benämning"],
    ["EUFORI", "stark lyckokänsla"],
    ["EXPLICIT", "uttrycklig, tydlig"],
    ["FATAL", "ödesdiger"],
    ["FEJD", "strid, konflikt"],
    ["FIASKO", "misslyckande"],
    ["FLEGMATISK", "trög, oberörd"],
    ["FRAMSYNT", "förutseende"],
    ["FRAPPERAD", "förvånad, slagen"],
    ["FRUGAL", "enkel, sparsam"],
    ["FÖRSTRÖDD", "tankspridd"],
    ["GALANT", "artig, ridderlig"],
    ["GEMYTLIG", "trivsam, godmodig"],
    ["GENANT", "pinsam"],
    ["GRANNLAGA", "ömtålig, känslig"],
    ["GROTESK", "vanskapt, absurd"],
    ["HABIL", "skicklig"],
    ["HETEROGEN", "olikartad, oenhetlig"],
    ["HOMOGEN", "likartad, enhetlig"],
    ["HUMAN", "mild, människovänlig"],
    ["HYBRIS", "övermod"],
    ["HÄMMA", "hindra, bromsa"],
    ["HÖVISK", "artig, belevad"],
    ["IDOG", "flitig, ihärdig"],
    ["IDYLL", "fridfull plats eller tillvaro"],
    ["IMPLICIT", "underförstådd"],
    ["IMPULSIV", "hastig, obetänksam"],
    ["INDOLENT", "håglös, loj"],
    ["INFAM", "nedrig, skändlig"],
    ["INKOGNITO", "under annat namn"],
    ["INSINUERA", "antyda, låta påskina"],
    ["KALABALIK", "tumult, oordning"],
    ["KAVAT", "modig, kaxig"],
    ["KLANDRA", "kritisera, anmärka på"],
    ["KOMPETENT", "kunnig, behörig"],
    ["KONCIS", "kortfattad"],
    ["KONTROVERSIELL", "omstridd"],
    ["KORRUMPERA", "muta, fördärva"],
    ["KUTYM", "sed, bruk"],
    ["KVERULANT", "gnällspik"],
    ["LABIL", "ostadig, instabil"],
    ["LAKONISK", "kort och torr"],
    ["LAPPRI", "struntsak"],
    ["LEGITIM", "rättmätig, laglig"],
    ["LISMA", "fjäska, smickra"],
    ["LOJAL", "trogen"],
    ["LUKRATIV", "lönsam"],
    ["LYHÖRD", "uppmärksam, känslig"],
    ["MARGINELL", "obetydlig, liten"],
    ["MELANKOLISK", "svårmodig"],
    ["MINUTIÖS", "ytterst noggrann"],
    ["MONOTON", "enformig"],
    ["MUNTER", "glad, uppsluppen"],
    ["NAIV", "godtrogen"],
    ["NONCHALANT", "likgiltig, vårdslös"],
    ["NOSTALGI", "längtan tillbaka"],
    ["NYCK", "infall"],
    ["NÄPST", "tillrättavisning"],
    ["OBSOLET", "föråldrad"],
    ["OBSTINAT", "envis, trotsig"],
    ["OFÖRVITLIG", "oklanderlig"],
    ["OMNIPOTENT", "allsmäktig"],
    ["OPTIMAL", "bästa möjliga"],
    ["ORAKEL", "siare, spåman"],
    ["PASSIV", "overksam"],
    ["PATOS", "glöd, stark inlevelse"],
    ["PEDANTISK", "överdrivet noggrann"],
    ["PERIFER", "avlägsen, oviktig"],
    ["PESSIMIST", "svartseende person"],
    ["PITTORESK", "målerisk"],
    ["PLAGIAT", "efterapning, avskrift"],
    ["PLAUSIBEL", "trolig, rimlig"],
    ["POMPÖS", "ståtlig, överdådig"],
    ["PRAGMATISK", "praktisk, saklig"],
    ["PREMISS", "förutsättning"],
    ["PRETENTIÖS", "anspråksfull"],
    ["PROFAN", "världslig, icke-religiös"],
    ["PROVOKATIV", "utmanande"],
    ["PUERIL", "barnslig"],
    ["RABALDER", "bråk, uppståndelse"],
    ["RATIONELL", "förnuftig, effektiv"],
    ["REDUNDANT", "överflödig"],
    ["RELEVANT", "som hör till saken"],
    ["REMINISCENS", "minne, kvarleva"],
    ["RESIGNERAD", "uppgiven"],
    ["RESTRIKTIV", "begränsande, återhållsam"],
    ["RIGID", "stel, strikt"],
    ["SANKTION", "straffåtgärd"],
    ["SARKASTISK", "spydig"],
    ["SKEPTISK", "tvivlande"],
    ["SKRÄVLA", "skryta"],
    ["SNÅL", "gnidig"],
    ["SPLITTRAD", "oenig, uppdelad"],
    ["SPORADISK", "enstaka, tillfällig"],
    ["STAGNERA", "avstanna"],
    ["STOISK", "orubbligt lugn"],
    ["SUBTIL", "fin, svårfångad"],
    ["SUPERFICIELL", "ytlig"],
    ["TABU", "förbjudet ämne"],
    ["TENDENS", "benägenhet, riktning"],
    ["TRAKASSERA", "ofreda, plåga"],
    ["TRIVIAL", "vardaglig, obetydlig"],
    ["TVETYDIG", "dubbeltydig"],
    ["UMBÄRA", "klara sig utan"],
    ["UNISON", "enstämmig"],
    ["UTOPI", "drömsamhälle"],
    ["VAG", "oklar, obestämd"],
    ["VAGABOND", "luffare"],
    ["VEDERGÄLLNING", "hämnd"],
    ["VEDERHÄFTIG", "tillförlitlig"],
    ["VEDERMÖDA", "prövning, svårighet"],
    ["VERBAL", "muntlig, språklig"],
    ["VITAL", "livskraftig"],
    ["VOLATIL", "flyktig, instabil"],
    ["ÅTERHÅLLSAM", "måttfull"],
    ["ÄRBAR", "anständig, dygdig"],
    ["ÖDMJUK", "anspråkslös"],
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = WORDS;
  else root.HP_WORDS = WORDS;
})(this);
