// HP-ord (ORD-delen) med betydelse – drygt 2 000 ord av den typ som brukar förekomma på provet. Ordet i versaler, ledtråden är en synonym/förklaring.
(function (root) {
  const WORDS = [
    ["ABDIKATION", "avgång från tronen"],
    ["ABDIKERA", "avsäga sig tronen"],
    ["ABERRATION", "avvikelse, snedsteg"],
    ["ABNORM", "onormal"],
    ["ABONNERA", "prenumerera"],
    ["ABSOLUT", "fullständig, ovillkorlig"],
    ["ABSORBERA", "suga upp"],
    ["ABSTRAKT", "teoretisk, ej konkret"],
    ["ABSURD", "orimlig, meningslös"],
    ["ACCEPTABEL", "godtagbar"],
    ["ACKLIMATISERA", "vänja vid nytt klimat"],
    ["ACKORD", "samklang, överenskommelse"],
    ["ACKREDITERA", "godkänna officiellt"],
    ["ACKUMULERA", "samla på hög"],
    ["ADAPTERA", "anpassa"],
    ["ADEKVAT", "lämplig, passande"],
    ["ADEPT", "lärjunge"],
    ["ADMINISTRERA", "förvalta, sköta"],
    ["ADMIRERA", "beundra"],
    ["ADRESSAT", "mottagare"],
    ["ADRETT", "söt, klädsam"],
    ["AFFEKT", "stark känsla"],
    ["AFFEKTERAD", "tillgjord, onaturlig"],
    ["AFFINITET", "släktskap, dragning"],
    ["AFFRONT", "förolämpning"],
    ["AGENDA", "dagordning"],
    ["AGGRESSIV", "angriplig"],
    ["AGITATOR", "uppviglare"],
    ["AGITERA", "uppvigla, driva opinion"],
    ["AKADEMISK", "högskolemässig"],
    ["AKRIBI", "noggrannhet, precision"],
    ["AKTNING", "högt värderande"],
    ["AKTSAM", "försiktig och varsam"],
    ["AKTUALISERA", "göra aktuell"],
    ["AKUSTISK", "som rör ljud"],
    ["AKUT", "brådskande, plötslig"],
    ["ALERT", "vaken och snabb"],
    ["ALIBI", "bevis på att man var på annan plats"],
    ["ALLDAGLIG", "vanlig, ordinär"],
    ["ALLEGORI", "sinnebildlig framställning"],
    ["ALLIANS", "förbindelse mellan stater"],
    ["ALLITTERATION", "bokstavsrim"],
    ["ALLMOGE", "bondebefolkning förr"],
    ["ALLMOSA", "gåva till fattig"],
    ["ALLMÄNNING", "gemensam mark"],
    ["ALLOKERA", "fördela resurser"],
    ["ALLUSION", "anspelning"],
    ["ALLVETANDE", "som vet allt"],
    ["ALMANACKA", "kalender"],
    ["ALTERNATIV", "val, möjlighet"],
    ["ALTRUISM", "osjälviskhet"],
    ["AMATÖR", "lekman, icke-professionell"],
    ["AMBASSAD", "beskickning"],
    ["AMBITION", "strävan, målsättning"],
    ["AMBITIÖS", "strävsam, målmedveten"],
    ["AMBIVALENT", "kluven, tvehågsen"],
    ["AMBULERANDE", "kringresande"],
    ["AMNESTI", "allmän benådning"],
    ["AMORAL", "utan moraliska principer"],
    ["AMORF", "formlös"],
    ["AMULETT", "skyddsföremål"],
    ["ANAKRONISM", "något som hör till en annan tid"],
    ["ANALFABET", "person som inte kan läsa"],
    ["ANALOG", "motsvarande, jämförbar"],
    ["ANALOGI", "likhet, motsvarighet"],
    ["ANALYS", "undersökning, uppdelning"],
    ["ANAMMA", "ta till sig, godta"],
    ["ANARKI", "laglöshet, oordning"],
    ["ANATEMA", "bannlysning"],
    ["ANDAKT", "stilla bön, vördnad"],
    ["ANEKDOT", "kort, underhållande berättelse"],
    ["ANEKDOTISK", "som bygger på enstaka berättelser"],
    ["ANEMISK", "blodfattig, kraftlös"],
    ["ANFÄKTELSE", "frestelse, tvivel"],
    ["ANGELÄGEN", "viktig, mån om"],
    ["ANGIVARE", "tjallare"],
    ["ANGRIPA", "attackera"],
    ["ANHOPNING", "ansamling"],
    ["ANIMERAD", "livlig"],
    ["ANIMOSITET", "fientlighet, agg"],
    ["ANKNYTNING", "förbindelse"],
    ["ANNALER", "årsböcker, krönikor"],
    ["ANNEKTERA", "lägga beslag på område"],
    ["ANNEX", "tillbyggnad"],
    ["ANNULLERA", "upphäva, ogiltigförklara"],
    ["ANOMALI", "avvikelse från det normala"],
    ["ANONYM", "namnlös"],
    ["ANRIKA", "koncentrera, berika"],
    ["ANSATS", "försök, början"],
    ["ANSEENDE", "gott rykte, aktning"],
    ["ANSPRÅKSFULL", "fordrande, krävande"],
    ["ANSTÅND", "uppskov"],
    ["ANSTÖTLIG", "stötande, oanständig"],
    ["ANTAGLIGEN", "troligen"],
    ["ANTAGONIST", "motståndare, motspelare"],
    ["ANTASTA", "ofreda"],
    ["ANTIK", "forntida, gammal"],
    ["ANTIPATI", "stark ovilja mot något"],
    ["ANTITES", "motsats"],
    ["ANTOLOGI", "samlingsverk"],
    ["ANTYDA", "låta förstå, ge en vink"],
    ["APATI", "likgiltighet, håglöshet"],
    ["APATISK", "likgiltig, håglös"],
    ["APOKRYF", "oäkta, tvivelaktig"],
    ["APOLOGI", "försvarstal"],
    ["APPELLERA", "vädja"],
    ["APPLÅDERA", "klappa händerna"],
    ["APPROXIMATIV", "ungefärlig"],
    ["APROPÅ", "på tal om"],
    ["APTIT", "matlust"],
    ["ARBETSAM", "som arbetar mycket"],
    ["ARBITRÄR", "godtycklig"],
    ["ARENA", "kampplats"],
    ["ARGUMENT", "skäl, bevis"],
    ["ARGUMENTERA", "föra fram skäl"],
    ["ARISTOKRATI", "adel, överklass"],
    ["ARKAISK", "ålderdomlig"],
    ["ARKETYP", "urbild, grundtyp"],
    ["ARKIV", "dokumentsamling"],
    ["ARMOD", "fattigdom"],
    ["AROMATISK", "väldoftande"],
    ["ARRENDE", "hyra av mark"],
    ["ARROGANS", "högfärd"],
    ["ARROGANT", "högfärdig, översittaraktig"],
    ["ARTIFICIELL", "konstgjord"],
    ["ARTIG", "hövlig"],
    ["ARTIKULERA", "uttala tydligt"],
    ["ASKES", "självförsakelse"],
    ["ASKETISK", "försakande, avhållsam"],
    ["ASOCIAL", "samhällsfientlig"],
    ["ASPEKT", "synpunkt"],
    ["ASPIRANT", "sökande, kandidat"],
    ["ASPIRERA", "sträva efter"],
    ["ASSIMILERA", "uppta, införliva"],
    ["ASSISTERA", "hjälpa till"],
    ["ASSOCIERA", "förknippa"],
    ["ASYL", "fristad"],
    ["ASYMMETRI", "oregelbundenhet"],
    ["ATMOSFÄR", "stämning"],
    ["ATTEST", "intyg"],
    ["ATTITYD", "inställning"],
    ["ATTRAKTIV", "lockande, tilldragande"],
    ["AUDIENS", "officiellt besök hos makthavare"],
    ["AUKTION", "offentlig försäljning"],
    ["AUKTORITET", "sakkunnig person, makt"],
    ["AUKTORITÄR", "maktfullkomlig, sträng"],
    ["AUTENTISK", "äkta, verklig"],
    ["AUTONOM", "självstyrande"],
    ["AVANCERAD", "komplicerad, framskriden"],
    ["AVBÖN", "ursäkt"],
    ["AVERSION", "motvilja"],
    ["AVFÄLLING", "överlöpare, förrädare"],
    ["AVFÄRDA", "vifta bort"],
    ["AVGRUND", "djup klyfta"],
    ["AVGUDA", "dyrka"],
    ["AVGÖRANDE", "utslagsgivande"],
    ["AVHANDLING", "vetenskaplig skrift"],
    ["AVHÅLLSAM", "som avstår från njutningar"],
    ["AVKASTNING", "vinst, utbyte"],
    ["AVKOMMA", "ättlingar"],
    ["AVLÅNG", "utdragen, oval"],
    ["AVMÄTT", "reserverad, kylig"],
    ["AVOG", "ovänligt inställd"],
    ["AVRÅDA", "ge rådet att låta bli"],
    ["AVSKAFFA", "ta bort, stryka"],
    ["AVSKY", "vämjelse"],
    ["AVSMAK", "olust"],
    ["AVSTÅNDSTAGANDE", "markerat ogillande"],
    ["AVSÄTTA", "avskeda"],
    ["AVTRUBBAD", "okänslig, likgiltig"],
    ["AVUND", "missunnsamhet"],
    ["AVVIKANDE", "annorlunda"],
    ["AVVISANDE", "ovänlig, kylig"],
    ["AVVÄGNING", "bedömning, balans"],
    ["AXIOM", "grundsats som inte behöver bevisas"],
    ["BAGATELL", "struntsak, småsak"],
    ["BAGATELLISERA", "förringa"],
    ["BAKSIDA", "nackdel"],
    ["BAKTANKE", "dold avsikt"],
    ["BALANS", "jämvikt"],
    ["BALANSERAD", "sansad, avvägd"],
    ["BANAL", "alldaglig, platt"],
    ["BANBRYTANDE", "nydanande"],
    ["BANKRUTT", "konkurs"],
    ["BARBARISK", "grym, ociviliserad"],
    ["BARMHÄRTIG", "medlidsam"],
    ["BARNSLIG", "infantil"],
    ["BARRIKAD", "hinder, spärr"],
    ["BARSK", "sträng, kärv"],
    ["BASAL", "allra mest grundläggande"],
    ["BEDAGAD", "gammal, sliten"],
    ["BEDRIFT", "framstående prestation"],
    ["BEDRÄGLIG", "falsk, vilseledande"],
    ["BEDRÖVLIG", "urusel"],
    ["BEDYRA", "försäkra, intyga"],
    ["BEFALLA", "beordra"],
    ["BEFOGAD", "berättigad, motiverad"],
    ["BEFOGENHET", "rätt att handla"],
    ["BEFRIA", "släppa loss, rädda"],
    ["BEFÄSTA", "stärka, säkra"],
    ["BEGABBA", "håna"],
    ["BEGIVEN", "förtjust i, sugen på"],
    ["BEGRUNDA", "fundera över"],
    ["BEHAG", "charm, ljuvlighet"],
    ["BEHAGSJUK", "fåfäng, kokett"],
    ["BEHJÄRTANSVÄRD", "värd stöd"],
    ["BEHÄNDIG", "smidig, flink"],
    ["BEHÄRSKAD", "lugn, kontrollerad"],
    ["BEKLAGANSVÄRD", "värd medlidande"],
    ["BEKLÄMMANDE", "nedslående"],
    ["BEKRÄFTA", "bestyrka"],
    ["BEKVÄM", "behaglig, lat"],
    ["BEKVÄMLIGHET", "komfort"],
    ["BEKYMMERSAM", "oroande"],
    ["BELASTNING", "börda"],
    ["BELEVAD", "väluppfostrad"],
    ["BELÅTEN", "nöjd, självgod"],
    ["BELÄGG", "bevis, stöd"],
    ["BELÖNING", "premie"],
    ["BENÅDA", "efterskänka straff"],
    ["BENÄGEN", "villig, böjd för"],
    ["BENÄGENHET", "böjelse, anlag"],
    ["BEPRÖVAD", "testad och säker"],
    ["BERIKA", "göra rikare"],
    ["BERUSAD", "rusig"],
    ["BERÖMVÄRD", "lovvärd"],
    ["BESATT", "helt uppslukad"],
    ["BESEGRA", "vinna över"],
    ["BESINNA", "tänka efter, betänka"],
    ["BESINNING", "eftertanke"],
    ["BESJÄLAD", "full av liv och känsla"],
    ["BESKEDLIG", "fredlig, stillsam"],
    ["BESKYDDARE", "mecenat, försvarare"],
    ["BESKÄFTIG", "klåfingrig, ivrig att lägga sig i"],
    ["BESTICKA", "muta"],
    ["BESTICKANDE", "skenbart övertygande"],
    ["BESTÅNDANDE", "som finns kvar länge"],
    ["BESTÅNDSDEL", "komponent"],
    ["BESVIKEN", "missräknad"],
    ["BESVÄRJA", "frammana, vädja"],
    ["BESYNNERLIG", "högst märklig"],
    ["BETAGANDE", "förtrollande"],
    ["BETAGEN", "förtjust, hänförd"],
    ["BETINGA", "förutsätta, kosta"],
    ["BETINGELSE", "förutsättning, villkor"],
    ["BETRAKTELSE", "reflektion"],
    ["BETROD", "anförtrodd, pålitlig"],
    ["BETUTTAD", "förälskad"],
    ["BETYDANDE", "avsevärd"],
    ["BEVARA", "behålla"],
    ["BEVEKANDE", "rörande, vädjande"],
    ["BEVEKELSEGRUND", "motiv, drivkraft"],
    ["BIBEHÅLLA", "bevara"],
    ["BIDRA", "medverka"],
    ["BIDRAGANDE", "medverkande"],
    ["BIFALL", "medhåll, applåder"],
    ["BIGOTT", "skenhelig, trångsynt i tron"],
    ["BILAGA", "tillägg till skrift"],
    ["BILDNING", "kunskap, kultur"],
    ["BINDANDE", "förpliktande"],
    ["BISARR", "underlig, besynnerlig"],
    ["BISTER", "sträng, dyster"],
    ["BISTÅ", "hjälpa"],
    ["BITSK", "argsint, ilsken"],
    ["BLASERAD", "uttråkad, likgiltig"],
    ["BLASFEMI", "hädelse"],
    ["BLEK", "färglös"],
    ["BLOTTA", "lägga i dagen"],
    ["BLYGHET", "skygghet"],
    ["BLYGSAM", "tillbakadragen, inte skrytsam"],
    ["BLÄNDANDE", "strålande"],
    ["BOHEMISK", "obunden, konstnärlig"],
    ["BOJKOTT", "vägran att delta eller handla"],
    ["BORGEN", "säkerhet för lån"],
    ["BORGERLIG", "medelklass-, icke-socialistisk"],
    ["BORNERAD", "inskränkt, trångsynt"],
    ["BRAGD", "modig handling"],
    ["BRAMARBAS", "skrytmåns"],
    ["BRASKANDE", "uppseendeväckande"],
    ["BRAVAD", "hjältedåd"],
    ["BRISTFÄLLIG", "ofullständig"],
    ["BRUTAL", "våldsam, rå"],
    ["BRYDD", "bekymrad, förlägen"],
    ["BRYSK", "tvär, burdus"],
    ["BRYTNINGSTID", "omvälvningsperiod"],
    ["BRÅDSKA", "hast"],
    ["BRÅDSKANDE", "angelägen, akut"],
    ["BRÄCKLIG", "skröplig, ömtålig"],
    ["BUDSKAP", "meddelande"],
    ["BUFFERT", "reserv, stötdämpare"],
    ["BURDUS", "ohyfsad, klumpig"],
    ["BURLESK", "grovt komisk"],
    ["BYRÅKRATI", "pappersvälde, ämbetsmannavälde"],
    ["BYRÅKRATISK", "formalistisk"],
    ["BÅNGSTYRIG", "svårstyrd, motsträvig"],
    ["BÄRKRAFTIG", "hållbar"],
    ["BÖJELSE", "dragning, lust"],
    ["BÖRD", "härkomst"],
    ["CELIBAT", "ogift stånd"],
    ["CENSUR", "granskning och förbud"],
    ["CENSURERA", "stryka, förbjuda"],
    ["CENTRAL", "viktig, belägen i mitten"],
    ["CEREMONI", "högtidlig akt"],
    ["CERTIFIERA", "intyga, godkänna"],
    ["CHARLATAN", "bluffmakare"],
    ["CHARMANT", "förtjusande"],
    ["CHAUVINISM", "överdriven nationalism"],
    ["CIRKULERA", "gå runt, spridas"],
    ["CITADELL", "borg, fästning"],
    ["CIVILISERAD", "hyfsad, samhällelig"],
    ["CYKLISK", "periodiskt återkommande"],
    ["CYNISK", "känslokall, hånfull"],
    ["CYNISM", "hånfull misstro"],
    ["DAGDRIVARE", "lätting"],
    ["DAGDRÖM", "fantasi"],
    ["DEBATTERA", "diskutera"],
    ["DEBUT", "första framträdande"],
    ["DEDUCERA", "härleda logiskt"],
    ["DEFAITISM", "uppgivenhet"],
    ["DEFEKT", "skadad, felaktig"],
    ["DEFENSIV", "försvarsinriktad"],
    ["DEFICIT", "underskott"],
    ["DEFINITIV", "slutgiltig"],
    ["DEGENERERA", "urarta"],
    ["DEKADENS", "moraliskt förfall"],
    ["DEKADENT", "förfallen"],
    ["DEKLAMERA", "läsa högt med inlevelse"],
    ["DEKLARERA", "förklara, tillkännage"],
    ["DEKORERA", "pryda"],
    ["DEKRET", "förordning"],
    ["DELAKTIG", "inblandad"],
    ["DELEGERA", "överlåta uppgifter"],
    ["DELIKAT", "läcker, ömtålig"],
    ["DELIKATESS", "läckerhet"],
    ["DEMAGOG", "folkuppviglare"],
    ["DEMOKRATISK", "folkstyrd"],
    ["DEMONSTRERA", "visa, protestera"],
    ["DEMONTERA", "montera isär"],
    ["DEPONERA", "lämna i förvar"],
    ["DEPRAVERAD", "moraliskt fördärvad"],
    ["DEPRESSION", "djup nedgång"],
    ["DEPRIMERAD", "nedslagen"],
    ["DESPERAT", "förtvivlad"],
    ["DESPOT", "tyrann, envåldshärskare"],
    ["DESTILLERA", "utvinna det väsentliga"],
    ["DESTINATION", "resmål"],
    ["DESTRUKTIV", "förstörande"],
    ["DETALJ", "enskildhet"],
    ["DETALJERAD", "utförlig"],
    ["DETRONISERA", "störta från tronen"],
    ["DEVALVERA", "minska i värde"],
    ["DIAGNOS", "sjukdomsbestämning"],
    ["DIALEKT", "lokal språkvariant"],
    ["DIALOG", "samtal"],
    ["DIDAKTISK", "undervisande"],
    ["DIFFAMERA", "förtala"],
    ["DIFFERENTIERA", "särskilja"],
    ["DIFFUS", "svävande, otydlig"],
    ["DIGNA", "böjas under tyngd"],
    ["DIGNITET", "värdighet"],
    ["DIGRESSION", "utvikning från ämnet"],
    ["DIKOTOMI", "tudelning"],
    ["DIKTAT", "påtvingat beslut"],
    ["DIKTERA", "föreskriva, bestämma"],
    ["DILEMMA", "svårt val"],
    ["DILETTANT", "amatör i kulturella ting"],
    ["DIMENSION", "omfång, storlek"],
    ["DIPLOMATISK", "taktfull"],
    ["DIREKTIV", "anvisning"],
    ["DISCIPLIN", "ordning"],
    ["DISHARMONI", "oenighet"],
    ["DISKREDITERA", "svärta ner, misskreditera"],
    ["DISKREPANS", "oöverensstämmelse, skillnad"],
    ["DISKRET", "försiktig, inte uppseendeväckande"],
    ["DISKRETION", "finkänslighet, tystnad"],
    ["DISKRIMINERA", "särbehandla negativt"],
    ["DISKURS", "samtal, resonemang"],
    ["DISKUTABEL", "som kan ifrågasättas"],
    ["DISKVALIFICERA", "utesluta från tävling"],
    ["DISPARAT", "olikartad"],
    ["DISPENS", "undantag från regel"],
    ["DISPONERA", "förfoga över"],
    ["DISPUT", "ordväxling, tvist"],
    ["DISSONANS", "missljud"],
    ["DISTANSERA", "hålla avstånd"],
    ["DISTINGERAD", "förnäm"],
    ["DISTINKT", "skarp, tydligt avgränsad"],
    ["DISTRAHERA", "störa, avleda"],
    ["DISTRIKT", "område"],
    ["DIVA", "primadonna"],
    ["DIVERGERA", "gå isär"],
    ["DIVERSIFIERA", "variera, sprida"],
    ["DJÄRV", "modig, vågad"],
    ["DOGM", "orubblig trossats"],
    ["DOGMATISK", "orubblig i sina åsikter"],
    ["DOKTRIN", "lära, lärosats"],
    ["DOKUMENTERA", "bevisa, registrera"],
    ["DOMESTICERA", "tämja"],
    ["DOMINANS", "överlägsenhet"],
    ["DOMINANT", "härskande, förhärskande"],
    ["DOMINERA", "härska"],
    ["DOSERING", "mängd"],
    ["DRAKONISK", "mycket sträng"],
    ["DRAMATISK", "spännande, våldsam"],
    ["DRASTISK", "kraftig, genomgripande"],
    ["DRIVKRAFT", "motivation"],
    ["DRYG", "tröttsamt lång"],
    ["DRÄGLIG", "uthärdlig"],
    ["DUALISM", "tvåfald"],
    ["DUBBELMORAL", "olika måttstockar"],
    ["DUBIÖS", "tvivelaktig"],
    ["DUGLIG", "användbar, kapabel"],
    ["DUKTIG", "kunnig, begåvad"],
    ["DUMDRISTIG", "vågad, oförsiktig"],
    ["DUNKEL", "oklar, mörk"],
    ["DUPERA", "lura"],
    ["DYGDIG", "moraliskt föredömlig"],
    ["DYNAMISK", "kraftfull, föränderlig"],
    ["DYRKA", "tillbe"],
    ["DYSFUNKTIONELL", "som inte fungerar"],
    ["DYSTER", "nedstämd, mörk"],
    ["DYSTOPI", "mardrömssamhälle"],
    ["DÅRAKTIG", "dum, oklok"],
    ["EFEMÄR", "kortvarig, flyktig"],
    ["EFFEKTIV", "verkningsfull"],
    ["EFTERFRÅGAN", "köpintresse"],
    ["EFTERGIVEN", "släpphänt"],
    ["EFTERLÄNGTAD", "önskad"],
    ["EFTERSINNANDE", "eftertänksam"],
    ["EFTERSKÄNKA", "avskriva skuld"],
    ["EFTERSTRÄVA", "försöka uppnå"],
    ["EFTERTANKE", "noggrant övervägande"],
    ["EFTERTRAKTAD", "åtråvärd"],
    ["EFTERTRYCKLIG", "kraftfull, bestämd"],
    ["EGALITÄR", "jämlik"],
    ["EGENDOMLIG", "konstig, märklig"],
    ["EGENHET", "särdrag"],
    ["EGENMÄKTIG", "självsvåldig"],
    ["EGENNYTTA", "eget intresse framför andras"],
    ["EGENSINNIG", "självrådig"],
    ["EGOCENTRISK", "självupptagen"],
    ["EGOISM", "själviskhet"],
    ["EKLATANT", "påfallande, uppenbar"],
    ["EKLEKTISK", "som väljer ut och blandar"],
    ["EKOLOGISK", "miljövänlig"],
    ["EKONOMI", "hushållning"],
    ["EKVILIBRIST", "mycket skicklig utövare"],
    ["EKVIVALENT", "likvärdig"],
    ["ELAKARTAD", "farlig, ondartad"],
    ["ELASTISK", "töjbar"],
    ["ELEGANT", "smakfull, stilig"],
    ["ELEGI", "sorgdikt"],
    ["ELEMENTÄR", "grundläggande"],
    ["ELIMINERA", "avlägsna, utesluta"],
    ["ELIT", "toppskikt"],
    ["ELOGE", "beröm"],
    ["ELOKVENT", "vältalig"],
    ["EMANCIPERA", "frigöra"],
    ["EMBARGO", "handelsförbud"],
    ["EMFAS", "eftertryck"],
    ["EMIGRANT", "utvandrare"],
    ["EMIGRERA", "utvandra"],
    ["EMINENT", "framstående, utmärkt"],
    ["EMISSION", "utsläpp, utgivning"],
    ["EMOTIONELL", "känslomässig"],
    ["EMOTSE", "förvänta sig"],
    ["EMPATI", "inlevelseförmåga"],
    ["EMPIRI", "erfarenhet, data"],
    ["EMPIRISK", "grundad på erfarenhet"],
    ["ENERGISK", "kraftfull, driftig"],
    ["ENFALDIG", "dum, naiv"],
    ["ENGAGEMANG", "hängivenhet"],
    ["ENGAGERAD", "intresserad"],
    ["ENHETLIG", "sammanhållen"],
    ["ENIGMATISK", "gåtfull"],
    ["ENKELSPÅRIG", "ensidig i sitt tänkande"],
    ["ENKLAV", "isolerat område"],
    ["ENORM", "väldig"],
    ["ENSIDIG", "som bara ser en sida"],
    ["ENTUSIASM", "hänförelse, iver"],
    ["ENTUSIAST", "hängiven anhängare"],
    ["ENVIS", "som inte ger sig"],
    ["ENVÄLDE", "diktatur"],
    ["EPIDEMI", "farsot, smittspridning"],
    ["EPIGON", "efterapare"],
    ["EPILOG", "efterord"],
    ["EPITET", "tillnamn, benämning"],
    ["EPOK", "tidsperiod, era"],
    ["ERFAREN", "rutinerad"],
    ["ERINRA", "påminna"],
    ["ERKÄNNA", "medge"],
    ["ERÖVRING", "intagande"],
    ["ESKALERA", "trappas upp"],
    ["ESOTERISK", "endast för de invigda"],
    ["ESTETISK", "som rör skönhet"],
    ["ETABLERA", "grunda, upprätta"],
    ["ETABLISSEMANG", "maktelit"],
    ["ETAPP", "del av sträcka"],
    ["ETIKETT", "formella umgängesregler"],
    ["ETISK", "sedlig, moralisk"],
    ["ETNISK", "som rör folkgrupp"],
    ["ETYMOLOGI", "läran om ords ursprung"],
    ["EUFEMISM", "förskönande omskrivning"],
    ["EUFORI", "stark lyckokänsla"],
    ["EUFORISK", "lyckorusig"],
    ["EVAKUERA", "utrymma"],
    ["EVENTUELL", "möjlig"],
    ["EVIDENT", "klar, uppenbart sann"],
    ["EVIG", "oändlig i tid"],
    ["EVOLUTION", "utveckling"],
    ["EXAKT", "precis"],
    ["EXALTERAD", "överspänd"],
    ["EXAMINERA", "pröva kunskaper"],
    ["EXCELLENT", "ytterst bra"],
    ["EXCENTRISK", "originell, udda"],
    ["EXEKUTIV", "verkställande"],
    ["EXEMPLARISK", "föredömlig"],
    ["EXIL", "landsflykt"],
    ["EXISTENS", "tillvaro"],
    ["EXKLUDERA", "stänga ute"],
    ["EXKLUSIV", "utvald, förnäm"],
    ["EXKURSION", "studieresa, utflykt"],
    ["EXOTISK", "främmande, ovanlig"],
    ["EXPANDERA", "utvidga"],
    ["EXPEDITION", "forskningsresa"],
    ["EXPERIMENT", "försök"],
    ["EXPERTIS", "sakkunskap"],
    ["EXPLICIT", "uttrycklig, tydlig"],
    ["EXPLOATERA", "utnyttja"],
    ["EXPLODERA", "spricka"],
    ["EXPONERA", "visa upp, blottställa"],
    ["EXPORT", "utförsel"],
    ["EXPRESS", "snabb"],
    ["EXPRESSIV", "uttrycksfull"],
    ["EXTAS", "hänryckning"],
    ["EXTENSIV", "omfattande, utbredd"],
    ["EXTERN", "yttre"],
    ["EXTREM", "ytterlig"],
    ["EXTROVERT", "utåtriktad"],
    ["FABRICERA", "tillverka, hitta på"],
    ["FABULÖS", "sagolik"],
    ["FACKMAN", "expert"],
    ["FADD", "smaklös, tråkig"],
    ["FAGER", "vacker"],
    ["FALANG", "flygel inom parti"],
    ["FALLENHET", "begåvning, anlag"],
    ["FALLFÄRDIG", "nära att rasa ihop"],
    ["FALSARIUM", "förfalskning"],
    ["FALSK", "oäkta"],
    ["FANATISK", "besatt, blint hängiven"],
    ["FANTASILÖS", "idéfattig"],
    ["FANTASTISK", "underbar"],
    ["FARHÅGA", "fruktan"],
    ["FARSARTAD", "löjlig, absurd"],
    ["FASAD", "framsida"],
    ["FASCINERA", "fängsla"],
    ["FASTHET", "beslutsamhet"],
    ["FASTSLÅ", "konstatera"],
    ["FATAL", "ödesdiger"],
    ["FATALIST", "den som tror på ödet"],
    ["FATTIG", "medellös"],
    ["FATTNING", "självbehärskning"],
    ["FAVORISERA", "gynna"],
    ["FAVORIT", "älsklingsval"],
    ["FAVÖR", "fördel"],
    ["FEBRIL", "feberaktig, jäktad"],
    ["FEG", "rädd, modlös"],
    ["FEJD", "strid, konflikt"],
    ["FELBAR", "som kan göra fel"],
    ["FENOMEN", "företeelse"],
    ["FENOMENAL", "häpnadsväckande bra"],
    ["FESTLIG", "glad, rolig"],
    ["FIASKO", "misslyckande"],
    ["FIENDSKAP", "fientlighet"],
    ["FIENTLIG", "som en fiende"],
    ["FIKTIV", "påhittad, låtsad"],
    ["FILANTROP", "människovän, välgörare"],
    ["FILANTROPI", "välgörenhet"],
    ["FINANSIERA", "bekosta"],
    ["FINESS", "förfining, knep"],
    ["FINKÄNSLIG", "hänsynsfull i känsliga lägen"],
    ["FIXERAD", "låst, besatt"],
    ["FLAGRANT", "skriande, uppenbar"],
    ["FLAMMA", "låga"],
    ["FLAMMANDE", "brinnande, glödande"],
    ["FLANERA", "promenera, driva omkring"],
    ["FLAT", "förlägen, snopen"],
    ["FLEGMATISK", "trög, oberörd"],
    ["FLEXIBEL", "böjlig, anpassningsbar"],
    ["FLINK", "snabb och händig"],
    ["FLORERA", "blomstra, frodas"],
    ["FLOSKEL", "innehållslöst talesätt"],
    ["FLUKTUERA", "växla, svänga"],
    ["FLYKTIG", "som snabbt försvinner"],
    ["FLÄCKFRI", "obefläckad"],
    ["FLÄRD", "fåfäng lyx"],
    ["FOBI", "sjuklig rädsla"],
    ["FOGLIG", "medgörlig, lydig"],
    ["FOKUS", "brännpunkt"],
    ["FOLKLIG", "populär, enkel"],
    ["FORCERA", "påskynda, tvinga fram"],
    ["FORMALITET", "formsak"],
    ["FORMATIV", "formande"],
    ["FORMELL", "officiell, stel"],
    ["FORMIDABEL", "väldig, imponerande"],
    ["FORMULERA", "uttrycka i ord"],
    ["FORSKA", "undersöka vetenskapligt"],
    ["FORTLÖPANDE", "löpande, pågående"],
    ["FRAGMENT", "brottstycke"],
    ["FRAKTION", "falang, grupp"],
    ["FRAMFART", "härjningar, beteende"],
    ["FRAMFUSIG", "påträngande"],
    ["FRAMGÅNGSRIK", "lyckosam"],
    ["FRAMSTEG", "steg framåt"],
    ["FRAMSYNT", "förutseende"],
    ["FRAMTRÄDANDE", "iögonfallande, ledande"],
    ["FRAPPANT", "slående, överraskande"],
    ["FRAPPERAD", "förvånad, slagen"],
    ["FRENETISK", "ursinnig, vild"],
    ["FRESTELSE", "lockelse"],
    ["FRIDSAM", "fredlig"],
    ["FRIKOSTIG", "givmild"],
    ["FRIKÄNNA", "förklara oskyldig"],
    ["FRIVOL", "lättsinnig"],
    ["FROMMA", "komma till nytta för"],
    ["FRUGAL", "enkel, sparsam"],
    ["FRUKTBAR", "givande, bördig"],
    ["FRÅNSTÖTANDE", "motbjudande"],
    ["FRÄCK", "djärv på ett ohyfsat sätt"],
    ["FRÄMLING", "okänd person"],
    ["FRÄSCH", "sval, ny och ren"],
    ["FRÖJD", "glädje"],
    ["FULLMAKT", "behörighet"],
    ["FULLSTÄNDIG", "komplett"],
    ["FULLÄNDAD", "fullkomlig"],
    ["FUMLA", "famla"],
    ["FUMLIG", "klumpig, tafatt"],
    ["FUNDAMENTAL", "väsentlig, i grunden avgörande"],
    ["FUNDERSAM", "tankfull"],
    ["FUNKTIONELL", "ändamålsenlig"],
    ["FYND", "upptäckt"],
    ["FÅNIG", "dum, barnslig"],
    ["FÄRDIGHET", "skicklighet"],
    ["FÄRGSTARK", "livfull"],
    ["FÖRAKT", "ringaktning"],
    ["FÖRBEHÅLL", "reservation"],
    ["FÖRBISE", "missa"],
    ["FÖRBLÅST", "dum, virrig"],
    ["FÖRBRUKA", "använda upp"],
    ["FÖRBRYLLAD", "förvirrad"],
    ["FÖRDEL", "gynnsam omständighet"],
    ["FÖRDOLD", "gömd"],
    ["FÖRDOM", "förutfattad mening"],
    ["FÖRDRAGSAM", "tålmodig mot andra"],
    ["FÖRDRÖJA", "försena"],
    ["FÖREBYGGA", "förhindra"],
    ["FÖREDÖME", "gott exempel"],
    ["FÖRENING", "sammanslutning"],
    ["FÖRENKLA", "göra enklare"],
    ["FÖRESKRIFT", "bindande regel"],
    ["FÖRFALL", "nedgång"],
    ["FÖRFLUTEN", "förgången"],
    ["FÖRFÄKTA", "försvara, hävda"],
    ["FÖRFÄRAD", "förskräckt"],
    ["FÖRFÖRISK", "förledande"],
    ["FÖRGIFTA", "förstöra, göra giftig"],
    ["FÖRGÄNGLIG", "dödlig, kortlivad"],
    ["FÖRHOPPNING", "förväntan"],
    ["FÖRKASTA", "avvisa"],
    ["FÖRKLARING", "utredning, orsak"],
    ["FÖRKLENA", "tala nedsättande om"],
    ["FÖRLIKA", "försona"],
    ["FÖRLOPP", "händelseutveckling"],
    ["FÖRLUST", "minskning, nederlag"],
    ["FÖRLÄGEN", "generad"],
    ["FÖRMANING", "varnande råd"],
    ["FÖRMEDLA", "överföra"],
    ["FÖRMILDRANDE", "lindrande"],
    ["FÖRMODAN", "gissning"],
    ["FÖRMÅGA", "kapacitet"],
    ["FÖRMÄTEN", "övermodig, fräck"],
    ["FÖRNEKA", "bestrida"],
    ["FÖRNUFT", "omdöme, klokhet"],
    ["FÖRNUMSTIG", "lillgammal, beskäftig"],
    ["FÖRNYA", "modernisera"],
    ["FÖRNÄM", "fin, aristokratisk"],
    ["FÖRNÖJSAM", "lättillfredsställd"],
    ["FÖRORSAKA", "vålla"],
    ["FÖRPASSA", "skicka iväg"],
    ["FÖRPLIKTELSE", "åtagande"],
    ["FÖRSAKA", "avstå från"],
    ["FÖRSAMLING", "menighet"],
    ["FÖRSKANSA", "befästa, skydda sig bakom"],
    ["FÖRSKONA", "skona"],
    ["FÖRSKÖNA", "göra vackrare"],
    ["FÖRSMÅ", "avvisa med förakt"],
    ["FÖRSONLIG", "villig att förlåta"],
    ["FÖRSPRÅNG", "försteg"],
    ["FÖRSTRÖDD", "tankspridd"],
    ["FÖRSTUCKEN", "dold, hemlig"],
    ["FÖRSUMLIG", "slarvig, pliktförgätande"],
    ["FÖRSUMMELSE", "underlåtenhet"],
    ["FÖRSVINNANDE", "nästan obefintlig"],
    ["FÖRSYNT", "hänsynsfull och blyg"],
    ["FÖRTAL", "smädelse"],
    ["FÖRTECKNING", "lista"],
    ["FÖRTJUSANDE", "bedårande"],
    ["FÖRTJÄNST", "merit, vinst"],
    ["FÖRTROLIG", "hemlig, personlig"],
    ["FÖRTRYTSAM", "förargad, sur"],
    ["FÖRTRÖSTAN", "tillit"],
    ["FÖRUTSÄGBAR", "väntad"],
    ["FÖRVARA", "ha i förvar"],
    ["FÖRVIRRING", "oreda"],
    ["FÖRVISA", "utvisa ur landet"],
    ["FÖRVISSA", "säkerställa"],
    ["FÖRVÅNANSVÄRD", "häpnadsväckande"],
    ["FÖRÄDLA", "förbättra, förfina"],
    ["FÖRÖDANDE", "katastrofal"],
    ["GAGNA", "vara till nytta"],
    ["GALANT", "artig, ridderlig"],
    ["GAMMALMODIG", "omodern"],
    ["GARANT", "borgesman"],
    ["GEDIGEN", "grundlig, solid"],
    ["GEMEN", "nedrig"],
    ["GEMENSKAP", "samhörighet"],
    ["GEMYTLIG", "trivsam, godmodig"],
    ["GENANT", "pinsam"],
    ["GENERALISERA", "dra allmänna slutsatser"],
    ["GENERATION", "släktled"],
    ["GENERÖS", "storsint, frikostig"],
    ["GENIAL", "briljant"],
    ["GENOMFÖRBAR", "möjlig att utföra"],
    ["GENOMSKÅDA", "avslöja"],
    ["GENOMTÄNKT", "välplanerad"],
    ["GENSTÖRTIG", "trotsig, motsträvig"],
    ["GENUIN", "äkta"],
    ["GEST", "åtbörd"],
    ["GESTALTA", "forma, framställa"],
    ["GIFTIG", "elak, toxisk"],
    ["GIRIG", "lysten efter pengar"],
    ["GISSEL", "plåga"],
    ["GLITTRANDE", "gnistrande"],
    ["GLOBAL", "världsomfattande"],
    ["GLORIFIERA", "förhärliga"],
    ["GLÖMSK", "som lätt glömmer"],
    ["GODHJÄRTAD", "snäll"],
    ["GODKÄNNANDE", "tillstånd"],
    ["GODTYCKLIG", "nyckfull, utan regler"],
    ["GRAMSE", "avundsjuk, missnöjd"],
    ["GRANDIOS", "storslagen"],
    ["GRANNLAGA", "ömtålig, känslig"],
    ["GRANSKA", "undersöka"],
    ["GRATIFIKATION", "extra ersättning"],
    ["GRAVALLVARLIG", "mycket allvarlig"],
    ["GRAVERANDE", "belastande, allvarlig"],
    ["GRAVITET", "allvar, värdighet"],
    ["GROLL", "agg"],
    ["GROTESK", "vanskapt, absurd"],
    ["GRUBBLA", "älta"],
    ["GRUMLIG", "oklar, ogenomskinlig"],
    ["GRUNDLIG", "genomgående noggrann"],
    ["GRYM", "hjärtlös"],
    ["GRÄNSLÖS", "utan gränser"],
    ["GRÄSROT", "vanlig medlem"],
    ["GUDOMLIG", "himmelsk"],
    ["GYCKEL", "skämt, skoj"],
    ["GYNNSAM", "fördelaktig"],
    ["GÅTA", "mysterium"],
    ["GÅTFULL", "hemlighetsfull"],
    ["GÄCKA", "narra, lura"],
    ["GÄLD", "skuld"],
    ["GÄNGSE", "vanlig, bruklig"],
    ["GÄSTFRI", "välkomnande"],
    ["HABIL", "skicklig"],
    ["HALSSTARRIG", "omedgörlig"],
    ["HALVHJÄRTAD", "ljum, oengagerad"],
    ["HANDFALLEN", "rådlös"],
    ["HANDGRIPLIG", "påtaglig, fysisk"],
    ["HARM", "förbittring"],
    ["HARMONI", "samklang"],
    ["HARMSEN", "stött, förargad"],
    ["HASARD", "slump, tur"],
    ["HASTIG", "snabb och plötslig"],
    ["HATISK", "fylld av hat"],
    ["HAVERI", "sammanbrott, olycka"],
    ["HEDERSAM", "hedervärd"],
    ["HEDONISM", "njutningslära"],
    ["HEDONIST", "njutningsmänniska"],
    ["HEDRA", "ära"],
    ["HEGEMONI", "överhöghet, dominans"],
    ["HEKTISK", "jäktad"],
    ["HELHJÄRTAD", "helt engagerad"],
    ["HELIG", "okränkbar, gudomlig"],
    ["HEMLIGHÅLLA", "dölja"],
    ["HEMSK", "förfärlig"],
    ["HERMETISK", "lufttät"],
    ["HEROISK", "hjältemodig"],
    ["HERRAVÄLDE", "makt, kontroll"],
    ["HETEROGEN", "olikartad, oenhetlig"],
    ["HETSIG", "häftig, lättretad"],
    ["HIERARKI", "rangordning"],
    ["HISNANDE", "svindlande"],
    ["HISTORISK", "som rör det förflutna"],
    ["HJÄLPLÖS", "försvarslös"],
    ["HOMOGEN", "likartad, enhetlig"],
    ["HOPPFULL", "förhoppningsfull"],
    ["HORISONTELL", "vågrät"],
    ["HOVSAM", "hänsynsfull och måttlig"],
    ["HUGSVALA", "trösta"],
    ["HUMAN", "mild, människovänlig"],
    ["HUMANISM", "tro på människovärdet"],
    ["HUMANITÄR", "människovänlig"],
    ["HUMÖR", "sinnesstämning"],
    ["HUSHÅLLA", "spara"],
    ["HUTLÖS", "skamlös, orimlig"],
    ["HYBRID", "korsning"],
    ["HYBRIS", "övermod"],
    ["HYCKLA", "låtsas, förställa sig"],
    ["HYLLA", "ära, prisa"],
    ["HYLLNING", "ära, lovprisning"],
    ["HYPOTES", "antagande"],
    ["HYSTERISK", "okontrollerat upprörd"],
    ["HÅGLÖS", "utan lust, slö"],
    ["HÅLLBAR", "tålig, som håller länge"],
    ["HÅNA", "förlöjliga"],
    ["HÅRDNACKAD", "envis, orubblig"],
    ["HÄFTIG", "intensiv"],
    ["HÄMMA", "hindra, bromsa"],
    ["HÄRDAD", "van vid påfrestningar"],
    ["HÄRJA", "ödelägga"],
    ["HÄRLEDA", "spåra ursprunget till"],
    ["HÄVDA", "påstå"],
    ["HÄVDVUNNEN", "traditionell, sedan länge rådande"],
    ["HÖGAKTNING", "respekt"],
    ["HÖGDRAGEN", "överlägsen, dryg"],
    ["HÖGFÄRDIG", "som tror sig vara bättre"],
    ["HÖGLJUDD", "bullrig"],
    ["HÖGTIDLIG", "ceremoniell"],
    ["HÖVISK", "artig, belevad"],
    ["IDEAL", "fullkomlig förebild"],
    ["IDEALISERA", "försköna"],
    ["IDEALISTISK", "som styrs av ideal"],
    ["IDENTISK", "likadan"],
    ["IDENTITET", "vem man är"],
    ["IDIOM", "fast uttryck"],
    ["IDOG", "flitig, ihärdig"],
    ["IDOL", "förebild, avgud"],
    ["IDYLL", "fridfull plats eller tillvaro"],
    ["IDYLLISK", "fridfull"],
    ["IGNORERA", "strunta i"],
    ["IHÄRDIG", "uthållig"],
    ["IKONISK", "symbolisk, välkänd"],
    ["ILLASINNAD", "som vill illa"],
    ["ILLOJAL", "trolös"],
    ["ILLUSION", "synvilla, inbillning"],
    ["ILLUSTER", "berömd, framstående"],
    ["ILLUSTRERA", "åskådliggöra"],
    ["IMITERA", "härma"],
    ["IMMANENT", "som finns inuti"],
    ["IMMATERIELL", "icke-materiell, andlig"],
    ["IMMIGRERA", "invandra"],
    ["IMMINENT", "överhängande"],
    ["IMMUN", "motståndskraftig"],
    ["IMPERIALISM", "stormaktspolitik"],
    ["IMPERIUM", "välde"],
    ["IMPERTINENT", "oförskämd"],
    ["IMPLEMENTERA", "genomföra, införa"],
    ["IMPLICERA", "innebära"],
    ["IMPLICIT", "underförstådd"],
    ["IMPONERA", "göra intryck"],
    ["IMPOPULÄR", "ogillad"],
    ["IMPOTENT", "maktlös"],
    ["IMPULS", "ingivelse"],
    ["IMPULSIV", "hastig, obetänksam"],
    ["INADEKVAT", "otillräcklig"],
    ["INAKTIV", "ej i gång, vilande"],
    ["INBILSK", "som tror sig vara förmer"],
    ["INBÖRDES", "sinsemellan"],
    ["INDIFFERENT", "oengagerad, neutral"],
    ["INDIGNERAD", "upprörd, harmsen"],
    ["INDIREKT", "medelbar, antydd"],
    ["INDISKRET", "som inte kan hålla tyst"],
    ["INDIVIDUELL", "personlig"],
    ["INDOKTRINERA", "påtvinga åsikter"],
    ["INDOLENT", "håglös, loj"],
    ["INDUCERA", "framkalla"],
    ["INEFFEKTIV", "verkningslös"],
    ["INFALL", "plötsligt påhitt"],
    ["INFAM", "nedrig, skändlig"],
    ["INFEKTERAD", "bitter, låst (om konflikt)"],
    ["INFERIÖR", "underlägsen"],
    ["INFLATION", "penningvärdesförsämring"],
    ["INFLUERA", "påverka"],
    ["INFLYTELSERIK", "mäktig"],
    ["INFORMELL", "otvungen, avspänd"],
    ["INGIVELSE", "plötslig idé"],
    ["INGÅENDE", "detaljerad"],
    ["INHERENT", "inneboende"],
    ["INHUMAN", "omänsklig"],
    ["INITIATIV", "första steg"],
    ["INITIERAD", "insatt"],
    ["INKARNATION", "förkroppsligat väsen"],
    ["INKOGNITO", "under annat namn"],
    ["INKOHERENT", "osammanhängande"],
    ["INKOMPETENT", "oduglig"],
    ["INKOMST", "intäkt"],
    ["INKONSEKVENT", "ologisk, ombytlig"],
    ["INKRÄKTARE", "objuden gäst"],
    ["INLEDNING", "början"],
    ["INNEBÖRD", "betydelse"],
    ["INNEHAVARE", "ägare"],
    ["INNERLIG", "varm, uppriktig"],
    ["INNOVATION", "nyskapelse"],
    ["INNOVATIV", "nyskapande"],
    ["INSATS", "bidrag, engagemang"],
    ["INSIKT", "förståelse"],
    ["INSINUANT", "antydande"],
    ["INSINUERA", "antyda, låta påskina"],
    ["INSISTERA", "envist hävda"],
    ["INSOLVENT", "betalningsoförmögen"],
    ["INSPEKTERA", "besiktiga"],
    ["INSPEKTION", "granskning"],
    ["INSPIRERA", "ge idéer, entusiasmera"],
    ["INSTABIL", "ostadig"],
    ["INSTINKT", "medfödd drift"],
    ["INSTITUTION", "inrättning"],
    ["INSTRUKTIV", "lärorik"],
    ["INTAKT", "orörd, hel"],
    ["INTEGRERA", "sammanfoga till en helhet"],
    ["INTEGRITET", "okränkbarhet, hederlighet"],
    ["INTELLEKT", "förstånd"],
    ["INTENSIV", "stark, koncentrerad"],
    ["INTENTION", "avsikt"],
    ["INTERAKTION", "samspel"],
    ["INTERN", "inre"],
    ["INTERVENERA", "ingripa"],
    ["INTIM", "förtrolig"],
    ["INTOLERANT", "ofördragsam"],
    ["INTRIG", "ränker, komplott"],
    ["INTRIKAT", "snårig, krånglig"],
    ["INTROVERT", "inåtvänd"],
    ["INTRÄNGANDE", "genomträngande, grundlig"],
    ["INTUITIV", "omedelbart förstående"],
    ["INVASION", "intrång, angrepp"],
    ["INVECKLAD", "trasslig, svårbegriplig"],
    ["INVENTERA", "förteckna"],
    ["INVÄNDNING", "motargument"],
    ["INVÄNTA", "vänta på"],
    ["IRONI", "förtäckt spydighet"],
    ["IRONISK", "som menar motsatsen"],
    ["IRRATIONELL", "orimlig, oförnuftig"],
    ["IRRELEVANT", "ovidkommande"],
    ["IRREVERSIBEL", "oåterkallelig"],
    ["IRRITERAD", "retad, störd"],
    ["ISOLERAD", "avskild"],
    ["JARGONG", "gruppspråk, slang"],
    ["JOVIALISK", "gemytlig, godmodig"],
    ["JUBILEUM", "högtidlig årsdag"],
    ["JUBLA", "glädjas högljutt"],
    ["JUSTERA", "rätta till"],
    ["JÄKTA", "stressa"],
    ["JÄMBÖRDIG", "likställd"],
    ["JÄMNMOD", "sinnesro"],
    ["JÄMSTÄLLD", "likaberättigad"],
    ["KALABALIK", "tumult, oordning"],
    ["KALAMITET", "olycka, katastrof"],
    ["KALKYLERA", "beräkna"],
    ["KALLHAMRAD", "beräknande, känslokall"],
    ["KAMOUFLERA", "dölja, maskera"],
    ["KAMP", "strid"],
    ["KANALISERA", "leda i en viss riktning"],
    ["KAOS", "total oordning"],
    ["KAPITULATION", "underkastelse"],
    ["KAPITULERA", "ge upp"],
    ["KAPRIS", "nyckfullt påhitt"],
    ["KARAKTERISTISK", "typisk"],
    ["KARAKTÄR", "personlighet"],
    ["KARG", "mager, ofruktbar"],
    ["KARIKATYR", "nidbild"],
    ["KARIKERA", "förlöjliga genom överdrift"],
    ["KARISMATISK", "utstrålande"],
    ["KARRIÄR", "yrkesbana"],
    ["KATALYSATOR", "pådrivande faktor"],
    ["KATASTROF", "olycka"],
    ["KATEGORI", "grupp, klass"],
    ["KATEGORISK", "bestämd, ovillkorlig"],
    ["KAUSAL", "orsaksbestämd"],
    ["KAVALJER", "bordsherre"],
    ["KAVAT", "modig, kaxig"],
    ["KLAGAN", "jämmer"],
    ["KLANDERFRI", "oklanderlig, utan fel"],
    ["KLANDRA", "kritisera, anmärka på"],
    ["KLARGÖRA", "förtydliga"],
    ["KLARHET", "tydlighet"],
    ["KLARSYNT", "skarpsinnig"],
    ["KLASSIFICERA", "indela"],
    ["KLASSISK", "tidlös"],
    ["KLENTROGEN", "som har svårt att tro"],
    ["KLOK", "förståndig"],
    ["KLYFTIG", "fyndig, påhittig"],
    ["KLÅFINGRIG", "som inte kan låta bli"],
    ["KNAPPHET", "brist"],
    ["KNAPPHÄNDIG", "kortfattad, otillräcklig"],
    ["KOALITION", "förbund, samverkan"],
    ["KOGNITIV", "som rör tänkandet"],
    ["KOHERENT", "sammanhängande"],
    ["KOKETT", "flirtig"],
    ["KOLLAPS", "sammanbrott"],
    ["KOLLEGIAL", "kamratlig"],
    ["KOLLEKTIV", "gemensam"],
    ["KOMMENTERA", "yttra sig om"],
    ["KOMMERSIELL", "affärsmässig"],
    ["KOMPAKT", "tät"],
    ["KOMPANJON", "delägare"],
    ["KOMPATIBEL", "förenlig"],
    ["KOMPENSATION", "ersättning"],
    ["KOMPENSERA", "ersätta, gottgöra"],
    ["KOMPETENS", "kunnighet"],
    ["KOMPETENT", "kunnig, behörig"],
    ["KOMPLEMENT", "komplettering"],
    ["KOMPLETTERA", "fylla ut"],
    ["KOMPLEX", "sammansatt, invecklad"],
    ["KOMPLICERA", "försvåra"],
    ["KOMPLIMANG", "berömmande ord"],
    ["KOMPROMISS", "uppgörelse där båda ger efter"],
    ["KONCIPIERA", "utforma, formulera"],
    ["KONCIS", "kortfattad"],
    ["KONDITION", "fysisk form"],
    ["KONDOLERA", "beklaga sorg"],
    ["KONFERENS", "sammankomst"],
    ["KONFIDENTIELL", "sekretessbelagd"],
    ["KONFISKERA", "beslagta"],
    ["KONFLIKT", "motsättning"],
    ["KONFORM", "likformig, anpassad"],
    ["KONFRONTERA", "ställa öga mot öga"],
    ["KONFUNDERAD", "förvånad och förvirrad"],
    ["KONFYS", "förvirrad, virrig"],
    ["KONGRUENT", "överensstämmande"],
    ["KONKLUSION", "slutsats"],
    ["KONKRET", "påtaglig, verklig"],
    ["KONKRETISERA", "förtydliga med exempel"],
    ["KONSEKVENS", "följd"],
    ["KONSEKVENT", "principfast"],
    ["KONSENSUS", "enighet"],
    ["KONSERVATIV", "traditionsbunden"],
    ["KONSERVERA", "bevara, lagra"],
    ["KONSOLIDERA", "göra stabil, trygga"],
    ["KONSPIRATION", "sammansvärjning"],
    ["KONSTANT", "ständig"],
    ["KONSTELLATION", "gruppering"],
    ["KONSTRUERA", "bygga"],
    ["KONSTRUKTIV", "uppbyggande"],
    ["KONSULTERA", "rådfråga"],
    ["KONSUMERA", "använda, äta"],
    ["KONTEMPLATION", "begrundan"],
    ["KONTEXT", "sammanhang"],
    ["KONTINUERLIG", "oavbruten"],
    ["KONTRAST", "tydlig skillnad"],
    ["KONTROLL", "tillsyn"],
    ["KONTROVERS", "stridsfråga"],
    ["KONTROVERSIELL", "omstridd"],
    ["KONVENANS", "etikett, god ton"],
    ["KONVENTION", "överenskommelse, praxis"],
    ["KONVENTIONELL", "traditionell, vedertagen"],
    ["KONVERGERA", "närma sig varandra"],
    ["KONVERSATION", "artigt småprat"],
    ["KOPIÖS", "riklig"],
    ["KORRELATION", "samband"],
    ["KORRESPONDERA", "brevväxla, motsvara"],
    ["KORRIGERA", "rätta"],
    ["KORRUMPERA", "muta, fördärva"],
    ["KORRUPT", "mutbar"],
    ["KOSMOPOLIT", "världsmedborgare"],
    ["KRAMPAKTIG", "forcerad, spänd"],
    ["KRASS", "materialistisk, hård"],
    ["KRAVALL", "upplopp"],
    ["KRAVLÖS", "utan krav"],
    ["KREATIV", "skapande"],
    ["KRIS", "svår situation"],
    ["KRISTALLKLAR", "fullkomligt tydlig"],
    ["KRITERIUM", "kännetecken, villkor"],
    ["KRITIK", "klander"],
    ["KRITISK", "avgörande, granskande"],
    ["KRUX", "svårighet, problem"],
    ["KRYPTISK", "dunkel, svårtydd"],
    ["KRÅNGLIG", "invecklad och bökig"],
    ["KRÄSEN", "nogräknad"],
    ["KULINARISK", "som rör matlagning"],
    ["KULMEN", "höjdpunkt"],
    ["KULMINERA", "nå höjdpunkten"],
    ["KULTIVERAD", "bildad"],
    ["KUMULATIV", "som växer genom att läggas till"],
    ["KUNNIG", "insatt, lärd"],
    ["KURAGE", "mod"],
    ["KURIÖS", "märklig, lustig"],
    ["KUSLIG", "obehaglig, spöklik"],
    ["KUTYM", "sed, bruk"],
    ["KVALIFICERAD", "kompetent"],
    ["KVALITATIV", "som rör egenskaper"],
    ["KVANTITATIV", "som rör mängd"],
    ["KVARLEVA", "rest"],
    ["KVERULANT", "gnällspik"],
    ["KVICK", "snabbtänkt, rolig"],
    ["KVINTESSENS", "det väsentligaste"],
    ["KVÄVA", "undertrycka"],
    ["KYLIG", "sval, reserverad"],
    ["KYSK", "oskuldsfull"],
    ["KÄCK", "modig, pigg"],
    ["KÄNSLIG", "ömtålig"],
    ["KÄRNFULL", "slagkraftig"],
    ["KÄRV", "hård, ovänlig"],
    ["LABIL", "ostadig, instabil"],
    ["LABYRINT", "irrgång"],
    ["LAGBUNDEN", "regelbunden"],
    ["LAGSTIFTNING", "lagar"],
    ["LAKONISK", "kort och torr"],
    ["LAMENTABEL", "beklaglig"],
    ["LAMSLAGEN", "förlamad"],
    ["LANDVINNING", "erövring, genombrott"],
    ["LANSERA", "introducera"],
    ["LANTLIG", "rural"],
    ["LAPIDARISK", "kort och kärnfull"],
    ["LAPPRI", "struntsak"],
    ["LARMANDE", "oroväckande"],
    ["LAST", "synd, dålig vana"],
    ["LATENT", "dold, slumrande"],
    ["LATHET", "slöhet"],
    ["LATITUD", "spelrum, frihet"],
    ["LEDA", "tristess"],
    ["LEDSAM", "tråkig"],
    ["LEGAL", "laglig"],
    ["LEGEND", "sägen"],
    ["LEGIO", "mycket vanlig"],
    ["LEGITIM", "rättmätig, laglig"],
    ["LEGITIMERA", "göra giltig"],
    ["LEKFULL", "skämtsam"],
    ["LETARGI", "slöhet, dvala"],
    ["LEVERNE", "sätt att leva"],
    ["LIBERAL", "frisinnad"],
    ["LIDANDE", "smärta, nöd"],
    ["LIDERLIG", "utsvävande"],
    ["LIKGILTIG", "oberörd"],
    ["LIKNÖJD", "obekymrad"],
    ["LIKTYDIG", "synonym"],
    ["LIKVÄRDIG", "lika mycket värd"],
    ["LISMA", "fjäska, smickra"],
    ["LITANIA", "klagovisa"],
    ["LITTERÄR", "som rör litteratur"],
    ["LIVAKTIG", "full av energi"],
    ["LJUMMEN", "halvvarm, oengagerad"],
    ["LOGIK", "tankeregler"],
    ["LOGISK", "följdriktig"],
    ["LOJ", "slö"],
    ["LOJAL", "trogen mot någon"],
    ["LOJALITET", "trohet"],
    ["LOMHÖRD", "som hör dåligt"],
    ["LOVORD", "lov, pris"],
    ["LUKRATIV", "lönsam"],
    ["LUKULLISK", "överdådig om mat"],
    ["LUMPEN", "tarvlig"],
    ["LUSTFYLLD", "njutbar"],
    ["LUXUÖS", "lyxig"],
    ["LYDNAD", "att lyda"],
    ["LYHÖRD", "uppmärksam, känslig"],
    ["LYRISK", "känslofull, hänförd"],
    ["LYSANDE", "strålande, utmärkt"],
    ["LÅNGRANDIG", "utdragen, tråkig"],
    ["LÅNGSINT", "som länge bär på agg"],
    ["LÄGLIG", "som kommer vid rätt tidpunkt"],
    ["LÄNGTAN", "saknad"],
    ["LÄRD", "kunnig och beläst"],
    ["LÄTTSINNIG", "slarvig, ansvarslös"],
    ["LÖFTE", "utfästelse"],
    ["LÖJEVÄCKANDE", "löjlig"],
    ["LÖSAKTIG", "lättfärdig"],
    ["MAGNAT", "storföretagare"],
    ["MAGNIFIK", "storartad"],
    ["MAJESTÄTISK", "upphöjd, vördnadsbjudande"],
    ["MAJORITET", "flertal"],
    ["MAKABER", "kuslig, hemsk"],
    ["MAKTLYSTEN", "härsklysten"],
    ["MALLIG", "stöddig"],
    ["MANDAT", "uppdrag, befogenhet"],
    ["MANIFEST", "tydlig, påtaglig"],
    ["MANIFESTERA", "visa, uttrycka"],
    ["MANIPULERA", "påverka i smyg"],
    ["MANÖVRERA", "styra"],
    ["MARGINAL", "säkerhetsavstånd, överskott"],
    ["MARGINALISERA", "tränga undan"],
    ["MARGINELL", "obetydlig, liten"],
    ["MARKANT", "märkbar, framträdande"],
    ["MARTYR", "den som lider för sin sak"],
    ["MASKERAD", "förklädd"],
    ["MASKULIN", "manlig"],
    ["MASSIV", "kompakt, omfattande"],
    ["MATERIALISM", "tro på det materiella"],
    ["MATERIALISTISK", "inriktad på ägodelar"],
    ["MATERIELL", "fysisk"],
    ["MAXIMAL", "största möjliga"],
    ["MEDBORGARE", "invånare"],
    ["MEDGIVANDE", "samtycke"],
    ["MEDGÖRLIG", "foglig, samarbetsvillig"],
    ["MEDIOKER", "medelmåttig"],
    ["MEDITERA", "försjunka i tankar"],
    ["MEDVERKA", "delta"],
    ["MEDVETEN", "insiktsfull"],
    ["MEKANISK", "maskinmässig"],
    ["MEKANISM", "funktion"],
    ["MELANKOLI", "vemod"],
    ["MELANKOLISK", "svårmodig"],
    ["MELODRAMATISK", "teatralisk"],
    ["MENINGSFULL", "givande"],
    ["MENLÖS", "oskyldig, harmlös"],
    ["MENTALITET", "tänkesätt"],
    ["MERITERAD", "kvalificerad"],
    ["METAFOR", "bildligt uttryck"],
    ["METODIK", "arbetssätt"],
    ["MIKROSKOPISK", "ytterst liten"],
    ["MILDRA", "lindra"],
    ["MILITANT", "stridslysten"],
    ["MINDERVÄRDIG", "sämre"],
    ["MINIATYR", "förminskad kopia"],
    ["MINIMAL", "mycket liten"],
    ["MINUTIÖS", "ytterst noggrann"],
    ["MISANTROP", "människohatare"],
    ["MISSBRUK", "felaktig användning"],
    ["MISSFÖRSTÅND", "feltolkning"],
    ["MISSGYNNA", "behandla orättvist"],
    ["MISSKÖTA", "vanvårda"],
    ["MISSLYNT", "missnöjd, sur"],
    ["MISSMODIG", "modfälld"],
    ["MISSTRO", "misstänksamhet"],
    ["MISSTÄNKSAM", "misstrogen"],
    ["MOBIL", "rörlig"],
    ["MOBILISERA", "samla, uppbåda"],
    ["MODERAT", "måttlig"],
    ["MODERN", "nutida"],
    ["MODEST", "blygsam, återhållsam"],
    ["MODIFIERA", "ändra något"],
    ["MONOLOG", "enmansprat"],
    ["MONOPOL", "ensamrätt"],
    ["MONOTON", "enformig"],
    ["MONUMENTAL", "kolossal"],
    ["MORALISERA", "predika moral"],
    ["MORALISK", "sedlig"],
    ["MORBID", "sjuklig, dyster"],
    ["MOTIV", "drivkraft, skäl"],
    ["MOTIVERA", "förklara skälen, sporra"],
    ["MOTSTRÄVIG", "ovillig"],
    ["MOTVERKA", "arbeta emot"],
    ["MUNDÄN", "världslig"],
    ["MUNTER", "glad, uppsluppen"],
    ["MYLLRANDE", "vimlande"],
    ["MYNDIG", "vuxen enligt lag"],
    ["MYSTISK", "oförklarlig"],
    ["MYTOMAN", "tvångsmässig lögnare"],
    ["MÅLMEDVETEN", "inriktad på ett mål"],
    ["MÅNGTYDIG", "som kan tolkas på flera sätt"],
    ["MÄKTIG", "stark, inflytelserik"],
    ["MÄRKLIG", "förvånande, udda"],
    ["MÖDOSAM", "besvärlig"],
    ["NAIV", "godtrogen"],
    ["NARRATIV", "berättelse"],
    ["NATURLIG", "äkta, okonstlad"],
    ["NEDBRYTANDE", "som tär på krafterna"],
    ["NEDLÅTANDE", "förmyndaraktigt nedsättande"],
    ["NEDSTÄMD", "ledsen"],
    ["NEDVÄRDERA", "sänka värdet av"],
    ["NEGATION", "förnekande"],
    ["NEGATIV", "nekande, ogynnsam"],
    ["NEGLIGERA", "försumma, ignorera"],
    ["NEJD", "trakt, bygd"],
    ["NEPOTISM", "gynnande av släktingar"],
    ["NERVÖS", "spänd, uppjagad"],
    ["NEUTRAL", "opartisk"],
    ["NEUTRALISERA", "oskadliggöra"],
    ["NIDING", "skurk, fegis"],
    ["NIHILISM", "förnekande av alla värden"],
    ["NISCH", "specialområde"],
    ["NIVÅ", "plan, grad"],
    ["NJUTNING", "välbehag"],
    ["NOBEL", "ädel"],
    ["NOGGRANN", "exakt, grundlig"],
    ["NOMINELL", "till namnet"],
    ["NONCHALANT", "likgiltig, vårdslös"],
    ["NORM", "regel, rättesnöre"],
    ["NORMAL", "vanlig"],
    ["NOSTALGI", "längtan tillbaka"],
    ["NOSTALGISK", "längtande tillbaka"],
    ["NOTABEL", "anmärkningsvärd"],
    ["NOTORISK", "ökänd, allmänt känd"],
    ["NOVIS", "nybörjare"],
    ["NYANS", "skiftning, ton"],
    ["NYANSERAD", "mångfacetterad"],
    ["NYCK", "infall"],
    ["NYCKFULL", "oberäknelig"],
    ["NYFIKEN", "vetgirig"],
    ["NYKTER", "saklig, sansad"],
    ["NYTTIG", "gagnande"],
    ["NÄPST", "tillrättavisning"],
    ["NÄRGÅNGEN", "alltför personlig"],
    ["NÄRING", "föda"],
    ["NÄSVIS", "fräck mot äldre"],
    ["NÖDVÄNDIG", "oundgänglig"],
    ["OANAD", "oväntad"],
    ["OANSENLIG", "som inte syns mycket"],
    ["OANTASTLIG", "oangriplig"],
    ["OBEGRIPLIG", "ofattbar"],
    ["OBEHAGLIG", "otrevlig"],
    ["OBESTRIDLIG", "ovedersäglig"],
    ["OBESVARAD", "utan svar"],
    ["OBETYDLIG", "oviktig, liten"],
    ["OBETÄNKSAM", "tanklös"],
    ["OBJEKTIV", "saklig, opartisk"],
    ["OBLIGATORISK", "tvingande"],
    ["OBOTLIG", "ohjälplig"],
    ["OBSCEN", "oanständig"],
    ["OBSERVANT", "uppmärksam"],
    ["OBSESSION", "besatthet"],
    ["OBSKYR", "okänd, dunkel"],
    ["OBSOLET", "föråldrad"],
    ["OBSTINAT", "envis, trotsig"],
    ["OBSTRUERA", "hindra"],
    ["ODÅGA", "lathund, slarver"],
    ["ODÖDLIG", "som aldrig dör"],
    ["OEFTERGIVLIG", "som inte kan efterges"],
    ["OFANTLIG", "gränslöst stor"],
    ["OFARLIG", "utan risk"],
    ["OFFENSIV", "anfallande"],
    ["OFFENTLIG", "allmän"],
    ["OFFER", "uppoffring, drabbad"],
    ["OFFICIELL", "offentligt bekräftad"],
    ["OFRIVILLIG", "oavsiktlig"],
    ["OFÖRENLIG", "som inte går ihop"],
    ["OFÖRSKÄMD", "ohövlig"],
    ["OFÖRVITLIG", "oklanderlig"],
    ["OGRUNDAD", "obefogad"],
    ["OGYNNSAM", "ofördelaktig"],
    ["OHÖRSAM", "olydig"],
    ["OJÄMFÖRLIG", "makalös"],
    ["OKONVENTIONELL", "originell"],
    ["OKÄNSLIG", "tanklös, hårdhudad"],
    ["OLYCKSBÅDANDE", "illavarslande"],
    ["OMDÖME", "förmåga att bedöma"],
    ["OMDÖMESLÖS", "obetänksam"],
    ["OMEDELBAR", "direkt, genast"],
    ["OMGIVNING", "miljö"],
    ["OMISTLIG", "oumbärlig"],
    ["OMNIPOTENT", "allsmäktig"],
    ["OMSORG", "vård, omtanke"],
    ["OMSTRIDD", "ifrågasatt, debatterad"],
    ["OMSTÄLLNING", "förändring"],
    ["OMSTÄNDLIG", "långrandig"],
    ["OMTÄNKSAM", "hänsynsfull"],
    ["OMVÄLVANDE", "revolutionerande"],
    ["OMVÄND", "motsatt"],
    ["ONDSKEFULL", "elak"],
    ["ONYTTIG", "värdelös"],
    ["OPERATIV", "praktiskt verksam"],
    ["OPINION", "allmän mening"],
    ["OPPONERA", "invända"],
    ["OPPORTUN", "lämplig för tillfället"],
    ["OPPOSITION", "motstånd"],
    ["OPTIMAL", "bästa möjliga"],
    ["OPTIMERA", "göra så bra som möjligt"],
    ["OPTIMIST", "den som ser ljust på saker"],
    ["OPTIMISTISK", "ljusögd"],
    ["ORAKEL", "siare, spåman"],
    ["ORDENTLIG", "noggrann, prydlig"],
    ["ORDINÄR", "vanlig, medelmåttig"],
    ["ORDKARG", "fåordig"],
    ["ORGANISERA", "planera och samordna"],
    ["ORGANISK", "naturlig, levande"],
    ["ORIENTERA", "informera, hitta rätt"],
    ["ORIGINELL", "särpräglad"],
    ["OROA", "bekymra"],
    ["ORSAK", "anledning"],
    ["ORTODOX", "renlärig"],
    ["ORÄTTVIS", "inte rättvis"],
    ["OSANNOLIK", "otrolig"],
    ["OSKULD", "renhet"],
    ["OSKYLDIG", "utan skuld"],
    ["OSTENTATIV", "demonstrativ, prålig"],
    ["OTACKSAM", "inte tacksam"],
    ["OTILLRÄCKLIG", "för liten, inte nog"],
    ["OTYGLAD", "ohämmad"],
    ["OUTSÄGLIG", "obeskrivlig"],
    ["OUTTRÖTTLIG", "som aldrig tröttnar"],
    ["OVISSHET", "osäkerhet"],
    ["PACIFIST", "fredsvän"],
    ["PAKT", "avtal"],
    ["PANEGYRISK", "överdrivet berömmande"],
    ["PANIK", "plötslig skräck"],
    ["PANORAMA", "vid utsikt"],
    ["PARADIGM", "tankemönster"],
    ["PARADISISK", "underbar, som paradiset"],
    ["PARADOX", "skenbar motsägelse"],
    ["PARAFRAS", "omskrivning"],
    ["PARALLELL", "likriktad"],
    ["PARANOID", "sjukligt misstänksam"],
    ["PARENTES", "inskott, bisak"],
    ["PARITET", "jämställdhet"],
    ["PARODI", "förlöjligande efterbildning"],
    ["PARTIELL", "delvis"],
    ["PARTISK", "ensidig, jävig"],
    ["PARTNER", "samarbetspart"],
    ["PASSIONERAD", "lidelsefull"],
    ["PASSIV", "overksam"],
    ["PATERNALISTISK", "förmyndaraktig"],
    ["PATETISK", "ömklig, överdrivet känslosam"],
    ["PATOLOGISK", "sjukdomsmässig"],
    ["PATOS", "glöd, stark inlevelse"],
    ["PATRIARKAT", "mansvälde"],
    ["PATRIOTISK", "fosterländsk"],
    ["PEDAGOGISK", "lätt att förstå"],
    ["PEDANT", "petimäter"],
    ["PEDANTISK", "överdrivet noggrann"],
    ["PEJORATIV", "nedsättande"],
    ["PERFEKT", "felfri"],
    ["PERIFER", "avlägsen, oviktig"],
    ["PERIFERI", "utkant"],
    ["PERIODISK", "som sker med jämna mellanrum"],
    ["PERMANENT", "varaktig, bestående"],
    ["PERSISTENT", "ihållande"],
    ["PERSONIFIERA", "förkroppsliga"],
    ["PERSONLIG", "privat"],
    ["PERSPEKTIV", "synvinkel"],
    ["PERVERS", "onormal, snedvriden"],
    ["PESSIMIST", "svartseende person"],
    ["PESSIMISTISK", "mörksynt"],
    ["PETIG", "noga med småsaker"],
    ["PIETET", "vördnad, hänsyn"],
    ["PIKANT", "kryddig, lätt vågad"],
    ["PIONJÄR", "föregångare"],
    ["PITTORESK", "målerisk"],
    ["PLAGIAT", "efterapning, avskrift"],
    ["PLAGIERA", "kopiera andras verk"],
    ["PLANLÖS", "utan mål"],
    ["PLATITYD", "intetsägande fras"],
    ["PLAUSIBEL", "trolig, rimlig"],
    ["PLIKTSKYLDIG", "förpliktad"],
    ["PLIKTTROGEN", "ansvarsfull"],
    ["PLURALISM", "mångfald"],
    ["PLÅGSAM", "smärtsam"],
    ["PLÖTSLIG", "hastig, oväntad"],
    ["POETISK", "diktartad"],
    ["POLARISERA", "dela i läger"],
    ["POLEMIK", "skarp debatt"],
    ["POMPA", "prakt, ståt"],
    ["POMPÖS", "ståtlig, överdådig"],
    ["PONERA", "anta, förutsätta"],
    ["POPULISM", "folkfriande politik"],
    ["POPULÄR", "omtyckt"],
    ["PORTABEL", "bärbar"],
    ["POSITIONERA", "placera"],
    ["POSTUM", "efter döden"],
    ["POTENT", "kraftfull"],
    ["POTENTIELL", "tänkbar i framtiden"],
    ["PRAGMATISK", "praktisk, saklig"],
    ["PRAKTFULL", "ståtlig"],
    ["PRAKTIK", "tillämpning"],
    ["PRAKTISK", "användbar"],
    ["PREDESTINERAD", "förutbestämd"],
    ["PREFERENS", "företräde, förkärlek"],
    ["PREJUDIKAT", "vägledande domslut"],
    ["PREKÄR", "besvärlig, osäker"],
    ["PREMIERA", "belöna"],
    ["PREMISS", "förutsättning"],
    ["PRESENTABEL", "snygg nog att visa upp"],
    ["PRESTERA", "åstadkomma"],
    ["PRESTIGE", "anseende"],
    ["PRESTIGELÖS", "utan behov av status"],
    ["PRESUMTIV", "trolig, blivande"],
    ["PRETENTION", "anspråk"],
    ["PRETENTIÖS", "anspråksfull"],
    ["PREVENTIV", "som skyddar mot"],
    ["PRIMITIV", "ursprunglig, enkel"],
    ["PRIMÄR", "första, huvudsaklig"],
    ["PRINCIP", "regel man följer"],
    ["PRINCIPIELL", "grundsatsmässig"],
    ["PRIORITERA", "sätta först"],
    ["PRIVILEGIUM", "förmån"],
    ["PROAKTIV", "förebyggande"],
    ["PROBLEMATIK", "frågeställning"],
    ["PROBLEMATISK", "svårlöst"],
    ["PROCEDUR", "tillvägagångssätt"],
    ["PROCESS", "arbetsgång"],
    ["PRODUKTIV", "som ger mycket resultat"],
    ["PROFAN", "världslig, icke-religiös"],
    ["PROFESSIONELL", "yrkesmässig"],
    ["PROFETIA", "spådom"],
    ["PROFIL", "kontur, image"],
    ["PROFITERA", "dra nytta av"],
    ["PROGNOS", "förutsägelse"],
    ["PROGRESSIV", "framstegsvänlig"],
    ["PROHIBITION", "förbud mot alkohol"],
    ["PROKLAMERA", "kungöra"],
    ["PROLOG", "förord"],
    ["PROMINENT", "framstående"],
    ["PROMPT", "genast, bestämt"],
    ["PROPAGANDA", "ensidig påverkan"],
    ["PROPORTION", "storleksförhållande"],
    ["PROPORTIONERLIG", "välavvägd"],
    ["PROSAISK", "torr, vardaglig"],
    ["PROTAGONIST", "huvudperson"],
    ["PROTEST", "missnöjesyttring"],
    ["PROTOKOLL", "anteckningar"],
    ["PROVINSIELL", "småstadsaktig"],
    ["PROVISION", "arvode"],
    ["PROVISORISK", "tills vidare, nödfalls-"],
    ["PROVOCERA", "reta, utmana"],
    ["PROVOKATIV", "utmanande"],
    ["PRUNKANDE", "praktfull, blomstrande"],
    ["PRÅLIG", "överdådigt utsmyckad"],
    ["PRÄGLA", "känneteckna"],
    ["PRÖVA", "testa"],
    ["PSEUDONYM", "täcknamn"],
    ["PSYKISK", "själslig"],
    ["PUBLICERA", "ge ut"],
    ["PUBLIK", "åskådare"],
    ["PUBLIKATION", "utgåva"],
    ["PUERIL", "barnslig"],
    ["PUNKTLIG", "i rätt tid"],
    ["PÅBUD", "order"],
    ["PÅFALLANDE", "anmärkningsvärt tydlig"],
    ["PÅFLUGEN", "närgången"],
    ["PÅFRESTANDE", "krävande"],
    ["PÅFRESTNING", "ansträngning"],
    ["PÅHITT", "idé"],
    ["PÅHITTIG", "uppfinningsrik"],
    ["PÅKOSTAD", "dyrbar"],
    ["PÅLITLIG", "som man kan lita på"],
    ["PÅMINNELSE", "erinran"],
    ["PÅSKYNDA", "skynda på"],
    ["PÅSTRIDIG", "tjurskallig"],
    ["PÅTAGLIG", "märkbar, konkret"],
    ["RABALDER", "bråk, uppståndelse"],
    ["RADIKAL", "genomgripande"],
    ["RADIKALISERA", "göra mer extrem"],
    ["RAFFINERAD", "förfinad, listig"],
    ["RAMSA", "uppräkning"],
    ["RASERA", "förstöra"],
    ["RATIFICERA", "godkänna ett fördrag"],
    ["RATIONALISERA", "effektivisera"],
    ["RATIONELL", "förnuftig, effektiv"],
    ["REAKTION", "gensvar"],
    ["REAKTIONÄR", "bakåtsträvande"],
    ["REALISERA", "förverkliga"],
    ["REALISM", "verklighetssinne"],
    ["REALISTISK", "verklighetstrogen"],
    ["REBELL", "upprorsmakare"],
    ["REBELLISK", "upprorisk"],
    ["RECENSION", "kritisk granskning"],
    ["RECIPROK", "ömsesidig"],
    ["REDIGERA", "bearbeta text"],
    ["REDLIG", "ärlig, hederlig"],
    ["REDOGÖRA", "förklara"],
    ["REDSKAP", "verktyg"],
    ["REDUCERA", "minska"],
    ["REDUNDANT", "överflödig"],
    ["REFERERA", "återge, hänvisa"],
    ["REFLEKTERA", "fundera, spegla"],
    ["REFLEX", "ofrivillig reaktion"],
    ["REFORM", "förbättring, omdaning"],
    ["REFORMERA", "förnya"],
    ["REGELBUNDEN", "jämn"],
    ["REGELVERK", "regler"],
    ["REGIM", "styre"],
    ["REGION", "landsdel"],
    ["REGISTRERA", "anteckna"],
    ["REGLERA", "ordna med regler"],
    ["REGRESSION", "tillbakagång"],
    ["REHABILITERA", "återställa"],
    ["REKAPITULERA", "sammanfatta"],
    ["REKLAM", "marknadsföring"],
    ["REKOMMENDERA", "föreslå"],
    ["REKONSTRUERA", "återskapa"],
    ["REKRYTERA", "värva"],
    ["RELATERA", "sätta i samband"],
    ["RELATIV", "förhållandevis"],
    ["RELEVANS", "betydelse för saken"],
    ["RELEVANT", "som hör till saken"],
    ["RELIGIÖS", "troende, from"],
    ["REMARKABEL", "märkvärdig"],
    ["REMINISCENS", "minne, kvarleva"],
    ["REMISS", "begäran om yttrande"],
    ["RENHET", "renlighet"],
    ["RENODLA", "förfina"],
    ["RENODLAD", "ren, oblandad"],
    ["RENOVERA", "rusta upp"],
    ["REPERTOAR", "inövade verk"],
    ["REPETERA", "upprepa"],
    ["REPLIK", "svar, yttrande"],
    ["REPRESENTATIV", "som speglar helheten"],
    ["REPRESSALIER", "bestraffningsåtgärder"],
    ["REPRODUCERA", "återge, kopiera"],
    ["REPUTATION", "rykte"],
    ["RESERVERAD", "förbehållsam"],
    ["RESIGNERAD", "uppgiven"],
    ["RESOLUT", "beslutsam"],
    ["RESPEKTABEL", "aktningsvärd"],
    ["RESTAURERA", "återställa i ursprungligt skick"],
    ["RESTRIKTION", "begränsning"],
    ["RESTRIKTIV", "begränsande, återhållsam"],
    ["RESULTAT", "utfall"],
    ["RESURS", "tillgång"],
    ["RETIRERA", "dra sig tillbaka"],
    ["RETORIK", "talekonst"],
    ["RETROSPEKTIV", "tillbakablickande"],
    ["REVANSCH", "upprättelse"],
    ["REVIDERA", "ändra, se över"],
    ["REVOLUTION", "omvälvning"],
    ["RIGID", "stel, strikt"],
    ["RIGORÖS", "sträng, noggrann"],
    ["RIKTLINJE", "vägledning"],
    ["RINGAKTA", "förakta"],
    ["RISKABEL", "farlig, vågad"],
    ["RITUAL", "ceremoni"],
    ["RITUELL", "enligt ritual"],
    ["RIVAL", "konkurrent"],
    ["RIVALITET", "konkurrens"],
    ["ROBUST", "kraftig"],
    ["ROMANTISK", "svärmisk"],
    ["ROTFAST", "förankrad"],
    ["ROTLÖS", "utan fäste"],
    ["RUDIMENTÄR", "outvecklad"],
    ["RUIN", "förstörelse"],
    ["RUNDHÄNT", "slösande givmild"],
    ["RUSTIK", "lantlig och enkel"],
    ["RUTIN", "vana, erfarenhet"],
    ["RYKTBAR", "berömd"],
    ["RÅDGIVARE", "konsult"],
    ["RÅDVILL", "villrådig"],
    ["RÄDDHÅGAD", "feg"],
    ["RÄTTFÄRDIG", "rättskaffens"],
    ["RÄTTIGHET", "befogenhet"],
    ["RÄTTVIS", "just"],
    ["SABOTERA", "förstöra med avsikt"],
    ["SAKKUNNIG", "kunnig i ämnet"],
    ["SAKLIG", "korrekt, utan känslor"],
    ["SAKRAL", "helig, kyrklig"],
    ["SAKTMODIG", "stillsam, mild"],
    ["SAMARBETE", "kooperation"],
    ["SAMFÖRSTÅND", "god förståelse"],
    ["SAMLAD", "lugn, fattad"],
    ["SAMSTÄMMIG", "enig"],
    ["SAMVETSGRANN", "plikttrogen, noggrann"],
    ["SANERA", "göra ren, rusta upp"],
    ["SANGVINISK", "livlig, optimistisk"],
    ["SANKTION", "straffåtgärd"],
    ["SANKTIONERA", "ge sitt bifall"],
    ["SANNOLIK", "rimlig att anta"],
    ["SANSAD", "förnuftig, lugn"],
    ["SARKASM", "bitande ironi"],
    ["SARKASTISK", "spydig"],
    ["SATIR", "förlöjligande skildring"],
    ["SATIRISK", "hånfullt skämtsam"],
    ["SCENARIO", "händelseförlopp"],
    ["SCHABLON", "mall, stereotyp"],
    ["SEDESAM", "ärbar i sitt uppträdande"],
    ["SEGDRAGEN", "långvarig"],
    ["SEKTOR", "område, del"],
    ["SEKULÄR", "icke-religiös"],
    ["SEKUNDÄR", "underordnad"],
    ["SELEKTION", "urval"],
    ["SELEKTIV", "urskiljande, väljande"],
    ["SENIL", "ålderssvag"],
    ["SENSATION", "uppseende"],
    ["SENSIBEL", "lyhörd, finkänslig"],
    ["SENSUELL", "erotiskt laddad"],
    ["SENTENS", "kärnfullt ordspråk"],
    ["SENTIMENTAL", "känslosam"],
    ["SEPARAT", "för sig, fristående"],
    ["SERIÖS", "allvarlig"],
    ["SERVIL", "inställsam, krypande"],
    ["SFÄR", "område, krets"],
    ["SIGNAL", "tecken"],
    ["SIGNIFIKANT", "betydande"],
    ["SIMULTAN", "samtidig"],
    ["SINNLIG", "njutningsfull"],
    ["SJÄLVGOD", "självbelåten"],
    ["SJÄLVKLAR", "uppenbar"],
    ["SKADEGLAD", "glad åt andras olycka"],
    ["SKANDAL", "uppseendeväckande händelse"],
    ["SKEPNAD", "gestalt"],
    ["SKEPTIKER", "tvivlare"],
    ["SKEPTISK", "tvivlande"],
    ["SKILDRA", "beskriva"],
    ["SKONINGSLÖS", "obarmhärtig"],
    ["SKRUPELFRI", "samvetslös"],
    ["SKRUPLER", "samvetsbetänkligheter"],
    ["SKRYMTA", "visa falsk fromhet"],
    ["SKRYTSAM", "som skryter"],
    ["SKRÄVLA", "skryta"],
    ["SKYDDSLÖS", "oskyddad"],
    ["SKYGG", "rädd, blyg"],
    ["SLAPP", "lös, slak"],
    ["SLAVISK", "okritiskt efterliknande"],
    ["SLENTRIAN", "vanemässighet"],
    ["SLUG", "listig"],
    ["SLÖSAKTIG", "som gör av med för mycket"],
    ["SMAKLÖS", "utan god smak"],
    ["SMICKRA", "fjäska"],
    ["SMIDIG", "följsam, mjuk"],
    ["SMÄDA", "håna, förolämpa"],
    ["SMÄLEK", "förödmjukelse"],
    ["SNARSTUCKEN", "lättstött"],
    ["SNILLE", "geni"],
    ["SNOBBIG", "som vill verka förnäm"],
    ["SNÅL", "gnidig"],
    ["SNÖPLIG", "förödmjukande, snopen"],
    ["SOFISTIKERAD", "världsvan, avancerad"],
    ["SOLID", "fast, gedigen"],
    ["SOLIDARISK", "lojal, sammanhållande"],
    ["SOLIDARITET", "sammanhållning"],
    ["SOLITÄR", "ensamlevande"],
    ["SOMNAMBUL", "sömngångare"],
    ["SONDERA", "undersöka försiktigt"],
    ["SORGFÄLLIG", "omsorgsfull"],
    ["SORGLÖS", "bekymmerslös"],
    ["SPARSAM", "hushållande"],
    ["SPARTANSK", "enkel, utan lyx"],
    ["SPECIFIK", "precis angiven"],
    ["SPEKTAKEL", "uppträde"],
    ["SPEKTAKULÄR", "effektfull"],
    ["SPEKULATIV", "grundad på antaganden"],
    ["SPEKULERA", "gissa, fundera"],
    ["SPETSFUNDIG", "hårklyvande"],
    ["SPIRITUELL", "kvick, andlig"],
    ["SPLITTRAD", "oenig, uppdelad"],
    ["SPLITTRING", "uppdelning"],
    ["SPONSRA", "stödja ekonomiskt"],
    ["SPONTAN", "oplanerad, naturlig"],
    ["SPORADISK", "enstaka, tillfällig"],
    ["SPRIDA", "distribuera"],
    ["SPRÖD", "skör"],
    ["STABIL", "stadig"],
    ["STABILITET", "fasthet"],
    ["STAGNATION", "stillastående"],
    ["STAGNERA", "avstanna"],
    ["STANDARD", "nivå, mått"],
    ["STATISK", "orörlig"],
    ["STATUS", "ställning"],
    ["STEGRING", "ökning"],
    ["STENHÅRD", "obeveklig"],
    ["STEREOTYP", "schablonartad"],
    ["STIGMA", "skamfläck"],
    ["STIMULANS", "uppmuntran"],
    ["STIMULERA", "uppmuntra, egga"],
    ["STIMULERANDE", "uppiggande"],
    ["STINN", "proppmätt"],
    ["STIPULERA", "fastställa"],
    ["STOICISM", "sinneslugn"],
    ["STOISK", "orubbligt lugn"],
    ["STRATEGI", "långsiktig plan"],
    ["STRIKT", "sträng"],
    ["STRINGENT", "stram, logiskt sammanhängande"],
    ["STRUKTUR", "uppbyggnad"],
    ["STRUKTURERA", "ordna"],
    ["STRÄVA", "kämpa"],
    ["STURSK", "trotsig, stolt"],
    ["STÅNDAKTIG", "som står emot"],
    ["STÅNDPUNKT", "åsikt"],
    ["STÖRANDE", "irriterande"],
    ["SUBJEKTIV", "personlig, ej objektiv"],
    ["SUBLIM", "upphöjd, förfinad"],
    ["SUBSTANS", "innehåll, ämne"],
    ["SUBTIL", "fin, svårfångad"],
    ["SUBVENTION", "statligt bidrag"],
    ["SUCCESSION", "tronföljd"],
    ["SUCCESSIV", "gradvis"],
    ["SUGGESTION", "påverkan"],
    ["SUGGESTIV", "stämningsfull, påverkande"],
    ["SUMMARISK", "översiktlig, kortfattad"],
    ["SUPERB", "utmärkt"],
    ["SUPERFICIELL", "ytlig"],
    ["SUPPLEMENT", "tillägg"],
    ["SURMULEN", "butter"],
    ["SURREALISTISK", "drömlik, overklig"],
    ["SUVERÄN", "överlägsen, oberoende"],
    ["SVAGHET", "svag punkt"],
    ["SVEKFULL", "förrädisk"],
    ["SVEPSKÄL", "förevändning"],
    ["SVIKA", "överge"],
    ["SVÅRMOD", "nedstämdhet"],
    ["SYMBIOS", "samlevnad till ömsesidig nytta"],
    ["SYMBOL", "sinnebild"],
    ["SYMBOLISK", "sinnebildlig"],
    ["SYMMETRI", "likformighet"],
    ["SYMPATI", "medkänsla"],
    ["SYMPTOMATISK", "typisk, betecknande"],
    ["SYNONYM", "ord med samma betydelse"],
    ["SYNTES", "sammanfogning"],
    ["SYSSLOLÖS", "utan sysselsättning"],
    ["SYSTEMATISK", "metodisk"],
    ["SÅRA", "kränka"],
    ["SÅRBAR", "känslig"],
    ["SÄLLSAM", "underlig"],
    ["SÄLLSYNT", "ovanlig"],
    ["SÄREGEN", "egenartad"],
    ["SÄRSKILD", "speciell"],
    ["SÖLA", "dröja, slöa"],
    ["SÖVANDE", "så tråkig att man somnar"],
    ["TABU", "förbjudet ämne"],
    ["TAKTFULL", "finkänslig"],
    ["TAKTIK", "stridsplan, metod"],
    ["TAKTLÖS", "klumpig i umgänge"],
    ["TALANG", "särskild gåva"],
    ["TALESMAN", "företrädare"],
    ["TANKSPRIDD", "disträ"],
    ["TEMPERAMENT", "lynne"],
    ["TEMPORÄR", "tillfällig"],
    ["TENDENS", "benägenhet, riktning"],
    ["TENDENTIÖS", "vinklad"],
    ["TENTATIV", "preliminär"],
    ["TEORETISK", "som bygger på teori"],
    ["TERMINOLOGI", "fackspråk"],
    ["TERRITORIUM", "landområde"],
    ["TESTAMENTE", "arvsbestämmelse"],
    ["TIDLÖS", "som inte blir omodern"],
    ["TILLFÄLLIGHET", "slump"],
    ["TILLGIVEN", "lojal och vänfast"],
    ["TILLRÄTTALAGD", "anpassad, friserad"],
    ["TILLTAGSEN", "djärv, företagsam"],
    ["TILLTALANDE", "lockande"],
    ["TILLTRO", "förtroende"],
    ["TIRAD", "ordflöde"],
    ["TOLERANS", "fördragsamhet"],
    ["TOLERANT", "fördragsam"],
    ["TOTALITÄR", "diktatorisk"],
    ["TRADITION", "sedvänja"],
    ["TRAGISK", "sorglig"],
    ["TRAKASSERA", "ofreda, plåga"],
    ["TRANSAKTION", "affär"],
    ["TRANSFORMERA", "omvandla"],
    ["TRANSPARENT", "genomskinlig"],
    ["TRAUMA", "psykisk skada"],
    ["TRENDIG", "modern"],
    ["TRILSKA", "vara trotsig"],
    ["TRIUMF", "seger"],
    ["TRIVIAL", "vardaglig, obetydlig"],
    ["TRIVSAM", "behaglig, hemtrevlig"],
    ["TROFAST", "ståndaktig, alltid trogen"],
    ["TROHJÄRTAD", "oskuldsfullt tillitsfull"],
    ["TRYCKANDE", "kvävande"],
    ["TRYGG", "säker"],
    ["TRÄGEN", "envist ihärdig"],
    ["TRÖGTÄNKT", "långsam i tanken"],
    ["TUMULT", "uppståndelse"],
    ["TVEKSAM", "osäker"],
    ["TVETYDIG", "dubbeltydig"],
    ["TVIVEL", "misstro, tvekan"],
    ["TVIVELAKTIG", "diskutabel"],
    ["TVÅNG", "påtryckning"],
    ["TVÄR", "kort i tonen"],
    ["TYRANNI", "förtryck"],
    ["TYST", "ljudlös"],
    ["TÅLIG", "slitstark"],
    ["TÅLMODIG", "uthållig i väntan"],
    ["TÄNKVÄRD", "som väcker eftertanke"],
    ["UMBÄRA", "klara sig utan"],
    ["UMBÄRLIG", "onödig, som man klarar sig utan"],
    ["UMGÄNGE", "kontakt"],
    ["UNDERDÅNIG", "lydig, servil"],
    ["UNDERFUNDIG", "lurig, finurlig"],
    ["UNDERHÅLLANDE", "roande"],
    ["UNDERKASTA", "lyda"],
    ["UNDERMÅLIG", "av dålig kvalitet"],
    ["UNDERSKATTA", "värdera för lågt"],
    ["UNDERSTÖDJA", "stödja"],
    ["UNDFALLANDE", "eftergiven"],
    ["UNDFLYENDE", "svävande, ej rakt svar"],
    ["UNDVIKA", "gå runt"],
    ["UNIFORM", "enhetlig"],
    ["UNIK", "enastående"],
    ["UNISON", "enstämmig"],
    ["UNIVERSELL", "allmängiltig"],
    ["UPPBYGGLIG", "moraliskt lärorik"],
    ["UPPHOV", "ursprung"],
    ["UPPLEVELSE", "erfarenhet"],
    ["UPPLYST", "kunnig, klok"],
    ["UPPMUNTRA", "sporra"],
    ["UPPOFFRING", "försakelse"],
    ["UPPRIKTIG", "öppen, sanningsenlig"],
    ["UPPROR", "revolt"],
    ["UPPRÄTTHÅLLA", "hålla vid liv"],
    ["UPPSKATTNING", "värdesättande"],
    ["UPPSTUDSIG", "trotsig, uppkäftig"],
    ["UPPSÅTLIG", "avsiktlig"],
    ["URBAN", "förfinad, stadsmässig"],
    ["URSPRUNGLIG", "original, första"],
    ["URSÄKTA", "förlåta"],
    ["UTANFÖRSKAP", "marginalisering"],
    ["UTARBETA", "sammanställa"],
    ["UTBILDNING", "skolning"],
    ["UTBREDD", "vanlig, spridd"],
    ["UTFORSKA", "upptäcka"],
    ["UTFÖRLIG", "detaljrik"],
    ["UTILITARISM", "nyttomoral"],
    ["UTMANA", "trotsa"],
    ["UTMANANDE", "provocerande"],
    ["UTMÄRKANDE", "kännetecknande"],
    ["UTOMORDENTLIG", "ypperlig"],
    ["UTOPI", "drömsamhälle"],
    ["UTOPISK", "orealistisk"],
    ["UTSATT", "exponerad, i fara"],
    ["UTSIKT", "vy, chans"],
    ["UTSTUDERAD", "genomtänkt, avsiktlig"],
    ["UTTALANDE", "yttrande"],
    ["UTTÖMMANDE", "fullständig"],
    ["VAG", "oklar, obestämd"],
    ["VAGABOND", "luffare"],
    ["VAKANS", "ledig tjänst"],
    ["VAKSAM", "på sin vakt"],
    ["VALFRIHET", "frihet att välja"],
    ["VALHÄNT", "ovan med händerna"],
    ["VANDALISERA", "förstöra med flit"],
    ["VANHEDER", "skam"],
    ["VANHEDRA", "skämma ut"],
    ["VANKA", "gå omkring planlöst"],
    ["VANKELMODIG", "obeslutsam"],
    ["VANSINNIG", "galen"],
    ["VARIATION", "omväxling"],
    ["VARSAM", "försiktig"],
    ["VEDERBÖRANDE", "den det gäller"],
    ["VEDERGÄLLNING", "hämnd"],
    ["VEDERHÄFTIG", "tillförlitlig"],
    ["VEDERLÄGGA", "motbevisa"],
    ["VEDERMÄLE", "bevis, tecken"],
    ["VEDERMÖDA", "prövning, svårighet"],
    ["VEDERTAGEN", "allmänt accepterad"],
    ["VEKLIG", "mesig, svag"],
    ["VEMOD", "stilla sorg"],
    ["VERBAL", "muntlig, språklig"],
    ["VERIFIERA", "bekräfta"],
    ["VERKLIGHET", "realitet"],
    ["VERKSAM", "aktiv"],
    ["VERSATIL", "mångsidig"],
    ["VIDLYFTIG", "omfattande, vidsträckt"],
    ["VIDSKEPLIG", "skrockfull"],
    ["VIKARIE", "ställföreträdare"],
    ["VIKTIG", "betydelsefull"],
    ["VILJESTARK", "bestämd"],
    ["VINNLÄGGA", "anstränga sig"],
    ["VIRTUOS", "mästare"],
    ["VISHET", "klokhet"],
    ["VISIONÄR", "framsynt person"],
    ["VITAL", "livskraftig"],
    ["VITALISERA", "ge ny kraft"],
    ["VITTNESMÅL", "utsaga"],
    ["VOLATIL", "flyktig, instabil"],
    ["VOLONTÄR", "frivillig"],
    ["VRESIG", "butter, sur"],
    ["VULGÄR", "simpel, grov"],
    ["VÅGHALSIG", "vågsam, riskfylld"],
    ["VÅLDSAM", "med våld"],
    ["VÅNDA", "ångest, plåga"],
    ["VÅRDSLÖS", "ovarsam"],
    ["VÄLBEHÅLLEN", "oskadd"],
    ["VÄLBÄRGAD", "förmögen"],
    ["VÄLGRUNDAD", "väl underbyggd"],
    ["VÄLGÖRANDE", "nyttig, hälsosam"],
    ["VÄLKOMNA", "hälsa"],
    ["VÄLKÄND", "känd av många"],
    ["VÄLSTÅND", "rikedom"],
    ["VÄLVILJA", "godhet"],
    ["VÄLVILLIG", "vänligt inställd"],
    ["VÄRDEFULL", "av stort värde"],
    ["VÄRDELÖS", "oanvändbar"],
    ["VÄRDESÄTTA", "uppskatta"],
    ["VÄRDIG", "förtjänt, ståndsmässig"],
    ["VÄRNA", "skydda"],
    ["VÄRNLÖS", "utan värn"],
    ["YMNIG", "överflödande"],
    ["YPPERLIG", "förträfflig"],
    ["YRVAKEN", "nyvaken, förvirrad"],
    ["YTLIG", "utan djup"],
    ["ZENIT", "högsta punkt"],
    ["ÅHÖRARE", "lyssnare"],
    ["ÅLDERSTIGEN", "till åren kommen"],
    ["ÅLÄGGA", "ge i uppdrag, beordra"],
    ["ÅNGERFULL", "botfärdig"],
    ["ÅTERGÄLDA", "betala tillbaka"],
    ["ÅTERHÅLLSAM", "måttfull"],
    ["ÅTERHÄMTNING", "tillfrisknande"],
    ["ÅTERKALLA", "dra tillbaka"],
    ["ÅTERSPEGLA", "avspegla"],
    ["ÅTERSTÅ", "finnas kvar"],
    ["ÅTERUPPTA", "börja igen"],
    ["ÅTRÅ", "begär"],
    ["ÄMBETE", "tjänst, befattning"],
    ["ÄMNE", "substans, tema"],
    ["ÄNDAMÅL", "syfte"],
    ["ÄNGSLIG", "orolig, rädd"],
    ["ÄRBAR", "anständig, dygdig"],
    ["ÄRELYSTEN", "hungrig efter ära"],
    ["ÄRLIG", "hederlig och sann"],
    ["ÄVENTYRA", "riskera"],
    ["ÄVENTYRLIG", "osäker, vågad"],
    ["ÖDE", "bestämmelse"],
    ["ÖDMJUK", "anspråkslös, inte högmodig"],
    ["ÖDSLIG", "övergiven, tom"],
    ["ÖMSINT", "kärleksfull"],
    ["ÖPPENHJÄRTIG", "frispråkig"],
    ["ÖVERDRIFT", "förstoring"],
    ["ÖVERDÅDIG", "slösande"],
    ["ÖVERENSSTÄMMA", "stämma"],
    ["ÖVERFLÖD", "riklighet"],
    ["ÖVERGIVEN", "lämnad ensam"],
    ["ÖVERGRIPANDE", "som täcker helheten"],
    ["ÖVERGÅNG", "skifte"],
    ["ÖVERHETTA", "göra för varm"],
    ["ÖVERILAD", "förhastad"],
    ["ÖVERLÅTA", "överföra till annan"],
    ["ÖVERLÄGSEN", "bättre, dominerande"],
    ["ÖVERMOD", "förmätenhet"],
    ["ÖVERMÄKTIG", "för svår"],
    ["ÖVERRASKNING", "oväntad händelse"],
    ["ÖVERSEENDE", "tolerant, förlåtande"],
    ["ÖVERSIKT", "sammanfattning"],
    ["ÖVERSKATTA", "värdera för högt"],
    ["ÖVERSKÅDLIG", "lätt att överblicka"],
    ["ÖVERTALA", "förmå"],
    ["ÖVERTRO", "överdriven tro"],
    ["ÖVERTYGA", "få någon att tro"],
    ["ÖVERVINNA", "komma över"],
    ["ÖVERVÄGA", "fundera på"],
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = WORDS;
  else root.HP_WORDS = WORDS;
})(this);
