// Dagens ord: ord med egenskrivna exempelmeningar. Ordet i meningen står mellan *stjärnor*.
// Varje dag väljs ett ord (samma för alla), och betydelsen hämtas från ordlistan (words.js).
(function (root) {
  const WOTD = [
    ["AKRIBI", "Hon granskade källorna med en *akribi* som imponerade på hela institutionen."],
    ["AMBIVALENT", "Han var *ambivalent* inför flytten – lockad av jobbet men ledsen över att lämna vännerna."],
    ["ANAKRONISM", "En armbandsklocka i en film om vikingatiden är en tydlig *anakronism*."],
    ["ANTAGONIST", "I romanen är den girige borgmästaren hjältens främsta *antagonist*."],
    ["APATISK", "Efter förlusten satt laget *apatiskt* i omklädningsrummet."],
    ["ARBITRÄR", "Gränsen på 18 år är till viss del *arbiträr*, men någonstans måste den dras."],
    ["ARKAISK", "Lagtexten innehöll flera *arkaiska* uttryck som ingen längre använder."],
    ["ASKETISK", "Munkarna levde ett *asketiskt* liv utan några bekvämligheter."],
    ["AUKTORITÄR", "Den nya rektorn hade en *auktoritär* stil och tålde inga invändningar."],
    ["AVOG", "Styrelsen var till en början *avog* mot förslaget."],
    ["BANAL", "Filmens slut var så *banalt* att publiken suckade."],
    ["BEFOGAD", "Kritiken mot bygget visade sig vara helt *befogad*."],
    ["BESKÄFTIG", "Den *beskäftiga* grannen hade åsikter om allt vi gjorde i trädgården."],
    ["BIGOTT", "Hans *bigotta* syn på andra religioner väckte starka reaktioner."],
    ["BLASERAD", "Efter tio år i branschen var hon ganska *blaserad* inför premiärer."],
    ["BORNERAD", "Det vore *bornerat* att avfärda idén utan att ens pröva den."],
    ["BRYSK", "Han avbröt henne på ett *bryskt* sätt."],
    ["DEKADENS", "Författaren skildrar överklassens *dekadens* under 1920-talet."],
    ["DEMAGOG", "Historien känner många *demagoger* som vunnit makt genom att spela på rädsla."],
    ["DESILLUSIONERAD", "Efter valet var många unga väljare *desillusionerade*."],
    ["DIDAKTISK", "Pjäsen är tydligt *didaktisk* – den vill lära publiken något."],
    ["DIFFUS", "Symtomen var *diffusa* och svåra att tolka för läkaren."],
    ["DIGRESSION", "Föreläsaren gjorde en lång *digression* om sin egen studietid."],
    ["DIKOTOMI", "Artikeln ifrågasätter *dikotomin* mellan natur och kultur."],
    ["DISKREPANS", "Det fanns en tydlig *diskrepans* mellan löftena och verkligheten."],
    ["DOGMATISK", "Han var så *dogmatisk* att ingen diskussion var möjlig."],
    ["DUBIÖS", "Företaget hade *dubiösa* affärskontakter i flera länder."],
    ["EFEMÄR", "Modeflugan visade sig vara *efemär* och glömdes snabbt bort."],
    ["EKLEKTISK", "Hennes *eklektiska* smak blandade barock med modern design."],
    ["ELOKVENT", "Den *elokventa* talaren fick hela salen att lyssna."],
    ["EMPIRI", "Teorin saknar stöd i *empirin*."],
    ["EPIGON", "Kritikerna avfärdade honom som en blek *epigon* till de stora mästarna."],
    ["ESKALERA", "Konflikten *eskalerade* snabbt när fler länder drogs in."],
    ["EUFEMISM", "\"Gått bort\" är en vanlig *eufemism* för att dö."],
    ["EXPLICIT", "Regeln står *explicit* i avtalet, så ingen kan påstå att de inte visste."],
    ["FATALISM", "Hans *fatalism* gjorde att han aldrig försökte påverka sin situation."],
    ["FIASKO", "Lanseringen blev ett *fiasko* – ingen köpte produkten."],
    ["FLEGMATISK", "Den *flegmatiske* domaren lät sig aldrig stressas av publiken."],
    ["FRUGAL", "De levde ett *frugalt* liv och sparade varje krona."],
    ["FÖRMÄTEN", "Det var *förmätet* av honom att kräva en plats i styrelsen redan första veckan."],
    ["GEDIGEN", "Hon har en *gedigen* utbildning inom ekonomi."],
    ["GENANT", "Det var *genant* att glömma talet mitt på scenen."],
    ["GROTESK", "Karikatyren var så *grotesk* att den väckte obehag."],
    ["HABIL", "Han är en *habil* pianist, även om han aldrig blev professionell."],
    ["HEGEMONI", "Landet hade länge ekonomisk *hegemoni* i regionen."],
    ["HETEROGEN", "Klassen var *heterogen*, med elever från många olika bakgrunder."],
    ["HOMOGEN", "Gruppen var ovanligt *homogen* – alla hade samma utbildning."],
    ["HYBRIS", "Generalens *hybris* ledde till ett förödande nederlag."],
    ["IDIOSYNKRASI", "Att alltid äta frukost stående var en av hans *idiosynkrasier*."],
    ["IMPLICIT", "Kritiken var *implicit* men alla förstod vad hon menade."],
    ["INDOLENT", "Den *indolente* arvtagaren brydde sig inte om släktföretaget."],
    ["INERT", "Gasen är *inert* och reagerar inte med andra ämnen."],
    ["INFAM", "Det var en *infam* lögn som skadade hans rykte."],
    ["INHERENT", "Risken är *inherent* i all aktiehandel."],
    ["INKOHERENT", "Vittnets berättelse var *inkoherent* och svår att följa."],
    ["INSINUERA", "Han *insinuerade* att kollegan hade fuskat."],
    ["INTRIKAT", "Mönstret var så *intrikat* att det tog månader att väva."],
    ["IRREVERSIBEL", "Skadorna på korallreven kan vara *irreversibla*."],
    ["KATEGORISK", "Hon gav ett *kategoriskt* nej till förslaget."],
    ["KLENTROGEN", "Publiken var *klentrogen* inför trollkarlens påståenden."],
    ["KONCIS", "Skriv en *koncis* sammanfattning på högst en sida."],
    ["KONFORMISM", "Romanen kritiserar småstadens *konformism*."],
    ["KONSENSUS", "Efter långa diskussioner nådde gruppen *konsensus*."],
    ["KONTROVERSIELL", "Förslaget var *kontroversiellt* och splittrade partiet."],
    ["KOPIÖS", "Middagen var *kopiös* med fem rätter."],
    ["KRASS", "Beslutet fattades av *krassa* ekonomiska skäl."],
    ["KRYPTISK", "Meddelandet var så *kryptiskt* att ingen förstod det."],
    ["KUMULATIV", "Effekten av små förändringar är *kumulativ* över tid."],
    ["LAKONISK", "\"Det gick bra\", svarade hon *lakoniskt*."],
    ["LATENT", "Konflikten hade länge funnits *latent* innan den bröt ut."],
    ["LETARGI", "Efter sjukdomen föll han i en djup *letargi*."],
    ["LUKRATIV", "Affären visade sig vara mycket *lukrativ*."],
    ["MARGINELL", "Förändringen fick bara *marginell* betydelse för resultatet."],
    ["MEDIOKER", "Filmen fick *mediokra* recensioner."],
    ["METICULÖS", "Hon var *meticulös* och kontrollerade varje siffra två gånger."],
    ["MINUTIÖS", "Planeringen var *minutiös* in i minsta detalj."],
    ["MONDÄN", "Hotellet hade en *mondän* atmosfär med kristallkronor och sammet."],
    ["MUNDÄN", "Han tröttnade på det *mundäna* kontorsarbetet."],
    ["NONCHALANT", "Hon ryckte *nonchalant* på axlarna åt kritiken."],
    ["NOTORISK", "Han var en *notorisk* lögnare som ingen trodde på."],
    ["OBSOLET", "Tekniken blev *obsolet* på bara några år."],
    ["OBSTINAT", "Barnet var *obstinat* och vägrade ta på sig jackan."],
    ["OMNIPOTENT", "I sagan framställs kungen som nästan *omnipotent*."],
    ["OPPORTUNIST", "Som *opportunist* bytte han parti så fort vinden vände."],
    ["ORTODOX", "Hon valde en *ortodox* metod snarare än att experimentera."],
    ["PARADOX", "Det är en *paradox* att mer information kan göra oss mindre säkra."],
    ["PATETISK", "Hans försök att ursäkta sig var närmast *patetiskt*."],
    ["PEDANTISK", "Den *pedantiske* redaktören rättade varje kommatecken."],
    ["PEJORATIV", "Ordet har fått en *pejorativ* klang med tiden."],
    ["PERIFER", "Frågan är *perifer* för undersökningens syfte."],
    ["PERTINENT", "Hon ställde en *pertinent* fråga som träffade kärnan i problemet."],
    ["PLAUSIBEL", "Förklaringen lät *plausibel*, men den var inte bevisad."],
    ["POLEMIK", "Debattartikeln innehöll skarp *polemik* mot regeringen."],
    ["PRAGMATISK", "Hon valde en *pragmatisk* lösning i stället för den perfekta."],
    ["PREKÄR", "Situationen på sjukhuset var *prekär* under vintern."],
    ["PRETENTIÖS", "Menyn var *pretentiös* men maten var enkel."],
    ["PROFAN", "Kyrkan användes för *profana* ändamål efter reformationen."],
    ["PROSAISK", "Förklaringen var betydligt mer *prosaisk* än ryktena."],
    ["PUERIL", "Hans skämt var *puerila* och föll platt."],
    ["PÅTAGLIG", "Det fanns en *påtaglig* spänning i rummet."],
    ["RADIKAL", "Reformen innebar en *radikal* förändring av skolan."],
    ["RAFFINERAD", "Hon hade en *raffinerad* smak för konst."],
    ["RATIFICERA", "Riksdagen *ratificerade* avtalet i december."],
    ["REDUNDANT", "Stycket är *redundant* eftersom samma sak redan sagts."],
    ["RENEGAT", "Partiet betraktade honom som en *renegat* efter avhoppet."],
    ["RESIGNERAD", "Hon lät *resignerad* när hon berättade om beslutet."],
    ["RETORIK", "Politikerns *retorik* var slagkraftig men innehållslös."],
    ["RIGID", "Systemet är för *rigidt* för att klara oväntade händelser."],
    ["RUDIMENTÄR", "Han hade bara *rudimentära* kunskaper i franska."],
    ["SAKROSANKT", "För honom var söndagsmiddagen *sakrosankt*."],
    ["SARDONISK", "Hon log ett *sardoniskt* leende åt hans ursäkter."],
    ["SERVIL", "Den *servile* tjänstemannen höll alltid med chefen."],
    ["SINEKUR", "Posten var en ren *sinekur* med hög lön och inga uppgifter."],
    ["SKEPSIS", "Förslaget möttes av *skepsis* från experterna."],
    ["SPORADISK", "Det har bara kommit *sporadiska* rapporter från området."],
    ["STAGNATION", "Ekonomin präglades av *stagnation* under hela årtiondet."],
    ["STOISK", "Hon tog emot beskedet med *stoiskt* lugn."],
    ["STRINGENT", "Resonemanget var *stringent* och lätt att följa."],
    ["SUBTIL", "Skillnaden mellan orden är *subtil* men viktig."],
    ["SUFFISANT", "Han log *suffisant* när han fick rätt."],
    ["TAUTOLOGI", "\"En gammal åldring\" är en *tautologi*."],
    ["TENDENTIÖS", "Rapporten kritiserades för att vara *tendentiös*."],
    ["TENTATIV", "Vi har kommit överens om en *tentativ* tidsplan."],
    ["TRIVIAL", "Problemet visade sig vara *trivialt* att lösa."],
    ["TRUISM", "Att träning är nyttigt är närmast en *truism*."],
    ["UBIKVITÄR", "Mobiltelefonen har blivit *ubikvitär* i vår vardag."],
    ["UTOPI", "Ett samhälle helt utan konflikter är en *utopi*."],
    ["VEDERHÄFTIG", "Uppgifterna kommer från en *vederhäftig* källa."],
    ["VIDLYFTIG", "Hans *vidlyftiga* planer krävde enorma summor pengar."],
    ["VIRULENT", "En *virulent* kampanj riktades mot journalisten."],
    ["VOLATIL", "Aktiemarknaden var *volatil* under krisen."],
    ["ÖVERSEENDE", "Läraren visade *överseende* med förseningen."],
    ["ABERRATION", "Den dåliga matchen var en *aberration* i en annars fin säsong."],
    ["ACKVIRERA", "Museet *ackvirerade* tre nya målningar i år."],
    ["ADJUNGERA", "Hon *adjungerades* till styrelsen för att bidra med juridisk kompetens."],
    ["ANTIKVERAD", "Hans syn på kvinnor var hopplöst *antikverad*."],
    ["APODIKTISK", "Han uttalade sig *apodiktiskt*, som om ingen kunde ha en annan åsikt."],
    ["APOKALYPS", "Filmen skildrar en *apokalyps* där städerna ligger öde."],
    ["AUTODIDAKT", "Som *autodidakt* hade han lärt sig programmera helt på egen hand."],
    ["AVARTAD", "Festen hade *avartat* till ett slagsmål."],
    ["BEFRYNDAD", "Svenska är nära *befryndat* med norska."],
    ["BESTÖRT", "Hon blev *bestört* när hon fick höra nyheten."],
    ["BEVINGAD", "\"Att vara eller inte vara\" är ett *bevingat* uttryck."],
    ["BYSANTINSK", "Ansökningsprocessen var så *bysantinsk* att många gav upp."],
    ["CHIMÄR", "Drömmen om evig ungdom är en *chimär*."],
    ["DECIMERA", "Befolkningen *decimerades* av pesten."],
    ["DEMISSION", "Regeringen lämnade in sin *demission* efter valet."],
    ["DETERMINERA", "Arv och miljö *determinerar* tillsammans vår utveckling."],
    ["DIVERGENS", "Det fanns en tydlig *divergens* mellan teorierna."],
    ["EGENNYTTIG", "Hans hjälp var inte helt osjälvisk – den var ganska *egennyttig*."],
    ["ENTOURAGE", "Stjärnan kom med hela sitt *entourage*."],
    ["ESKAPISM", "För många är fantasyböcker en form av *eskapism*."],
    ["EXTRAPOLERA", "Man kan inte *extrapolera* resultaten från möss till människor."],
    ["FACIT", "*Facit* av säsongen blev två vinster och tio förluster."],
    ["FILIPPIKA", "Oppositionsledaren höll en lång *filippika* mot regeringen."],
    ["FURORE", "Hennes debutroman gjorde *furore* bland kritikerna."],
    ["GENMÄLE", "Ministern skrev ett skarpt *genmäle* till debattartikeln."],
    ["GUNSTLING", "Kungens *gunstling* fick allt större makt vid hovet."],
    ["HAGIOGRAFI", "Biografin är snarare en *hagiografi* än en kritisk granskning."],
    ["HARANG", "Han höll en lång *harang* om ungdomens förfall."],
    ["HOMAGE", "Filmen är en *homage* till de gamla stumfilmerna."],
    ["HUGAD", "Är du *hugad* att följa med på utflykten?"],
    ["HUMBUG", "Den mirakulösa kuren visade sig vara ren *humbug*."],
    ["IKONOKLAST", "Som konstnär var hon en *ikonoklast* som bröt mot alla konventioner."],
    ["IMPERATIV", "Det är *imperativt* att vi agerar nu."],
    ["INBITEN", "Han är en *inbiten* kaffedrickare."],
    ["INCITAMENT", "Bonusen blev ett starkt *incitament* att jobba hårdare."],
    ["INSIPID", "Soppan var *insipid* och behövde mer salt."],
    ["INTERIMISTISK", "En *interimistisk* ledning tog över tills en ny vd hittats."],
    ["INTRANSIGENT", "Parterna var *intransigenta* och förhandlingarna strandade."],
    ["INTROSPEKTION", "Dagboken blev ett verktyg för *introspektion*."],
    ["KADENS", "Talet hade en behaglig *kadens* som fångade publiken."],
    ["KALIBER", "Hon är en forskare av internationell *kaliber*."],
    ["KAMRER", "*Kamreren* kontrollerade alla utbetalningar noga."],
    ["KOLPORTERA", "Tidningen *kolporterade* rykten utan att kontrollera dem."],
    ["KONSILIANT", "Den nya chefen var *konsiliant* och lyssnade på alla."],
    ["KONSTERNERAD", "Hon blev *konsternerad* över det oväntade beskedet."],
    ["KOTERI", "Ett litet *koteri* av konstnärer styrde utställningen."],
    ["KRUMBUKT", "Han svarade utan *krumbukter* – rakt på sak."],
    ["KULPABEL", "Chefen var lika *kulpabel* som de anställda."],
    ["KURIOSA", "Museet visade samlarens *kuriosa* från hela världen."],
    ["LAKEJ", "Kritikerna kallade honom maktens *lakej*."],
    ["LÄTTING", "Den *lättingen* har inte diskat på en vecka!"],
    ["MAKULERA", "Biljetterna *makulerades* efter föreställningen."],
    ["MALKONTENT", "En grupp *malkontenter* protesterade mot varje beslut."],
    ["MECENAT", "Utan sina *mecenater* hade konstnären aldrig kunnat måla."],
    ["MEDDELSAM", "Den annars tystlåtne mannen blev *meddelsam* efter middagen."],
    ["MISSTYCKA", "Om du inte *misstycker* öppnar jag fönstret."],
    ["MOROS", "Han var *moros* hela morgonen."],
    ["NEOLOGISM", "\"Hen\" var en gång en *neologism* i svenskan."],
    ["NÄPSA", "Barnet blev *näpst* för sin fräckhet."],
    ["OKTROJ", "Beslutet uppfattades som en *oktroj* från huvudkontoret."],
    ["OMEN", "Den svarta katten sågs som ett dåligt *omen*."],
    ["OPULENT", "Slottet var *opulent* inrett med guld och marmor."],
    ["OSTRACISM", "Visselblåsaren drabbades av *ostracism* på arbetsplatsen."],
    ["OUTRERAD", "Hans skådespeleri var *outrerat* och överdrivet."],
    ["PARIA", "Efter skandalen blev han en *paria* i branschen."],
    ["PATINA", "Den gamla kopparstatyn hade fått en grön *patina*."],
    ["PEKUNIÄR", "Stiftelsen gav *pekuniärt* stöd till unga forskare."],
    ["PERFID", "Det var en *perfid* plan att lura de äldre på pengar."],
    ["PERPLEX", "Hon blev helt *perplex* när hon såg resultatet."],
    ["PETITESS", "Låt oss inte bråka om *petitesser*."],
    ["PLEONASM", "\"Fri gratis\" är en *pleonasm*."],
    ["PREGNANT", "Hon sammanfattade läget i en *pregnant* mening."],
    ["PYRRHUSSEGER", "Att vinna rättegången men förlora alla kunder var en *pyrrhusseger*."],
    ["RALJERA", "Han *raljerade* över kollegans försök att sjunga."],
    ["RECIDIV", "Patienten fick ett *recidiv* efter ett år."],
    ["REPRIMAND", "Den anställde fick en skarp *reprimand* av chefen."],
    ["RESPIT", "Banken gav familjen ett kort *respit* med betalningen."],
    ["SEKUNDERA", "Hon *sekunderade* förslaget på mötet."],
    ["STOFIL", "Den gamle *stofilen* klagade på dagens ungdom."],
    ["STRAPATS", "Resan över bergen var en riktig *strapats*."],
    ["SUBALTERN", "Han hade bara en *subaltern* befattning på ministeriet."],
    ["SUPPLIK", "Byborna skickade en *supplik* till kungen."],
    ["SYKOFANT", "Hovet var fullt av *sykofanter* som smickrade drottningen."],
    ["TONDÖV", "Han är helt *tondöv* och sjunger alltid falskt."],
    ["TRANSITORISK", "Inflationen bedömdes vara *transitorisk*."],
    ["TVEHÅGSEN", "Hon var *tvehågsen* inför erbjudandet."],
    ["UPPBRAGT", "De *uppbragta* föräldrarna krävde ett möte med rektorn."],
    ["URMODIG", "Han hade en *urmodig* kostym från 1970-talet."],
    ["VEDERSTYGGLIG", "Brottet var *vederstyggligt* och väckte avsky."],
    ["VINDFLÖJEL", "Politikern kallades *vindflöjel* för att han ständigt bytte åsikt."],
    ["YVIG", "Hon hade *yvigt* hår som stack ut åt alla håll."],
    ["ÅBEROPA", "Advokaten *åberopade* ett tidigare rättsfall."],
  ];
  if (typeof module !== "undefined" && module.exports) module.exports = WOTD;
  else root.HP_WOTD = WOTD;
})(this);
